- blivet/devicetree.py
This goes with rhinstaller/anaconda#60
- move getRelatedDisks into blivet as suggested by both @vpodzime and @mulkieran
- tweak getDependentDevices to (optionally) work with hidden devices
> Bits needed to enforce sane disk selection in anaconda

- blivet/size.py
- tests/size_test.py
I need to pickle size instances in blivet-gui for multiprocess communication and \__reduce__ function inherited from decimal causes precision loss and other problems.
> Pickling support for Size

- blivet/errors.py
- blivet/osinstall.py
- blivet/populator.py
- python-blivet.spec
There are some issues that must be resolved before blivet can do anything useful. The two that this PR addresses are multiple LVM VGs with the same name and disklabel corruption that prevents parted from acknowledging a disklabel when partitions are present on the disk.
Until the lvm tools accept UUID in place of VG name for at least lvremove, vgchange, and vgremove we have no way to work with multiple VGs with the same name. This related bug has been sitting since 2008: https://bugzilla.redhat.com/show_bug.cgi?id=449832
The first patch enables parted to proceed with a partially-corrupt GPT disklabel, but I suspect it will not cover all such cases, hence the exception handling.
There will soon be an accompanying anaconda PR that handles these exceptions by showing the error and the …
> Do not continue when presented with unusable storage configurations

- Makefile
- blivet/blivet.py
- blivet/devices/file.py
- blivet/fcoe.py
- blivet/formats/__init__.py
- blivet/formats/prepboot.py
- blivet/iscsi.py
- blivet/osinstall.py
- blivet/partitioning.py
- blivet/size.py
- blivet/util.py
- python-blivet.spec
- tests/formats_test/labeling_test.py
- tests/size_test.py
Fixes for Python 3 compatibility issues discovered while running tests with Python 3 including hundreds of installations with Python 3 Anaconda. With all that passing in the end, I decided to add the pieces that make sure the python3 subpackage is built too (tested in [Copr builds] (https://copr.fedoraproject.org/coprs/bkabrda/py3anaconda/builds/)).
**Disclaimer:** 
These patches don't try to fix anything else than Python 3 incompatibilities in the most straightforward way. Many changes are subject for future improvements and nicer solutions.
> Fix some Python 3 compatibility issues and add the python3 subpackage

- blivet/devicefactory.py
- blivet/devicelibs/lvm.py
- blivet/devices/btrfs.py
- blivet/devices/disk.py
- blivet/devices/dm.py
- blivet/devices/loop.py
- blivet/devices/lvm.py
- blivet/devices/md.py
- blivet/devices/partition.py
- blivet/devicetree.py
- blivet/formats/__init__.py
- blivet/formats/fs.py
- blivet/formats/luks.py
- blivet/formats/lvmpv.py
- blivet/formats/mdraid.py
- blivet/formats/swap.py
- blivet/osinstall.py
- blivet/partitioning.py
- blivet/util.py
- python-blivet.spec
- tests/devices_test.py
As of version 0.10 libblockdev provides better error reporting if its ErrorProxy
instances are used (e.g. blockdev.lvm.lvcreate instead of lvm.lvm_lvcreate where
blockdev.lvm is an ErrorProxy instance). Let's make use of this feature and
catch native python exceptions defined in libblockdev's python GI overrides
instead of GLib.GError.
> Make use of the new libblockdev error reporting

- blivet/devices/md.py
The basic problem is that level is a very important concept for md
so a lot of log messages log this information. Some of these
log messages are executed as a result of running the parent constructor.
The particular problem I saw is that self.updateSize() is called by
StorageDevice.__init__, which understandably logs the size,
and the size() methods logs its result, along with the level, leading to
an AttributeError. Now there will be no AttributeError, but the RAID
level will be displayed as None when this happens.
> Move definition of _level attribute above super-constructor call.

- blivet/actionlist.py
- blivet/formats/lvmpv.py
See https://bugzilla.redhat.com/show_bug.cgi?id=1212841
Currently is not possible to add new partitions to disk with an existing LVM VG. 'findActiveDevicesOnActionDisks' should disallow only actions involving changes on the disklabel not adding new partitions.
> Fix adding new partitions on disks with active devices

- blivet/devicelibs/lvm.py
Resolves: rhbz#1206526
Currently blivet exepects pesize parm of the vgcreate function
should be in MiB. Any given value will be converted to MiB format
and omits any fractional part. That means, if any KiB values are
passed to pesize parm, it becomes 0 and the actual lvm lvcreate
faild to create the vg and returns an error.
This limits passing any KiB values for pesize to create a vg.
This patch fixes the issue by accepting the given value in KiB.
Submitted-by: Timothy Asir Jeyasingh <tjeyasin@redhat.com>
> Allow passing KiB values to vgcreate -s option

- blivet/devicetree.py
Assume that whenever lvm presents blivet w/ a name with two consecutive
dashes this represents an escaped single dash.
Previously only doing this for lvmvg's and lvmlv's, which turned out
to be a problem when looking up subclass instances, like lvm thin lvs.
> Un-escape '-'s in names or paths for _all_ lvm lv or vgs.

- blivet/blivet.py
- blivet/mounts.py
Supersedes PR#107.
The final patch, "Cache data..." is the only interesting one.
The main change from previous PR is that since mountinfo cache is only needed in _getActiveMounts(), it is only instantiated there. In #107 is was an attribute of the mounts cache, which was excessive. This way, the cache needs to be managed less, which is good.
> Master btrfs c

- tests/pylint/runpylint.py
GError and Error are just aliases of each other, and GError is more
distinctive, thus a better choice for filtering so long as it is
used always in place of Error.
Should have gone in with commit 3f0aa449e42bc64da78e2ff8c0553b4526deed00.
> Filter GLib.GError instead of GLib.Error in pylint false positives.

- blivet/devices/lvm.py
- blivet/util.py
New version of #99 
-----
Override readCurrentSize of LVM old-style snapshots to check size
on COW device instead of snapshot device. (The latter one reports
snapshot to be same size as the LV.)
Signed-off-by: Vojtech Trefny <vtrefny@redhat.com>
> Use COW device to get actual size of LVM snapshots

- blivet/devices/disk.py
- blivet/devices/storage.py
- blivet/populator.py
Also make sure _model and _vendor attrs are never set to None in the
StorageDevice constructor.
Fixes #84
> Store vendor/model information for DiskDevice instances.

- blivet/__init__.py
- python-blivet.spec
In version 1.0 the libblockdev library changes the initialization functions a
bit and thanks to that we may simplify our code.
> Adapt to the new libblockdev initialization API

- Makefile
It has become impossible to do builds for rawhide from previous releases
because the system is expected to match what it's being built for. Run
make check manually when making commits instead.
> Drop check from the release build target

- blivet/size.py
- blivet/udev.py
- tests/loopbackedtestcase.py
- tests/size_test.py
- tests/util_test.py
Supersedes #124. The only changes are to setUp() and tearDown() in loopbackedtestcase.py.
Uses tempfile.TemporaryNamedFile in setUp() and has tearDown() separate removing loop device from unlinking backing store.
> Master keepers c

- blivet/devices/storage.py
- tests/devicelibs_test/edd_test.py
It not only returns an iterator in Python 3, it actually works in the lazy
evaluation fashion. So if its returned value is not iterated over, the passed
function is not called on the iterable's items. Let's use a for cycle in these
places to make the iteration and function calls explicit.
> Beware of Python 3's version of the map() built-in function

- blivet/devicetree.py
- blivet/formats/lvmpv.py
> Allow adding new partitions to disks with active devices

- .gitignore
- doc/Makefile
- doc/_inheritance.rst
- doc/conf.py
- doc/index.rst
- doc/intro.rst
- tests/README.rst
* No longer explicitly remove files in apidoc target, all handled in clean.
* Put autogenerated .rst files in subdirectories and gitignore them.
* Create a hidden file which includes some inheritance diagrams.
* Add commented out option for inheritance graph in conf.py.
* Include documentation for test modules at top level.
* Include documentation about testing in the introduction.
* Get rid of unnecessary MODULE_NAMES variable.
> Include automatic and manual test documentation.

- blivet/devices/partition.py
- blivet/partitioning.py
I think it's easier to review the whole resulting diff as things move back and forth in the commits. One question -- is it correct that all the commits have 'Related: rhbz#1202877' instead of the original bugs referenced?
> RHEL 7.2 cherry-picks

- tests/action_test.py
- tests/devicefactory_test.py
- tests/devicelibs_test/mdraid_test.py
- tests/devicelibs_test/raid_test.py
- tests/devices_test/dependencies_test.py
- tests/devices_test/device_names_test.py
- tests/devices_test/device_packages_test.py
- tests/devices_test/device_properties_test.py
- tests/devices_test/lvm_test.py
- tests/devices_test/network_test.py
- tests/devices_test/partition_test.py
- tests/devicetree_test.py
- tests/formats_test/device_test.py
- tests/formats_test/fs_test.py
- tests/formats_test/fslabeling.py
- tests/formats_test/fstesting.py
- tests/formats_test/init_test.py
- tests/formats_test/labeling_test.py
- tests/formats_test/selinux_test.py
- tests/parentlist_test.py
- tests/partitioning_test.py
- tests/size_test.py
- tests/storagetestcase.py
- tests/tasks_test/basic_tests.py
- tests/tsort_test.py
- tests/udev_test.py
- tests/util_test.py
* Remove #!/usr/bin/python shebang from tests.
* Remove unittest.main() from tests.
* Remove a definition of suite method, which we no longer use.
The tests should be run via the unittest discovery mechanism.
They are best run by invoking the "test" target in the Makefile.
This allows any necessary setup to occur, including overrides
for Python2/3 compatibility.
> Remove facilities for running tests as standalone modules.

- doc/Makefile
doctest target was removed in fed53d969af0eddaeeca58cdf3e40916497aa305. This PR cleans up a bit more.
> Remove mention of doctest b/c target was removed

- Makefile
Check that dependencies for testing are available.
> Parameterize Makefile test targets on Python version.

- blivet/deviceaction.py
Simple fix for https://bugzilla.redhat.com/show_bug.cgi?id=1225352 Cancelling of ActionResizeFormat fails because the origSize is set to format.targetSize that can be 0.
> Fix setting original size for format resize action. (#1225352)

- tests/__init__.py
- tests/action_test.py
- tests/devicefactory_test.py
- tests/devicelibs_test/raid_test.py
- tests/devices_test/device_properties_test.py
- tests/devices_test/lvm_test.py
- tests/devices_test/partition_test.py
- tests/formats_test/fslabeling.py
- tests/partitioning_test.py
- tests/size_test.py
- tests/tsort_test.py
From the original review in PR #120
@mulkieran
> Please use "with self.assertRaises" everywhere. It's just easier on the eyes.
This doesn't work b/c assertRaises and assertRaisesRegex are different. I'm not quite sure what do you mean but directly changing one for the other doesn't seem to work.
> Also, we always use six.PY2 and six.PY3 to check the python version for this kind of thing, not sys.version_info, so it's probably best to stick with that.
Fixed.
> I think you should be able to avoid modifying the class hierarchy to deal with the versioning problem in commit 3. You might consider modifying unittest.TestCase instead, for example.
Let me see how can I do this. Is there a place where I can hook into before the test cases are actually executed? If so I can monkey-patch …
> Fix tests deprecation warnings in a backward compatible way

- tests/devices_test/device_packages_test.py
> Sort the lists before comparing because coversion to set reverses order in Python3

- blivet/formats/fs.py
- blivet/size.py
- tests/size_test.py
These came up while working on LUKS resize but are in some sense orthogonal.
Extending Size.convertTo() to take Size parameter is necessary for resizing LUKS format to multiples
of sector size, but also brings convertTo() into line with roundToNearest(), which now also takes
a Size parameter and generally makes it more useful.
Changes to FS._setTargetSize() came up when hoisting size related methods to DeviceFormat.
> Some small patches

- blivet/actionlist.py
- blivet/devices/md.py
- blivet/devices/partition.py
- blivet/devices/storage.py
We began using this metadata version because grub1 could not read arrays with v1.1 or newer metadata. Now that we're using grub2 we can stop using v1.0. The UEFI bootloader still needs us to use v1.0 for /boot/efi arrays.
See https://bugzilla.redhat.com/show_bug.cgi?id=1061711#c6
> Use default md metadata version for everything except /boot/efi

- blivet/blivet.py
- blivet/devicelibs/lvm.py
- blivet/devices/lvm.py
- blivet/devices/storage.py
- blivet/populator.py
- python-blivet.spec
This is really more a request for comments than a real pull request as I'd like to know your opinion on the chosen approach. Making blivet aware of internal LVs is one of the crucial steps towards creation and manipulation of thin/cache pools' metadata volumes and other things.
The internal LVs are not part of the DeviceTree, they are only referenced by their "parent" LVs as they should not be manipulated with directly and because there may be many of them (tens on quite simple setups). However, these LVs are still just LVs like any other as far as things like name, UUID, size, etc. go.
> Make blivet aware of internal LVs

- blivet/devices/md.py
- blivet/populator.py
The motivation here is to enable hardware vendors to use regular md arrays for fwraid without the need for mdmonitor. The difficulty is that there will be nothing to distinguish these fwraid arrays from any other user-created array whose members are disks.
Existing arrays whose members/parents are all partitionable will be partitionable.
Existing arrays whose members/parents are all disks will be treated as disks.
It shouldn't be possible to delete such arrays in anaconda. They should be treated like fwraid arrays. It will be possible to delete them in blivet by scheduling an `ActionDestroyFormat`/`ActionDestroyDevice` action pair, but calling `DeviceTree.recursiveRemove` on them will not destroy the array.
> Allow partitioning of md arrays whose members are all disks

- blivet/devices/cache.py
- blivet/devices/lvm.py
These commits add generic classes for Cache monitoring, manipulation and reporting, the implementation for the LVM Cache and pieces of code needed for the ``LVMLogicalVolumeDevice`` class to support cached LVs.
The reason why cached LV is not a new, separate class is that when the cache is detached, such (formerly) cached LV becomes a normal LV like any other and its not possible to change the type/class of an existing object. Thus the ``LVMCache`` class is added instead the instances of which are referenced by cached LVs and provide the cache-related functionality to them. The same approach will be later used for ``BcacheDevice`` and ``BcacheCache`` classes (a device can be formatted as a ``BcacheDevice`` with no cache attached to it).
> LVM cache detection, manipulation and reporting

- blivet/blivet.py
- blivet/devices/btrfs.py
- blivet/devices/storage.py
- blivet/populator.py
- blivet/tasks/fsck.py
- blivet/tasks/fsinfo.py
- blivet/tasks/fsminsize.py
- blivet/tasks/fsmkfs.py
- blivet/tasks/fsmount.py
- blivet/tasks/fsreadlabel.py
- blivet/tasks/fsresize.py
- blivet/tasks/fssize.py
- blivet/tasks/fssync.py
- blivet/tasks/fstask.py
- blivet/tasks/fswritelabel.py
This is an alternative to #165. The approach is to deepcopy all format objects when copying, instead of to define an ```__copy__``` method that handles tasks specially.
The first two patches are the same as in #165.
It's tested, in that I tried an experiment whereby I made a deep copy of all formats objects in fstesting.py and ran all tests on the deepcopy, rather than the original format object, and they all passed. Using copy, instead of deepcopy, they all failed. Using copy, and overriding ```__copy__``` in FS, they all passed.
It should be noted that format objects are already deep copied, rather than shallow copied, in actionlist.
> Master format copy b

- blivet/__init__.py
- blivet/devicetree.py
- blivet/util.py
`getDevicesBySerial` has no callers and the other two don't offer any value beyond their list comprehension equivalents `[d for d in dt.devices if isinstance(d, cls)]` (`getDevicesByInstance`) and `[d for d in dt.devices if d.type == devtype]` (`getDevicesByType`).
The first patch establishes a basic procedure for deprecating things in blivet. The warnings will only be logged if someone has called `blivet.util.set_up_logging`.
> Deprecate some little-used device lookup methods

- Makefile
Only output the parts about packages that are not installed.
> Make check-requires errors more readable.

- blivet/devices/lvm.py
- blivet/devices/partition.py
- blivet/devices/storage.py
- tests/devices_test/size_test.py
This fixes several minor problems and adds some unit tests to ensure the correct behaviors are preserved in the future.
We shouldn't be setting the target size from the size setter under any circumstances. The size reflects reality for existing devices and the planned reality for non-existent devices. Target size is only for resize of existing devices. The setter for one should not modify the other.
> Clean up device size properties a bit

- blivet/__init__.py
This makes the 'TAB-TAB' completion in ipython and dir() calls work as if the
lazy-imported object was imported in a normal way.
> Implement the __dir__ method of the LazyImportObject class

- blivet/partitioning.py
Using true division results in a float, which eventually causes
a crash when the value is passed to sectorsToSize(), which
tries to multiply it by a Size. Multiplying a float by a Size
doesn't work. sectorsToSize() does specify that it needs an int.
This is a python2 vs. python3 thing: in py2, int/int returns
an int. See PEP 238.
This fixes #1245854 and #1245446 (tested).
> use floor division in calculating amount to reclaim (#1245446)

- blivet/devicefactory.py
- blivet/devices/lvm.py
- blivet/devices/storage.py
@kellinm The ones you're interested in are a5000d4, a800128, and b8b2c48
> More followups for size property changes

- python-blivet.spec
With providing both Python 2 and Python 3 packages we need to make sure both
have the translations available. This commit makes the translations shared by
both Python 2 and 3 subpackages by putting them into a separate subpackage
required by both.
> Put translations into a subpackage shared by Python 2 and 3

- blivet/formats/luks.py
It should be 'npass' not 'new_passphrase'.
> Fix name of the keyword argument for luks_add_key

- Makefile
- blivet/devices/disk.py
- tests/devicefactory_test.py
- tests/imagebackedtestcase.py
- tests/loopbackedtestcase.py
Improvement of loop device cleanup and disabling of image-backed tests are so we can start running the test suite in jenkins again, @clumens.
The device factory tests fail without the changes from #182. They increase coverage of devicefactory.py from 19% to 74% (IIRC).
> Various small test changes

- blivet/mounts.py
- blivet/udev.py
This makes it possible to use any valid device spec when accessing the cache. All device specs are resolved to the basename canonical device node name (eg: `dm-1`, `md127p2`) before being stored or search for.
It turns out that `/proc/mounts` contains `/dev/mapper/` symlinks for device-mapper devices, but does not contain `/dev/md/` symlinks for md devices. We avoid this circus by using only the canonical device node name in the cache itself. We use udev to resolve device specs to the canonical names.
> Fix mount cache for devices with symlinks

- blivet/blivet.py
- blivet/deviceaction.py
- blivet/devices/cache.py
- blivet/devices/lvm.py
- blivet/partitioning.py
Commits that add support for creation of cached LVs plus two minor changes that make things a bit nicer. Please note that I'm intentionally leaving the changes in the last commit as a standalone commit as it needs some attention.
> LVM cache creation

- blivet/devices/lvm.py
- tests/devices_test/device_properties_test.py
- tests/devices_test/lvm_test.py
- tests/partitioning_test.py
So that we can catch possible regressions easily in the future.
> Add unit tests for the LVM cache support

- blivet/blivet.py
Otherwise a traceback appears because thin(pool) LVs don't support this kwarg.
> Remove the cacheRequest kwarg for thin(pool) LVs (#1254567)

- blivet/formats/luks.py
Otherwise callers like anaconda would have to catch this low-level error
(requiring libblockdev as a dependency and other issues) to prevent tracebacks
when trying to unlock LUKS (possibly with a wrong passphrase).
> Do not propagate low-level blockdev.CryptoError when setting up LUKS (#1253925)

- blivet/devices/lvm.py
- blivet/partitioning.py
- tests/devices_test/device_properties_test.py
- tests/devices_test/lvm_test.py
- tests/partitioning_test.py
This pull request has three purposes (of descending importance):
1) it fixes a hidden issue discovered by anaconda's kickstart tests where the following kickstart snippet
```
logvol swap --name=swap --vgname=fedora --size=500 --fstype=swap
logvol / --name=root --vgname=fedora --size=4000 --grow --fstype=ext4 --cachepvs=pv.2 --cachesize=1000 --cachemode=writethrough
logvol /home --name=home --vgname=fedora --size=1000 --grow --fstype=ext4 --cachepvs=pv.2 --cachesize=1000 --cachemode=writeback
```
results in a successful installation, but the ``swap`` LV ends up being 8 MiB smaller. It's not the end of the world, but if the metadata size for cache was 256 MiB, it would be 256 MiB smaller which is quite a big difference. And even with the 8 MiB it's just wrong because the ``swap`` LV is the …
> Better calculate required space for LVM cache

- blivet/devicefactory.py
- blivet/devices/lvm.py
- blivet/partitioning.py
Reserving 5 extents per disk per LV for metadata if a VG is on top of RAID PVs
is a weird magic that saved us troubles with placing LVM on top of RAID, but
even on the first it's just wrong and doesn't make sense. LVM doesn't allocate
any extra meta data if an LV is added to a VG (unless it is a meta data LV of
course) and the RAID device below it (the PV) is just a block device with some
size and no matter how many disks are below, the meta data space used by LVM is
just subtracted from the RAID device's (PV's) size. Moreover the LVM extent size
has nothing to do with the RAID device so it's like mixing apples and oranges.
If things don't fit we need to tweak our calculations of free space/size in/of
an MD RAID device (depending on the level and underlying disks) since that's the
only …
> Do not reserve extra space for metadata in a VG with RAID PVs

- blivet/devices/storage.py
We want to continue to recursively deactivate the parents even if
the current device is inactive, but we don't want to run the
_postTeardown method of a device we're not deactivating.
On rhel7-branch, this will be preceded by a revert of a909ea38.
Related: rhbz#1182229
> Continue with recursive teardown beyond inactive devices.

- blivet/populator.py
multipath itself has absolutely no identifying metadata, so whatever
metadata found on the member is not related to the multipath set.
Therefore, we shouldn't be storing it in the member's format.
Resolves: rhbz#1254232
> Don't store UUIDs or labels of multipath members.

- blivet/devicelibs/raid.py
- blivet/devices/lvm.py
- blivet/formats/lvmpv.py
The first commit just removes some old, naïve comments from the code. The second and third commits make our calculations related to LVM on RAID much more precise and realistic -- from ~150 MiB free space in a VG where some LV was requested to grow to a maximum size to ~4-8 MiB (1 or 2 extents). But what's more important, the calculations now reflect the real calculations that happen in the "storage land below us" and they make sense. :)
We still have the "emergency brake" making an LV smaller if it's about to be created in a VG that doesn't have enough space for it so this should be safe. Plus I'm only proposing this for *master* right now and I'll make anaconda's kickstart tests stricter so that they reveal any potential issues this could cause and any future changes breaking this.
> Improvements for LVM on RAID calculations

- blivet/devicelibs/lvm.py
- blivet/devices/lvm.py
When lvmetad is running and the last PV in a VG is activated, an asynchronous system unit (`lvm2-pvscan@...service`) is scheduled to update LVM's view of things and to auto-activate the LVs. During the interim between that unit being scheduled and run, LVM behaves as if the PV were still inactive. So, when we're deactivating/activating the PVs we should wait for auto-activation instead of plowing ahead and trying to activate the LVs ourselves. This has caused several bugs in which we activate an MD PV, then try to activate an LV, and get an error from LVM saying the VG doesn't exist.
> lvactivate when lvmetad is active

- python-blivet.spec
Also need to include the python2-devel package for the macros. Blivet's
Makefile now defaults to python3 so we need to explicitly set the python
version when installing.
> Always build python2 and python3 versions.

- blivet/devicelibs/lvm.py
- blivet/flags.py
Many times we have been asked by the LVM team to use the '-vvvv' option whenever
we do any LVM action so that the logs contain more (debugging)
information. However, getting the output of every single LVM command cluttered
with a lot of debugging info would be confusing for both us reading the logs and
the code parsing the output of such commands. The trade-off solution is to pass
the 'log{level=7}' config with all our commands that causes LVM to put the extra
info from '-vvvv' to syslog where it looks like all the other crystal-clear
stuff.
> Add a 'debug' flag and use it for LVM debugging

- blivet/errors.py
- blivet/formats/disklabel.py
- blivet/partitioning.py
- tests/formats_test/disklabel_test.py
- tests/partitioning_test.py
Without this patch, blivet cannot create any partition smaller than the optimal io size reported by the disk it's being created on (without passing a start sector to `partitioninging.addPartition` to disable alignment). This PR makes it possible.
> Allow allocation of small, minimally-aligned partitions.

- blivet/devicetree.py
- tests/devicetree_test.py
This prevented proper resolution of some partition names.
Fixes #152
> Fix an overly inclusive regex in DeviceTree.resolveDevice.

- blivet/__init__.py
- blivet/devicelibs/edd.py
- blivet/util.py
- tests/devicelibs_test/edd_test.py
This adds another logger that we can use to write data to about what we
find on the filesystem, in such a way that we can use that data to
recreate test cases later, automatically, from the log.
This also adds that data to all the EDD code.  The result is the attached log from our test data:
[blivet-edd-testdata.log.txt](https://github.com/rhinstaller/blivet/files/21790/blivet-edd-testdata.log.txt)
> Make a logger for test data that we can automatically use later

- .gitignore
This adds pylint-log and tests/pylint/.pylint.d/ to .gitignore.
I hate looking at this stuff in "git status", but removing it isn't
worth the trouble.
Signed-off-by: Peter Jones <pjones@redhat.com>
> Add pylint stuff to .gitignore

- blivet/populator.py
- tests/populator_test.py
The size needs to be updated after the sysfs path has been setup.
Related: rhbz#1252703
This is fixed on rhel7-branch but not on master:
https://github.com/rhinstaller/blivet/commit/828ddb09535357a35bde6b3b18ae871bfe2c52ad
The result is --image installs don't work b/c the device has size 0 and anaconda ignores it. I've also added a test case for this. It looks like this test should probably go into anaconda but I'm not sure if the infrastructure there allows for that that's why I've added it here.
> Update dmdev size when setting up disk images

- blivet/devicefactory.py
- blivet/devices/lvm.py
The key commit here is the third one (https://github.com/rhinstaller/blivet/commit/9c30318f34093253e0c875ab8b25522069f0e654). It fixes an issue our tests caught together with a recent change in libblockdev. These together revealed the fact that the LVMFactory doesn't account for LVM metadata taking space from the PVs.
The other patches are just to make this change nicer.
> LVM factory LVM metadata

- blivet/blivet.py
It's good to log the full format we instantiated, but we should be
inlcuding the type -- not a DeviceFormat instance -- in the error
message.
> Improve clarity of error when setting new default fstype fails.

- blivet/util.py
- tests/util_test.py
namedtuple classes are great as pure data objects one can store things in and
then access them really easily. The problem is that if a new field is added to a
namedtuple, all places creating instances of it has to be modified to provide a
value for that new field. The default_namedtuple class constructor implemented
in this commit constructs namedtuples with default values for (some) fields and
fields without any value passed defaulting to None.
Such default namedtuple classes are still great for storing data and
e.g. passing data to functions/methods grouped into a few objects (like
DeviceInfo, FormatInfo,...) passed as arguments, but allow us to add extra
fields in the future (e.g. a new device attribute to DeviceInfo) without
breaking the API.
> Add a class constructor for namedtuples with default values

- blivet/devices/lvm.py
If the cached LV is not active, we cannot determine the size of its cache from
the stats because these are only available for activated LVs. However, if the LV
and cache exist, we examined them on devicetree population and got the
information about the size at that point. Thus we can used the stored value if
the LV is no longer active.
Also, keep the logic of when we should be able to get stats in one place.
note: this fixes a bug I hit when trying to install F23 on my workstation -- blivet.reset() fails because when we try to dump the state, the cached LV is inactive.
> Do not try to get LVM cache's size from stats for inactive LV

- blivet/autopart.py
- blivet/blivet.py
- blivet/devicefactory.py
- blivet/osinstall.py
- blivet/populator.py
In order to have a nicer code we have recently moved from camelCase names to
split_words names. While the change covered all the direct accesses (pylint
would catch any problematic ones), it didn't cover the cases where we access the
items indirectly via the getattr() call. This fixes all the getattr() calls that
tried to access any camelCase items.
> Update the getattr calls with PEP8 property/attribute names

- scripts/makebumpver
In conf.py release and version are the same thing, only version needs to
be updated with the new version string.
> Fix makebumpver for new conf.py

- blivet/util.py
Otherwise we get things like this:
'/home/user/sources/blivet/None/sys/devices/.../block/sda/size'
which is not really what we want.
@vathpela, could you please add unit tests for the ``Path`` class?
> Only prepend the root to get the ondisk path if there is some

- Makefile
- blivet/devicelibs/edd.py
- blivet/util.py
- tests/devicelibs_test/edd_test.py
- tests/lib.py
- tests/util_test.py
Moves 'pylint' to its own target, adds a 'pep8' target, and makes
the 'check' target empty with 'check' and 'pep8' as prerequisites.
This allows the user to run either pylint or pep8 separately or
together.
It also makes it possible to plumb a user-specified PYTHONPATH
into the 'pylint' target.
> Add PEP8 compliance checking to 'check' target.

- blivet/devicetree.py
DM maps cannot be removed while they are in use so in order to make them
removable, we need to teardown all devices "built" on top of them first. This
makes our examples (and possibly some tests) better clean after themselves.
> Teardown all descendants devices before tearing disk images down

- blivet/blivet.py
- blivet/devicefactory.py
- blivet/devices/btrfs.py
- blivet/devices/device.py
- blivet/devices/dm.py
- blivet/devices/lib.py
- blivet/devices/lvm.py
- blivet/devices/md.py
- blivet/devices/storage.py
- blivet/devicetree.py
- blivet/populator/helpers/luks.py
- blivet/populator/populator.py
- tests/devicefactory_test.py
Instead of a simple child device counter, these patches add a list of children to each `Device` instance. This makes `Device` more complete and makes `DeviceTree.get_children` unnecessary.
> Let Device know about its children

- blivet/actionlist.py
- blivet/blivet.py
- blivet/deviceaction.py
- blivet/devices/container.py
- blivet/devices/device.py
- blivet/devices/lvm.py
- blivet/devices/raid.py
- blivet/devicetree.py
- blivet/flags.py
- blivet/formats/__init__.py
- blivet/threads.py
- blivet/util.py
The idea here is to make blivet thread-safe without making a ton of changes. This adds a global reentrant lock and a metaclass. The metaclass wraps every method call with a decorator that acquires the global lock prior to calling the method.
> Make blivet thread-safe

- doc/Makefile
- doc/conf.py
- doc/intro.rst
1. Use "sphinx-build-3" and "sphinx-apidoc-3", it fixes the problem with "empty" documentation (not sure if it help with readthedocs, but it fixes the problem when building locally).
2. Fix "class:`~..." links in intro. Blivet 2.0 API change, devices split up and other changes broke them.
> Two docs related fixes

- blivet/blivet.py
- blivet/devicefactory.py
- blivet/devicelibs/lvm.py
- blivet/devices/__init__.py
- blivet/devices/btrfs.py
- blivet/devices/device.py
- blivet/devices/file.py
- blivet/devices/lvm.py
- blivet/devices/nfs.py
- blivet/devices/storage.py
- blivet/partitioning.py
- blivet/populator/helpers/lvm.py
- blivet/util.py
- release_notes.rst
- tests/devicefactory_test.py
- tests/devices_test/device_names_test.py
- tests/devices_test/lvm_test.py
- tests/devicetree_test.py
- tests/util_test.py
These commits change how we represent LVs. Instead of having special classes for various types of LVs, we now have a single class with the type of LV being more a dynamic property than a once-given thing. This will allow us to implement various LVM-related features in the future that have so far been limited by our multi-class representation.
I'm not adding any new functionality or features so no tests are added. Just the existing ones are modified to continue working.
I'll add a section to the *release_notes.rst* file tomorrow as an extra commit to this PR.
> LVM classes unification

- scripts/makebumpver
- scripts/makeupdates
- scripts/merge-pr
- setup.py
The check is no more, since it is no longer relevant in python 3.5. This
leaves the usage of the eintr_retry_call, since that is still relevant
in Python 2.
> Remove references to the interruptible-system-call check

- blivet/blivet.py
- blivet/devicelibs/crypto.py
- blivet/devices/luks.py
- blivet/devices/partition.py
- blivet/devices/storage.py
- blivet/errors.py
- blivet/formats/__init__.py
- blivet/formats/fs.py
- blivet/formats/luks.py
- blivet/osinstall.py
- blivet/tasks/dfresize.py
- blivet/tasks/fsresize.py
- blivet/tasks/lukstasks.py
- release_notes.rst
- tests/formats_test/luks_test.py
LUKS encrypted partitions resize support.
Known issues:
- `LUKSFormat` has "wrong" `min_size` -- because minimal size depends on minimal size of LUKS device's format, it's not possible to set it for LUKS format. Slave device, LUKS device and filesystem have correct min_size.
- Both `LUKSFormat` and `LUKSDevice` don't have `max_size` -- it depends on the slave device. We don't set max_size for formats (just limits), so it probably makes sense to set the max size correctly just for the slave device. But it would be easy to set the max_size correctly for the LUKS device.
- Tasks -- I just took code from mulhern's original pull request and made changes to make pep8 and pylint happy. It works, but I don't have idea how :)
- `FSError` and `FSResizeError` -- original `do_resize` and …
> LUKS resize

- blivet/devices/partition.py
- blivet/errors.py
- blivet/formats/fs.py
- blivet/partitioning.py
- blivet/size.py
- python-blivet.spec
- release_notes.rst
- tests/formats_test/misc_test.py
- tests/size_test.py
libbytesize provides an implementation of what we need for manipulations and
calculations with sizes in bytes. It's a little bit faster and more importantly
it can be shared with other projects because it's written in C. Thus we should
use it.
At some point it would be nice if we could drop our own Size class and the
blivet/size.py module altogether because they don't bring any extra value, but
for now we need this thin wrapper to keep the API (almost*) stable. The only
real changes are:
1) Strings like "100 kibibytes" are no longer accepted, I doubt anybody has ever
used this functionality. If the opposite turns out to be true such support will
be added to libbytesize and no change will be needed in Blivet.
2) humanReadable() now ignores the 'skip' and 'min_value' attributes. The former …
> Use libbytesize's Size class as a base for our Size class

- tests/populator_test.py
We don't want to use the information from the system the tests are running on
and actually we cannot even grab that information because the tests may not be
run as root. To prevent issues and exceptions, we can easily just mock all three
LVM listing functions - lvs(), vgs() and pvs().
> Mock all blockdev's listing functions for populator tests

- blivet/partitioning.py
This fixes an issue with growing thin pool requests where the thin pools don't
have their size set but their req_size is set to the sum of their thin LVs.
> Set both req_size and size of thin pool when growing LVM

- blivet/devicefactory.py
- blivet/devicelibs/raid.py
- blivet/devices/lvm.py
- blivet/partitioning.py
These are all ported patches from the master branch fixing the bug rhbz#1284660 where our magical calculations of space in case of LVM on RAID lead to a failure of installation with a valid storage configuration in kickstart.
> Port LVM on RAID space calculations fixes (#1284660)

- blivet/devices/lvm.py
- blivet/populator/helpers/lvm.py
If an internal LV is a RAID LV, it's lv_attr is really interesting. Usually
(bug in LVM?) it has 'r' as the first letter so we need to allow that and then
do some magic to correctly determine the role of the LV.
Using 'lvs -o+lv_role' would be much better for this, but I only learnt about it
today and using it would require more changes (incl. some in libblockdev).
> Correctly recognize internal RAID LVs

- CONTRIBUTING
You can see a preview of what it will look like [here](https://gist.github.com/dwlehman/ceaf09d7ae1ac1c9e13da79285f5f738).
> Update CONTRIBUTING file to match current practices.

- blivet/devicelibs/dasd.py
If using only FBA DASDs during installation, anaconda crashes when writing
dasd.conf (more specifically, when running the check to see if there are any
hyperPAV aliases). So, just be a bit safer and wrap the affected code in a
try/except block. No special handling needs to be done if OSError is thrown --
which happens if a user has only FBA DASDs -- so we can safely ignore it.
Resolves: rhbz#1031589
> Fix traceback when writing dasd.conf (#1301589)

- blivet/populator/helpers/disk.py
If its imported for the class the import happens when the class is being
initialized and thus when the module is imported. Initializing the iscsi
singleton may take time (especially when things go wrong) which makes the import
take more time than an import should take (basically none).
> Only import the 'iscsi' singleton when really needed

- blivet/devicelibs/lvm.py
- blivet/flags.py
- tests/devicelibs_test/lvm_test.py
Somehow the patches that fixed [rhbz#1066004] did not make their way into the previous blivet master branch, which means they got lost when this branch got rebased.. or something like that.
These patches should fix [rhbz#1269144] - which is a clone of [rhbz#1066004].
A little massaging was necessary to fix conflicts in the `devicelibs.lvm` refactor patch, but it *looks* correct, at least.
[rhbz#1066004]: https://bugzilla.redhat.com/show_bug.cgi?id=1066004
[rhbz#1269144]: https://bugzilla.redhat.com/show_bug.cgi?id=1269144
> suppress LVM autobackup during image installs (rhbz#1269144)

- blivet/blivet.py
- blivet/osinstall.py
- blivet/partitioning.py
- tests/partitioning_test.py
This moves a bunch of bootloader-related logic out of Blivet class and out of blivet.partitioning and into osinstall.InstallerStorage instead.
> Installer Isolation: part two (bootloader)

- blivet/populator.py
When an iso9660 is written to a USB the child partitions are excluded
from the devicetree by addUdevPartitionDevice. This means it never gets
to the point where it can protect the parent devices.
This adds a second check to see if the liveBackingDevice name starts
with any of the other device names. If so then the device is set as
protected and added to the protectedDevNames list.
> Protect the live device's parent (#1172342)

- blivet/platform.py
This provides more space to store yet more kernels.
Resolves: rhbz#1270883
> Increase the default size of /boot to 1 GB.

- python-blivet.spec
This should make it possible for users to update rawhide
smoothly, unless they have something installed that still
requires the older python-blivet that isn't getting updated.
> Obsolete python-blivet and blivet-data packages.

- blivet/partitioning.py
Instead of dividing two potentially big sizes by sector size and then comparing
the numbers of sectors we can compare the sizes and divide just the smaller
(more limitting) one. This is a minor optimization, but more importantly a nice
way to prevent issues with really big numbers that may not fit into 64bits (Size
divided by Size is a number).
Related: rhbz#1326897
> Compare sizes instead of numbers of sectors

- blivet/errors.py
- blivet/populator/helpers/partition.py
Having name of the problematic/unusable disk in this exception would help when trying to ignore the disk during (next) reset.
> Add name of problematic device to UnusableConfigurationError

- blivet/dbus/blivet.py
- tests/dbus_test.py
This is just one commit on top of #392 and #394.
I closed #395 because I accidentally created it against `master` instead of `2.2-devel`.
> Add an InitializeDisk method to DBusBlivet

- blivet/formats/lvmpv.py
If pvremove() fails, we need to jump to DeviceFormat._destroy() not destroy()
because destroy calls self._destroy() which jumps to LVMPhysicalVolume.destroy()
again because 'self' is a LVMPhysicalVolume instance.
> Break the cycle in LVMPhysicalVolume.destroy (#1331630)

- blivet/size.py
- tests/size_test.py
This should fix the recent failures of tests because of libbytesize's translations being finally in place.
> Size tests fix

- blivet/formats/__init__.py
- blivet/mounts.py
- blivet/populator/helpers/disklabel.py
Three small and simple changes that make ``reset()`` quite a bit faster (~3s on my testing VM). A lot more can/needs to be done in the future, but the rest is quite complicated.
Just a note for the second patch:
``resolve_devspec()`` is not needed there. Something like ``resolve_dev_symlink()`` would be sufficient and much more efficient, but since it is a common operation, I'd like to add such function to *libblockdev* and then do the change in *Blivet* to start using it.
> Some low-hanging fruit to speed reset() up

- blivet/size.py
- tests/size_test.py
It's always a bug to rely on some default rounding when storage is part of the
game.
> Always require the rounding mode to be specified for Size

- blivet/devices/lvm.py
Pylint somehow fails to figure out that 'parent_lv' is a property of the mixin
class and reports it to be a method which doesn't have any 'size' member.
> Ignore pylint being confused with our mixins' properties

- blivet/__init__.py
- blivet/actionlist.py
- blivet/blivet.py
- blivet/devices/btrfs.py
- blivet/flags.py
- blivet/formats/fs.py
- blivet/formats/luks.py
- blivet/osinstall.py
- blivet/partitioning.py
- blivet/populator/helpers/lvm.py
- blivet/populator/populator.py
- blivet/udev.py
- blivet/util.py
- tests/formats_test/selinux_test.py
- tests/partitioning_test.py
This gets rid of flags.installer_mode from blivet. A few flags are created in its stead which are hopefully more generic, although I'm really bad at thinking of names. In other places local/surrounding logic could be used instead of just checking for flags.installer_mode.
> Remove installer mode

- blivet/__init__.py
- blivet/devices/btrfs.py
- blivet/flags.py
Mount btrfs volumes during rescue mode (to get list of its
subvolumes) and include non-leaf btrfs subvolumes when looking for
root devices and make sure it's mounted with subvol mount option.
Resolves: rhbz#1250011
> Fix root detection on btrfs in rescue mode

- blivet/formats/fs.py
- blivet/util.py
This is a copy of how lorax handles umount. Try 3 times, sleep 1s
between retries and log the output of lsof if the logging level is debug
or higher.
_This is related to rhbz#1315541 trying to see if retrying the umount helps_
> Retry umount and log output of lsof if it fails

- blivet/devices/partition.py
Extended partitions should be protected also when at least one of
its logical partitions is protected.
> Fix protected status for extended partitions

- blivet/platform.py
We need to be able to support both msdos and GPT partitions due to various low end Single Board Computers such as the Pine64. It would be really good to have this in Fedora 24 too, I think I have got the spots needed to support msdos and GPT on both ARMv7 and aarch64, I couldn't see any spots in anaconda itself.
A lot of new aarch64 single board computer devices need old style
msdos partition types due to restrictions in booting where the SoC
boots off a u-boot, that supports uEFI booting, written to the area
that is occupied by a GPT partition table.
Similarly a number of ARMv7 devices support booting from GPT
partitions where the u-boot binary is available in a EEPROM or nand.
Signed-off-by: Peter Robinson <pbrobinson@gmail.com>
> ARM platforms: support both msdos and gpt partitions

- blivet/formats/__init__.py
XFS is the default filesystem type for several of the current linux
distributions. It should be included as a potential default filesystem
type in the constructor list.
Related: rhbz#1242666
> Add xfs to default filesystem types

- blivet/formats/__init__.py
Calls to get_default_filesystem_type check to see if the filesystem is
supported by the installed operating system. The boolean flag that
indicated support was actually returning an instance of the property
object which, when cast to a boolean type, is always True.
Converted to call the actual boolean property and made the error handler
return False instead of None for consistency with the property.
Related: rhbz#1242666
> Fix blivet constructor fs support check

- tests/devices_test/device_methods_test.py
This adds testing of `create`, `destroy`, `setup`, `teardown` methods for `StorageDevice`, `DiskDevice`, `PartitionDevice`, `LVMVolumeGroupDevice`, `LVMLogicalVolumeDevice`, and `MDRaidArrayDevice`. It doesn't increase coverage by much, but it does test some critical logic in the device classes.
> Tests for crucial methods of core device classes.

- blivet/__init__.py
- tests/blivet_test.py
Blivet generates the information about user defined custom partitioning
that is used in the kickstart file. The output was missing the biosboot
and prepboot data rendering the kickstart unusable for automated
installation using the generated file.
Added code and unit tests to add and verify the presence of the
bootloader device in the generated kickstart data.
Resolves: rhbz#1242666
> Kickstart missing bootloader partitions (#1242666)

- po/Makefile
The plural string, "RAID level %(raidLevel)s requires that device have
at least %(minMembers)d member(s)." was not being included for
translation.
This also affects 1.20-devel but I don't know how much you want to care about Fedora string freezes.
> Add the P_ keyword to xgettext.

- blivet/devicetree.py
Internal LVs can have their own internal LVs (e.g. RAIDed thin pool
metadata). We don't add the "top-level" internal LVs to DeviceTree when
iterating over them so let's do the same when their own internal LVs are being
analyzed.
> Do not try to add internal LVs (#1271665)

- blivet/devicetree.py
If udev knows about some VG (or more precisely LVs from such VG), but we don't
see any PVs of that VG, we still need to remember the VG's name because trying
to create a new one with the same name would/could result into a failure as LVM
may know (better) about the VG.
Resolves: rhbz#1245038
> Remember VG name even if it seems to have no PVs

- blivet/actionlist.py
- blivet/autopart.py
- blivet/blivet.py
- blivet/deviceaction.py
- blivet/devicefactory.py
- blivet/devices/partition.py
- blivet/formats/disklabel.py
- blivet/partitioning.py
- blivet/populator/helpers/disklabel.py
- blivet/populator/helpers/partition.py
- blivet/udev.py
- tests/unsupported_disklabel_test.py
This is a total reversal from the "unusable storage" dialog I added last year. The idea here is that blivet should not be constrained by what disklabels parted supports. If there are partitions in the system for it, we should be able to identify them and whatever it built on them. We should also be able to completely clear them so that users can get to a known-good state. Here are the main points of what this patch set does:
- include partitions and their descendants even if parted doesn't support the disklabel
- we cannot support modifying the partition table in this case
- we can, however, use the devices as-is or completely wipe the disk to start over
- make a better effort to find the disk a partition belongs on, regardless of whether `udev`/`blkid` provide expected data
The …
> Improved handling of corrupt or otherwise unsupported disklabels

- blivet/__init__.py
- blivet/deviceaction.py
- blivet/devicefactory.py
- blivet/devices/partition.py
- blivet/devicetree.py
- blivet/formats/disklabel.py
- blivet/partitioning.py
- blivet/udev.py
- tests/storagetestcase.py
- tests/unsupported_disklabel_test.py
Same as #427 except for `rhel7-branch`, which means I had to drag over a few minor things to make it all work the same.
> Improved handling of corrupt or otherwise unsupported disklabels (rhel7)

- blivet/devices/storage.py
- blivet/udev.py
- python-blivet.spec
'pyudev.Device.from_sys_path' and 'pyudev.Device.from_device_file'
are deprecated since pyudev 0.18.
> Do not use deprecated pyudev methods

- blivet/devices/partition.py
On s390x in particular, some partition alignment issue is causing fractional
sizes to be reported. Pykickstart doesn't take anything except int values for
partition info, hence the call to roundToNearest.
This change only affects the data that is written to ks.cfg.
Resolves: rhbz#1257997
> Round down to nearest MiB value when writing ks parittion info. (#1257997)

- tests/formats_test/methods_test.py
This adds unit tests for the `setup`, `teardown`, `create`, `destroy` methods of the most commonly used `DeviceFormat` classes.
> unit tests for critical methods of format classes

- blivet/deviceaction.py
- blivet/formats/fs.py
- tests/action_test.py
This is not a final version, just a "request for comments".
I've decided to use the "single class" approach with a dict of supported ("configurable") attributes and functions used to set the attribute. I didn't have to create a special function for label configuration -- we already have the `write_label` functions so I've just changed it to take the `dry_run` option for the input validation.
Pros:
- It's easy to tell if format supports configuration of an attribute using actions.
- Having only one class makes the API simpler for the users.
- It's possible to use existing validation functions/tasks.
Cons:
- Every attribute needs a special function that looks like a setter but it actually isn't (because of the `dry_run` option).
> Configuration actions

- blivet/platform.py
Signed-off-by: David A. Marlin <dmarlin@redhat.com>
Resolves: rhbz#1349130
> Restore the correct default partition table type for AArch64 EFI.

- blivet/devicetree.py
- tests/devicetree_test.py
People should be able to set `exclusive_disks = ["mpatha"]` (via `ignoredisk --onlyuse=mpatha` in kickstart) without having to list the member disks.
> Fix mpath edge case in disk filtering

- blivet/blivet.py
- blivet/devices/lvm.py
- doc/api/blivet.rst
- tests/devices_test/lvm_test.py
Thin and cache pools can be created from two other LVs (data and metadata). We
don't support creation of standalone cache pools now, but we do support creation
of standalone thin pools and thus we should also support their creation from
other LVs.
A new high-level function added to the API can save us from a lot of headache
caused by people doing crazy things and ending up with inconsistent devicetree.
> Allow creation of a new LV from other LVs

- blivet/devices/lvm.py
- blivet/partitioning.py
- tests/devices_test/lvm_test.py
These fix a few issues with internal LVs, metadata and data part sizes etc. The change in behavior that we no longer include the thin pool's padding into its ``vg_space_used`` for existing thin pools is for the better because that way we can report consistent numbers as LVM for VG's free space.
> Fixes for calculations of space taken from a VG by LVs

- blivet/devices/lvm.py
- tests/devices_test/lvm_test.py
You can't add snapshot to a model when this check is enabled. I don't know why you want this but it looks as a huge drawback to me.
> Don't require existing origin when modeling snapshot

- blivet/iscsi.py
storaged now provides the API compatible with UDisks2.
> Adapt to the old-new storaged API paths

- blivet/populator/populator.py
- blivet/udev.py
I didn't realize we need #450 on 2.x too. I'll remove `device_is_realdisk` from 3.0 after merging this.
> Fix udev.resolve_glob and udev.device_is_disk

- blivet/partitioning.py
When adding fourth partition extended partition is automatically
created. Because the extended partition takes 1 MiB of the free space
we might not have enough free space for the logical partition.
This patch shrinks the logical partition if this problem occurs.
> Fix not enough free space after creating extended partition (#1252350)

- blivet/devicelibs/lvm.py
- blivet/populator/helpers/lvm.py
- python-blivet.spec
Instead of doing multiple calls to libblockdev for every LV to find out what its
potential pool, data and metadata LVs are, we can use the information from the
overall information about LVs libblockdev now provides.
> Use the new way extra information is provided for LVs

- blivet/devices/lvm.py
- blivet/devicetree.py
Set `vgName` in lvmpv format to `None` when removing the vg, so we can remove the pv too.
> Fix removing PVs after removing VG (#1358067)

- blivet/populator/helpers/dmraid.py
The name should come before the uuid.
Note: the referenced bug report is definitely related, but it would be great if this was the only required thing to fixing it
> Pass arguments to get_member_raid_sets() in the correct order (#1225184)

- blivet/callbacks.py
- blivet/populator/populator.py
It's easy for us to advertise how many devices we expect to scan and then report
each device scan completion. The user code can then show scanning progress to
users.
> Add callbacks for populate

- blivet/blivet.py
- blivet/devices/lvm.py
- blivet/devicetree.py
- python-blivet.spec
- tests/action_test.py
- tests/devices_test/lvm_test.py
The first three patches are the same as in the PR #465 and may be ignored here. The next 5 patches tweak the little details we need to make actions for creating LVs from other LVs work. The last patch adds tests for the newly-supported functionality.
> Actions for creating LVs from other LVs

- blivet/devicelibs/dasd.py
This will weed out non-DASD devices and prevent tb's occurring when we
try to check for DASD-specific attrs.
Resolves: rhbz#1353667
> Check a device is a DASD before doing DASD-specific things. (#1353667)

- blivet/__init__.py
- tests/blivet_test.py
Added support to detect the biosboot partition.
The biosboot partition, unlike other bootloaders, is not considered a stage1
device and is not mountable therefore it never actually showed up. Detection
of the biosboot partition required a special case that does not impact the
internal bootloader device properties which would have wreaked havoc
elsewhere in the codebase.
Resolves: rhbz#1242666
> Ensure biosboot shows up in kickstart (#1242666)

- blivet/blivet.py
- blivet/dbus/blivet.py
- blivet/devicefactory.py
- tests/dbus_test.py
- tests/devicefactory_test.py
My intention was to do this in a way that does not break existing callers who are passing type and size as positional args. I expect to follow this up on `3.0-devel` with another pull request to remove that compatibility.
> Default to LVM in the device factory.

- blivet/actionlist.py
- blivet/deviceaction.py
- blivet/devices/md.py
- blivet/devices/partition.py
- blivet/devices/storage.py
When repurposing a partition, partition type UUID is now set correctly (#1258167)
> UUID now set correctly when reformatting partition

- blivet/deviceaction.py
This is fixed in 1.x+ but 0.x still fails while formatting a deactivated logical volume.
> Make sure a logical volume is active before formatting it

- python-blivet.spec
- setup.py
- tests/devicelibs_test/edd_test.py
These are fixes that came out of the fedora package review for the python2-only blivet-1.x compatibility package. They seem applicable to all active branches.
> a few packaging tweaks

- blivet/formats/fs.py
Found this when adding support for relabel using `ActionConfigureFormat` to blivet-gui. Checks (using `write_label` with `dry_run=True`) are done in constructor of the actions, but `self.label` is set in `apply`, so these two checks will always fail in dry run mode.
> Fix checks when changing fslabel using actions

- blivet/blivet.py
API of devicetree.reset() has changed in #469
> Fix TypeError when calling blivet.reset()

- blivet/devices/lvm.py
Default value for mountpoint is always None not an empty string.
> Use None as mountpoint for new snapshots

- blivet/blivet.py
For snapshots, format already exists after creating the snapshot.
> Do not try to create format for snapshots in create_device

- blivet/devices/device.py
- blivet/devices/disk.py
- blivet/devices/lib.py
- blivet/devices/network.py
- doc/api/devices.rst
- tests/devices_test/tags_test.py
- tests/populator_test.py
_I'm trying to sort out what the set of tags should be, so:
1. the set of tags is still in flux
2. the code doesn't currently match what I've written below_
Add a read/write property to `Device` containing a `set` of string tags. The primary use-case is disk selection, where users want to control which disks are used for various purposes. Ultimately, this could be exposed through `pykickstart` to add more powerful disk selection. The initial set of tags, which will be set automatically in the `Device` classes, is:
- local
- rotational
- removable
- remote
- multipath
I had initially included basic device type tags, eg: `lvm`, `iscsi`, but I don't really see a use-case for them. Does anyone have use-cases in mind?
I am undecided on several questions:
1. should every tag have an inverse? …
> Device tags

- blivet/devices/partition.py
- blivet/partitioning.py
- tests/partitioning_test.py
This builds on #485 by doing two things:
1. add a constructor argument to `PartitionDevice` to allow passing tags as disk set specification
2. add handling in `partitioning.allocate_partitions` to resolve the tags to a disk set at partition allocation time
> Disk tags as disk spec for new partitions

- blivet/devices/btrfs.py
- blivet/devices/lvm.py
- blivet/udev.py
This version of "Do not include..." is a bit clumsy in the name of safety. I don't know what the difference is between `self.size` and `self.req_size` at that point, but let's work that out in fedora.
> things almost forgotten

- blivet/iscsi.py
The arguments have to be a single GVariant of type tuple and thus we need to
pass a python tuple as the value for it.
> Make sure we create a proper GVariant tuple as args (#1375712)

- blivet/deviceaction.py
It appears that libparted does not provide any way to clear the `system` attribute of a partition, so don't try to.
> Revert unsupported clearing of parted partition 'system'.

- blivet/deviceaction.py
Also change self.device.disk.original_format instead of
self.device.disk.format. It makes me wonder if there will be cases
where not changing the new/current format will caused problems.
(based on whether or not a new disklabel will be created)
> Move parted changes to after format destroy. (#1378162)

- blivet/populator/helpers/__init__.py
several populators were not imported by populator.helpers, which
means we'd never use them even for devices that should use
them. This should help fix detection of existing firmware RAID
devices...and existing iSCSI devices, existing FCoE devices,
existing DASD devices, existing ZFCP devices, and existing
multipath filesystems...
368a4db6141c7fdcb31ed45fe6be207ccc08ad30 added MultipathFormatPopulator to multipath.py but did not add an import to __init__.py , and 832fe67f6e8d0cb1a38e84b86410fcf15d42a92d added all the subclasses of DiskDevicePopulator but did not add imports for them.
> add missing populators to populator.helpers

- blivet/blivet.py
- blivet/devicefactory.py
- tests/devicefactory_test.py
See the commit message for 72170b1f for the point. My thinking before I started was that this would be significant usability improvement for `DeviceFactory`.
Since it breaks the API (`Blivet.factory_device`, `devicefactory.get_device_factory`, and `DeviceFactory`) it has to go onto 3.0-devel.
> DeviceFactory constructor argument cleanup

- blivet/devices/device.py
- blivet/devices/storage.py
- tests/devices_test/device_names_test.py
Device name check moved from Device to StorageDevice. Now is the name checked only when
device does not exist.
Added tests to check this behavior.
> Device name now checked only for new devices

- blivet/iscsi.py
List comprehensions make the world a better place. At this point
the method is so trivial we could probably ditch it entirely,
but meh.
> Use a list comprehension for _to_node_infos

- blivet/formats/lvmpv.py
These should not be needed now that both blivet and lvm have improved
handling around stale metadata. The pvcreate and wipefs calls should
trigger (asynchronous, udev-initiated) pvscan jobs as needed.
> Remove some obsolete pvscan calls.

- blivet/osinstall.py
- blivet/populator/populator.py
The most important one is definitely the one in `_find_existing_installations`, since it can trigger full setup and recursive teardown for each lv in vgs with an md pv.
The only one of these that I think may not be completely redundant is the one at the end of `PopulatorMixin.populate`, since anaconda runs that method directly (as opposed to using `Blivet.reset`) after adding network storage through the GUI. For that one, we could either leave it as-is or we could add an explicit `teardown_all` in anaconda after the `populate` call.
> Remove several redundant recursive teardown calls.

- blivet/devices/disk.py
- blivet/iscsi.py
These commits fix a couple of problems in iSCSI support. The first is simple: the type of the `port` arg doesn't match the type string (`q` is an int). The second is more complicated; when we moved from libiscsi to storaged the `node` objects were changed from libiscsi `PyIscsiNode` instances to a new namedtuple class called `NodeInfo`...but as a consequence of that, they no longer provide any access to the usernames and passwords used to authenticate to the target, which both  blivet and anaconda actually expect. This restores that information in a different form (it just gets stuffed into the `NodeInfo` tuple) and adapts blivet to the change; I'll send a corresponding PR for anaconda.
> Fix iscsi problems: type of arg passed to storaged, store auth info when logging in with it

- blivet/events/handler.py
- blivet/populator/helpers/disklabel.py
- blivet/populator/populator.py
- blivet/static_data/__init__.py
- blivet/static_data/mpath_info.py
- tests/populator_test.py
With the new function provided by libblockdev we can easily get the list of
multipath member devices once and then query it instead of querying every device
whether it is an mpath member or not.
Note: This is an enhancement so it's targeting the _2.1-devel_ branch.
> Cache and reuse data about multipath members

- blivet/iscsi.py
The iSCSI class has an `initiator_set` property whose meaning
feels a bit slippery these days. It has always been set to
True in `__init__()` if iBFT is active, right after we get the
initiator name from the firmware. Prior to 9280eff7, it was
also set true by `startup()` after it wrote out INITIATOR_FILE.
In 9280eff7, that was removed, without any kind of replacement.
Now `initiator_set` will never be True unless iBFT is being
used.
This is a problem because `iscsi.write()` checks if it's True,
and immediately bails if it isn't. The result of this is that
when you do an iSCSI install with anaconda, the contents of
`/var/lib/iscsi` from the installer environment are no longer
copied in the installed system.
I wasn't entirely sure how to fix this, but this seems like the
simplest way, at …
> iSCSI: set `iscsi.initiator_set` when setting initiator

- blivet/static_data/lvm_info.py
Otherwise if the symlink is used to search for the PV info, it's not found and
everything on that PV is ignored which leads e.g. to issues when removing the PV
(as described in the bug) and others.
> Add device symlinks to the PVs dictionary for MD RAID PVs (#1389130)

- blivet/populator/helpers/boot.py
- tests/populator_test.py
368a4db6 lost a crucial condition in the detection of 'macefi'
partitions in the transition to the 'populator helper' design.
Previously we checked that the parted partition 'name' (which
is a GPT property, for GPT partitions) matched the expected
value according to the macefi format, which basically means we
will only detect partitions created by a previous anaconda run
as 'macefi' (because that name is a very specific one which is
only created by anaconda in the first place).
In the transition, that condition was lost, and now we treat
any device with an HFS+ filesystem that's over 50MiB in size
as a 'macefi' device, which means we mount it at /boot/efi and
try to write all kinds of stuff to it. Not surprisingly, this
borks the install. Fortunately, HFS+ filesystems are mounted …
> Fix detection of 'macefi' partitions (#1393846)

- Makefile
- python-blivet.spec
We no longer require all the python2 packages, python3-kickstart is a hard
requirement now, cryptsetup is no longer used by blivet directly and we need the
anaconda-core stuff for pylint. Plus we need the zanata client to pull
translations and run the canary tests on them.
The file system utilities should all be just test dependencies because blivet
itself works without any of them.
> Fix the test dependencies

- blivet/formats/disklabel.py
Several blivet classes use custom __deepcopy__ methods to avoid
deep copying some parted objects which we know can't be deep
copied. Unfortunately the list of attributes excepted from deep
copying for `DiskLabel` was missing one parted Alignment object,
and with Python 3.6, we blow up trying to deepcopy that. This
fixes the problem by adding that attribute to the list of ones
we know have to be shallow copied.
> Shallow copy another alignment property (#1408282)

- blivet/formats/fs.py
During running the test suite I found that while `MKNTFS_APP` is available, the tests for NTFS are skipped because it's not marked to be formattable.
> formats/fs: Set NTFS to be formattable

- blivet/populator/helpers/disk.py
- blivet/populator/helpers/loop.py
- blivet/udev.py
- tests/populator_test.py
Populator now skips all detached loop devices (i.e. without backing file)
> Loop devices w/o backing file are now ignored

- blivet/formats/luks.py
- tests/formats_test/luks_test.py
As has been suggested and approved in the Fedora 26 change
https://fedoraproject.org//wiki/Changes/EnableTrimOnDmCrypt,
crypttab entries for newly created LUKS devices/formats should
use the 'discard' option by default.
> Add 'discard' option to crypttab for newly created LUKS

- blivet/util.py
Resolves: rhbz#1322439
Mountpoints in `/proc/mounts` are listed with resolved/eliminated symlinks.
> Eliminate mountpoint symlinks when looking for mounted device

- blivet/flags.py
- blivet/formats/luks.py
- blivet/osinstall.py
- tests/formats_test/luks_test.py
Instead of the old non-specific 'installer_mode' flag we no
longer have on 3.0-devel and master.
> Introduce the discard_new flag and use it

- blivet/devicetree.py
For some BIOS RAIDs the hierarchy of devices looks like
[sdb, sdc] -> imsm0 -> md126 (= Volume0_0) so when adding Volume0_0
to exclusiveDisks we need to check for all ancestors, not only
parents, to add the disks to exclusiveDisks.
Resolves: rhbz#1327463
Submitted-by: Masahiro Matsuya <mmatsuya@redhat.com>
> Use all ancestors when adding RAID disks to exclusiveDisks

- blivet/iscsi.py
If udisks (storaged) is not installed at all, we may get an error
even when trying to find out if udisks (storaged) provides the
iSCSI functionality via its Manager object.
Resolves: rhbz#1429132
> Be more careful when checking for udisks-iscsi availability

- blivet/platform.py
- python-blivet.spec
There can be created up to three partitions on FBA DASD with the msdos
disk label type instead of only one, so we should prefer that.
Also the method requiredDiskLabelType can be removed, because it is not
needed anymore.
This pull request is based on https://github.com/rhinstaller/blivet/pull/546 and requires a new version of libblockdev 
https://github.com/rhinstaller/libblockdev/pull/170.
> FBA DASD should use the msdos disk label type

- blivet/devicelibs/dasd.py
- blivet/platform.py
There can be created up to three partitions on FBA DASD with the msdos
disk label type instead of only one, so we should prefer that.
Resolves: rhbz#1214407
> FBA DASD should use the msdos disk label type (#1214407)

- tests/formats_test/luks_test.py
- tests/populator_test.py
Apparently pointing blivet's tests at an uncompiled anaconda git clone is not the same as having the anaconda-core package installed -- go figure.
> Fix root-only unit tests on 2.1-devel

- tests/formats_test/selinux_test.py
This is the only fix needed to be able to run unit tests as root on `3.0-devel` and `master`.
> Fix unit tests that only run as root

- blivet/devicelibs/edd.py
Since the regexp matches the device type as well as the identifying
numbers, we need to pull the numbers from match groups 2 and 3, not 1
and 2.
Resolves: rhbz#1394026
Signed-off-by: Peter Jones <pjones@redhat.com>
--------
This is https://github.com/rhinstaller/blivet/pull/524 for `2.1-devel`. We already have this as a downstream patch in dist-git.
> Fix "unknown" SAS device sysfs parsing.

- blivet/iscsi.py
- blivet/tasks/availability.py
- blivet/util.py
It is the same except that it doesn't raise an exception if the
executable is not found. Which we, however, don't need.
> Use distutils.spawn.find_executable instead of our custom code

- blivet/devices/disk.py
- blivet/populator/helpers/disk.py
- blivet/populator/helpers/dmraid.py
- blivet/populator/helpers/multipath.py
- blivet/udev.py
- doc/api/devices.rst
- tests/populator_test.py
One tricky bit is that I'm removing the `serial` constructor argument to `MultipathDevice`, which has until now been used as a stand-in for WWN. The `MultipathDevice` constructor is not listed as part of the public API, so I think this should be okay.
It's too bad that `DMRaidArrayDevice` and `MultipathDevice` do not derive from `DiskDevice` -- it would have made this (and #485) much simpler.
> Add a WWN attribute to disk-like device classes.

- blivet/devices/md.py
- blivet/devices/partition.py
- blivet/devices/storage.py
- blivet/devicetree.py
This is a backport from master and has been verified to resolve the referenced bug. I don't see any risk, given that the behavior has not caused problems in recent fedora and the reporter verified the fix.
> Update md boot metadata version selection.

- blivet/udev.py
Return md name if it matches a device name for the given device
specification, so the device names are consistent when we work
with udev module and a devicetree.
Resolves: rhbz#1445723
> Fix resolve_devspec to fully support raid devices (#1445723)

- blivet/populator/helpers/partition.py
udev.device_get_partition_disk() returns the device name as given
by device_get_name() not sys_name. So when trying to find a match
we need to compare it to the same value for devices we iterate
over.
Also don't call resolve_devspec() on the returned value,
udev.device_get_partition_disk() is already doing it.
Resolves: rhbz#1445302
> Look the disk up for a partition by name not sys_name

- blivet/partitioning.py
When setting thin pool's size based on the sum of its thin LVs we
need respect its minimum size. That can for example be its actual
size if it already exists.
Together with the recent changes for thin pool padding this
Resolves: rhbz#1435180
> Respect thin pool's min size when setting its req_size

- blivet/formats/fs.py
The uuid module is shipped together with Python so we should use
it instead of requiring an extra utility.
note: This requires a *rhbz#* reference to be added.
> Use the uuid module instead of the uuidgen tool

- blivet/devices/md.py
- scripts/merge-pr
- setup.py
- tests/devices_test/md_test.py
#580 for 2.1-devel
This also includes the original chunks size support commit, because it isn't (for some unknown reason) part of this branch -- it is on "newer" branches (2.2-devel, 3.0-devel and master) and also on the 2.1-release branch (that's why no one noticed) but not here.
> Add RAID chunk size to the generated kickstart file

- blivet/partitioning.py
In installer mode do not try to remove empty extended partitions
created by blivet-gui. We should remove the extended partition
only if the PartitionDevice doesn't exist or if we previously
deleted all the logical partitions.
> Do not remove manually created extended partitions (#1440150)

- blivet/autopart.py
Otherwise all Blivet log messages in the Anaconda log messages
would have the "misc" prefix.
With "anaconda.blivet.autopart" the prefix will be "blivet.autopart".
> Use structured logging for the anaconda logger

- blivet/formats/fs.py
This is needed when the file system is not clean (e.g. if it was
created as a snapshot of some other mounted file system) which is
quite a common case. And since 'xfs_admin' exits with code 0 even
when it fails to set the UUID [1], we cannot do a second/fallback
try. The first one has to have the best chance to succeed, hence
this patch.
[1] https://bugzilla.redhat.com/show_bug.cgi?id=1450423
> Always mount & unmount an XFS file system when writing new UUID

- blivet/blivet.py
- blivet/devicefactory.py
- blivet/devices/btrfs.py
- blivet/devices/container.py
- blivet/devices/lvm.py
- blivet/devices/md.py
- blivet/formats/fs.py
- blivet/formats/swap.py
- blivet/platform.py
- blivet/size.py
- blivet/util.py
- tests/devicelibs_test/edd_test.py
- tests/devices_test/device_methods_test.py
- tests/parentlist_test.py
- tests/populator_test.py
- tests/pylint/runpylint.py
We now have new pylint in Fedora and it has a lot of new awesome warnings and errors.
Test will still fail on this because pylint started writing the score to stdout and pocketlint thinks it is an error. https://github.com/rhinstaller/pocketlint/pull/16 should fix this
> Various pylint fixes

- blivet/devicelibs/disk.py
- tests/dbus_test.py
This code is only on `2.2-devel` so these errors/warnings were not fixed by #593
> pylint: ignore some pylint warnings in tests

- blivet/osinstall.py
This together with #591 and #594 should fix all pylint warnings on 3.0-devel/master.
> pylint: disable pylint warning for InstallerStorage.get_free_space

- blivet/partitioning.py
"installer_mode" flag no longer exists on 3.0-devel.
-----
I didn't notice this when merging 2.2-devel to 3.0-devel. Oops.
> Use "flags.keep_empty_ext_partitions" instead of "installer_mode"

- blivet/udev.py
- tests/populator_test.py
Fix of excessive deprecation warnings in the logs.
Due to nature of deprecation warnings origin (e.g. __getitem__ or
__iter__ methods) it was almost impossible to find and fix all of its
sources. Instead the Device class was substituted with its 'properties'
attribute which directly fixes the problem.
Couple of other minor changes was neccessary, though.
> Updated calls to avoid log spamming

- blivet/__init__.py
The anaconda_log module has been renamed to anaconda_logging,
so change the name of the imported module accordingly.
> Adapt to logging module name change

- blivet/devicefactory.py
These are a few improvements and fixes for the generic ``DeviceFactory`` and ``LVMFactory`` classes. The commits are intentionally small and isolated so that it's easy to reject/skip or later revert any of them.
> (LVM)Factory cleanups

- blivet/osinstall.py
The anaconda_log module has been renamed to anaconda_logging
in Anaconda 27.10-1.
> Adapt to anaconda_log rename

- blivet/devices/lvm.py
Before and LV is removed, we may need to set its ancestors (VG
and its PVs) up which may trigger auto-activation of the LV
itself. And since we are supposed to always remove a deactivated
LV so we have to make sure the LV is deactivated before we try to
remove it.
Resolves: rhbz#1456821
> Make sure an LV is deactivated before removal

- blivet/devices/lvm.py
Otherwise LVM does it when creating the thin pool and we may end
up with not enough space in the VG to create the data part of the
pool (which happens afterwards).
Resolves: rhbz#1456528
> Round the recommended thpool metadata size to extents

- blivet/devices/lvm.py
- blivet/partitioning.py
These two have been merged to the *rhel7-branch* recently and we need them on *2.1-devel* and above too.
> Ports of thin provisioning related fixes on rhel7-branch

- Makefile
- python-blivet.spec
Allow building blivet with Python 2 and add a Python 2 subpackage.
-----
I've tested this in Copr (build [here](https://copr.fedorainfracloud.org/coprs/vtrefny/test2/build/562282/)) and on my CentOS machine. Few notes:
- CentOS has `pyudev` 0.15 and we require >= 0.18, I've changed this only for the copr build.
- Translation canary doesn't work with Python 2
- `python2-pocketlint` is not ready yet, Ie created a [copr repo with it](https://copr.fedorainfracloud.org/coprs/vtrefny/pocketlint/)
- Version for _Conflicts_ and _Obsoletes_ for the `blivet-data` package needs to be adjusted on the release branch.
> Adjust Makefile and spec file for Python 2 compatibility

- blivet/storage_log.py
Some informal measurements on my workstation showed between 15-20% speedup in running `blivet/examples/list_devices.py` with this patch.
> Only run log_method_call when flags.debug is set.

- blivet/formats/fs.py
- blivet/tasks/fsck.py
The '-p' option means "Automatically repair ("preen") the file system.  This
option will cause e2fsck to automatically fix any filesystem problems that can
be safely fixed without human intervention." which is something we really
shouldn't do as part of reset()/populate(). We should use '-n' instead "Open the
filesystem read-only, and assume an answer of `no' to all questions." which
guaranties no changes to be made on the file system.
We might want to add the '-p' functionality back at some point, but it needs to
be explicitly triggered by the user code (e.g. Anaconda). I think we need to add
a 'clean' property and a 'repair' method to the formats.FS class so that users
can see where the problem is (if any) and explicitly trigger a safe fixup
attempt if they want to.
Related: …
> Change how we run e2fsck to check ext filesystems

- blivet/devices/lvm.py
- blivet/partitioning.py
These two are needed for ``logvol ... --thinpool --percent ...`` combination to work in kickstarts. IOW, percent-based thin pools.
> Percent-based thpool fixes

- blivet/partitioning.py
- tests/partitioning_test.py
Today I learned that the partition count limits in pyparted are in fact massively outdated (rhinstaller/pyparted#41). These days major/minor numbers are dynamically allocated so there is no limit except for space. There is a notable exception in mmcblk, which has a kernel config value for the number of minors per major. It defaults to 8. Good grief.
> Stop enforcing obsolete limits on partition count. (#1460668)

- CONTRIBUTING
- python-blivet.spec
- setup.py
blivet has been moved under the storaged-project organization at
GitHub.
Also update the URL of the project pages.
> Update the upstream git URL

- tests/platform_test.py
These will come in handy when moving this code from `platform` to `DiskLabel` in preparation for moving the rest of `platform` into anaconda.
> Add tests for disklabel type selection and partition weight.

- blivet/tasks/availability.py
- python-blivet.spec
- tests/pylint/runpylint.py
Just run the tool with "--version" (or similar) option to get its
version. Querying RPM database to get version of installed package
makes blivet impossible to use on other distributions than Fedora.
> Do not use package version to check version of installed tools

- blivet/mounts.py
- python-blivet.spec
- tests/storagetestcase.py
This reverts commit dc5da7db13e01aa9406e494ecf31247a2e7ed9de.
-----
We need Python 2 compatibility and libmount unfortunately doesn't have Python 2 bindings. Reverting to the "old" implementation from `2.1-devel` is probably the best solution for now.
> Revert "Use libmount for MountsCache"

- tests/formats_test/selinux_test.py
SELinux tests no longer fail when SeLinux is disabled.
Instead they are skipped.
> Skip tests when SELinux is disabled

- tests/formats_test/selinux_test.py
Rather than skiping the test, parts of it that need selinux were mocked
> No longer skip test w/o selinux; mocked

- tests/clearpart_test.py
- tests/devicelibs_test/edd_test.py
- tests/devices_test/dependencies_test.py
- tests/devices_test/device_properties_test.py
- tests/devicetree_test.py
- tests/formats_test/fs_test.py
- tests/formats_test/luks_test.py
- tests/formats_test/selinux_test.py
- tests/imagebackedtestcase.py
- tests/populator_test.py
- tests/size_test.py
- tests/storagetestcase.py
In some cases when a test crashes, the tearDown method is not
executed, using addCleanup method fixes this.
> Use addCleanup for test cleanup instead of clening in tearDown

- tests/devicelibs_test/edd_test.py
Since this doesn't make any sense on non-x86 machines anyway, and
apparently I've got some endian bugs in it (which don't really
matter...), just don't run the edd tests on non-x86.
Signed-off-by: Peter Jones <pjones@redhat.com>
------------
#276 rebased to 2.1-devel
> edd_test: don't run on non-x86

- python-blivet.spec
Listing python3-pocketlint as a BuildRequires is
redundant as it is used during the rpm build.
-------
#269 rebased to 2.1-devel
> Remove build requires for pocketlint

- Makefile
- install-test-dependencies.yml
List of dependencies moved from Makefile to a ansible playbook.
"install-requires" target now uses Ansible to install dependencies
instead of yum/dnf.
------
Moving list of dependencies to a playbook also allows it to be somewhat distribution independent and makes it easier to maintain lists of packages with different names for different distributions.
I've also decided to remove the "check-requires" target -- it isn't possible to check if a package is installed with Ansible (it is possible to run "install-requires" instead, it will skip packages that are already installed, but it needs root privilegies). I think we can simply assume that user will run "install-requires" before running the tests and we don't need to check for every run.
> Use Ansible playbook to install test dependencies

- tests/populator_test.py
"osinstall.storage_initialize" expects "osinstall.InstallerStorage"
not "blivet.Blivet".
> Use InstallerStorage in setupDiskImagesNonZeroSizeTestCase

- blivet/formats/fs.py
Fixed confirmation hang when ext[234] partition was created on the whole
disk.
Resolves: rhbz#1461459
> mkfs.ext4 no longer hangs on confirmation

- tests/size_test.py
LANG variable is sometimes not set in our testing environment so
we need to set some reasonable default value to make the cleanup
work.
> Add some reasonable default value for LANG variable in size_test

- blivet/__init__.py
- blivet/tasks/availability.py
By default libblockdev will fail to load a plugin during its
initialization if one (or more) of the plugin runtime dependencies
is missing. For example if the "swaplabel" utility is missing,
loading of the swap module will fail.
This commit disables dependency checks during init -- in the same
situation swap plugin will load and only calling "swap_set_label"
would fail (because the utility it uses is missing).
Specification of all required "technologies" and "modes" is added
to the "tasks" module so checking for external tools availability
still checks if libblockdev supports everything we need.
> Use libblockdev runtime dependency checks

- blivet/__init__.py
- blivet/devicefactory.py
- blivet/devicelibs/lvm.py
- blivet/devices/btrfs.py
- blivet/devices/disk.py
- blivet/devices/dm.py
- blivet/devices/loop.py
- blivet/devices/lvm.py
- blivet/devices/md.py
- blivet/devices/partition.py
- blivet/devicetree.py
- blivet/formats/__init__.py
- blivet/formats/luks.py
- blivet/formats/lvmpv.py
- blivet/formats/mdraid.py
- blivet/formats/swap.py
- blivet/osinstall.py
- blivet/partitioning.py
- blivet/populator.py
- blivet/tasks/availability.py
- blivet/util.py
- blivet/zfcp.py
- tests/devices_test/device_properties_test.py
- tests/devices_test/partition_test.py
- tests/partitioning_test.py
python2-blivet1 has fallen into disrepair on Fedora since at least F25 due to various changes to dependencies. This should resolve everything. It was tested manually on F27.
> 1.20 fedora updates

- blivet/devicelibs/lvm.py
- blivet/devices/md.py
Multiple subsequent installations with the same layout (lvm-on-raid1) with lazy cleanup in between can lead to a situation in which stale lvm metadata is found by udev/lvmetad/pvscan immediately after creation of a new md array. The same udev/lvmetad/pvscan machinery activates this lvm, which trips blivet since it is unaware of the newly-activated devices.
There will also be a version of this for newer branches once the fix is confirmed by reporters.
> Remove stale lvm metadata found on new md arrays.

- blivet/devices/md.py
Apparently you get `KeyError` instead of `blivet.errors.LVMError` when the new md array doesn't have lvm metadata on it.
> Followup for #651

- blivet/devices/device.py
- blivet/devices/storage.py
- tests/devices_test.py
Name validity is ommitted for existing devices
Changes backported from commit a950e95
Resolves: rhbz#1325697
> Name validity check fix

- blivet/devices/lvm.py
- blivet/partitioning.py
Growable non-autopart (kickstart) thin pools don't get vg space for pmspare/mlog volumes. I have verified the fix after reproducing the original issue.
> Account for pmspare/mlog volumes after growing a thin pool.

- blivet/formats/disklabel.py
- tests/formats_test/disklabel_test.py
Add the dasd label type to the list of valid label types for s390x.
This bug was introduced in the commit ebd43b6.
Resolves: rhbz#1538550
> Dasd is a valid label type on s390x (#1538550)

- blivet/udev.py
The idea is to add an alternative way to get a `pyudev.Device` without breaking the API.
> Add option to get udev device by device node path

- blivet/populator/helpers/disk.py
MDBiosRaidArrayDevice's parent class doesn't take a 'wwn' kwarg,
so the populator for it shouldn't pass one.
For more details, see comment 15 on the bug.
Resolves: rhbz#1557957
Signed-off-by: Adam Williamson <awilliam@redhat.com>
> Don't use a 'wwn' kwarg for MDBiosRaidArrayDevice (#1557957)

- blivet/blivet.py
- tests/clearpart_test.py
The exception caused by using anaconda kickstart with zerombr and --only-use read-only disk
now produces a warning
Added tests for this behavior
> Fixed KS forcing zerombr onto RO disk

- blivet/__init__.py
- blivet/devices/__init__.py
- blivet/devices/disk.py
- blivet/devices/lib.py
- blivet/populator/helpers/__init__.py
- blivet/populator/helpers/disk.py
- blivet/static_data/__init__.py
- blivet/static_data/nvdimm.py
- blivet/udev.py
- tests/populator_test.py
Basic support for nvdimm devices:
- `NVDIMMNamespaceDevice` -- new "disk type" for NVDIMM namespaces that are recognized by udev as disks -- namespaces in *sector*, *memory* or *raw* mode
```
NVDIMMNamespaceDevice instance (0x7fc4646340b8) --
name = pmem0s  status = True  id = 268
children = []
parents = []
uuid = 5c75b9c7-a74d-43c7-b260-c5b00415015f  size = 1015.91 MiB
format = existing gpt disklabel
major = 0  minor = 0  exists = True  protected = False
sysfs path = /sys/devices/platform/e820_pmem/ndbus0/region0/btt0.0/block/pmem0s
target size = 1015.91 MiB  path = /dev/pmem0s
format args = []  original_format = disklabel  removable = False  wwn = None  mode = sector  devname = namespace0.0  sector size = 512
```
- `NVDIMM` singleton for managing NVDIMM devices
- we need to be able to …
> NVDIMM support

- po/Makefile
- python-blivet.spec
It is not needed during build. This was already removed on
2.1-devel but not completely removed on 3.0-devel.
----
We had the dependency multiple times on 3.0-devel and I didn't notice that when merging #633
> Remove dependency on pocketlint

- blivet/devices/md.py
- tests/devices_test/device_methods_test.py
This is a port of #651 to active development branches.
> Find and remove stale LVM metadata immediately after creating md array.

- blivet/devices/md.py
Sometimes after running 'mdadm --stop' it takes some time before
the device in /dev disappears. udev settle should fix this.
Resolves: rhbz#1563631
----
This happens when we try to remove an mdraid array in Anaconda. We first need to wipe filesystem from the array -- so we need to start it, run wipefs and stop it after that. Second step is to remove the array itself -- the code checks if the `/dev/mdXXX` exists and if it exists we try to stop it first. The problem is that it takes some time before the device file disappears after the first stop and sometimes it disappears after we run the check in blivet but before libblockdev tries to stop it again, so the `blockdev.md.deactivate(self.path)` call fails. Running `udev.settle()` should prevent this.
> Try to wait after stopping an MD array

- blivet/devices/disk.py
The supported option is rd.iscsi.firmware
Resolves: rhbz#1566133
> Replace deprecated iscsi_firmware dracut option

- blivet/__init__.py
Libblockdev uses syslog log levels for logging and these are not
the same as python logging levels so we need to "translate"
these.
Also ignore debug logs from libblockdev and don't save these
to program.log.
> Translate log levels from libblockdev to python log levels

- python-blivet.spec
- tests/devices_test/dependencies_test.py
- libblockdev plugins now use only weak dependencies
- added libblockdev plugins dependency tests to verify that:
- destroy|create|resize_device fails (properly) w/o necessary plugin
- no BlockDevNotImplementedError is raised in case of missing plugin
(due to confusing nature of this exception - it does not inform
about a missing dependency)
> Weak dependencies for libblockdev plugins

- blivet/blivet.py
- blivet/deviceaction.py
- tests/devices_test/dependencies_test.py
- when `create_device` raises an exception during the format creation, previously
created device is now cleaned from the devicetree; the exception is then reraised
- this prevents having the device with the same name already in the devicetree
when retrying the `create_device` command
- changed dependency related exception in `DeviceAction.__init__` from `ValueError`
to `DependencyError` and updated the rest of code and the tests accordingly
> Fixed create_device fail behavior

- blivet/formats/luks.py
If the cipher is specified, then the key size is None by default
and liblockdev fails to create the format, because it expects 0 by
default. Because of that, Anaconda fails to do the partitioning
if the kickstart option --cipher is specified.
> The key size of LUKS should be 0 by default

- blivet/tasks/availability.py
- tests/devices_test/dependencies_test.py
These changes fix the partitioning test error and allow running (most of) these tests as non-root.
This is an alternative to #691.
> Fixups for missing dependency tests.

- blivet/populator/helpers/dmraid.py
- blivet/populator/helpers/multipath.py
- blivet/udev.py
- tests/populator_test.py
Also strip off the '0x' prefix, which just takes up space.
> Use ID_WWN_WITH_EXTENSION for WWNs.

- blivet/__init__.py
- blivet/nvdimm.py
- blivet/udev.py
- python-blivet.spec
This basically ignores nvdimm devices on systems without libblockdev-nvdimm . In installer mode, all `pmem` devices will be ignored, outside of installer existing NVDIMM namespaces in sector mode will be treated as normal disks.
> Remove NVDIMM support on non-x86_64

- blivet/devices/lvm.py
These are still "valid" existing internal RAID LVs just not synced
yet.
We are using internal lvs to calculate `free_space` property of vgs. If we ignore these we will report wrong free space, see https://github.com/storaged-project/blivet-gui/issues/107
There is also an issue in lvmdbus (https://bugzilla.redhat.com/show_bug.cgi?id=1608930) -- it doesn't update the Attr property of the LVs so we ignore all internal lvs for raid LVs (because the type is never changed from *(I)mage out-of-sync* to *(i)mage, mirror or raid*).
> Do not ignore "Image out-of-sync" internal LVs

- blivet/blivet.py
- blivet/devicefactory.py
- blivet/devices/lvm.py
- setup.py
- tests/pylint/runpylint.py
- now marked as pylint false positive: non-existing 'id' attribute of ObjectID and its children
- fixed ksdata variable reappearance caused by merging
> Fixed various issues preventing successful build

- blivet/devicefactory.py
- blivet/devicelibs/crypto.py
- blivet/devices/__init__.py
- blivet/devices/dm.py
- blivet/devices/luks.py
- blivet/formats/luks.py
- blivet/populator/helpers/__init__.py
- blivet/populator/helpers/dm.py
- blivet/populator/helpers/luks.py
- blivet/static_data/luks_data.py
- blivet/tasks/availability.py
- blivet/tasks/lukstasks.py
- blivet/udev.py
- blivet/util.py
- python-blivet.spec
- tests/populator_test.py
This is first part of luks2 support for blivet. These changes solve problem with luks2+integrity -- blivet currently expects that the luks device is child of the partition with luks format and this is not true with integrity devices.
> LUKS2 support

- blivet/devices/disk.py
- blivet/tasks/availability.py
Libblockdev can now be build without dmraid support so we need
a separate check for dmraid and 'other' dm devices support.
Resolves: rhbz#1617958
> Create a separate availability check for dmraid support

- blivet/tasks/availability.py
- tests/devices_test/dependencies_test.py
Pylint thinks that 'get_available_plugin_names' has a "self"
paramter (it doesn't).
> Ignore pylint 'no-value-for-parameter' warning

- blivet/formats/__init__.py
This resolves #673 without too much complexity.  Anaconda has a few additional concerns so this is largely based on `get_default_filesystem_type`.
> Add toplevel tuple of fstypes supported by kernel

- blivet/formats/lvmpv.py
- tests/formats_test/methods_test.py
While reinstall a crypt fs, it occasionally failed
[snip]
|gi.overrides.BlockDev.LVMError: Process reported exit code 5:
WARNING: atari signature detected on /dev/mapper/luks-0e5f891c
-7701-48bc-a41e-8d626b6ef953 at offset 466. Wipe it? [y/n]:
[snip]
Add `-y' to lvm.pvcreate
Signed-off-by: Hongxu Jia <hongxu.jia@windriver.com>
> add `-y' to lvm.pvcreate

- blivet/deviceaction.py
- tests/devices_test/dependencies_test.py
Btrfs volumes are removed using wipefs so we don't need to check
for device dependencies availability when removing the volume
(btrfs support depends on libblockdev btrfs plugin).
Resolves: rhbz#1605213
----
Fixing this in `DeviceAction` is definitely not ideal, but I don't think there is a better way -- this would require a quite radical rewrite of the availability code to be able to define different dependencies for adding, removing and modifying devices. And right now this problem exists only for Btrfs devices.
> Allow removing btrfs volumes without btrfs support

- blivet/devices/lvm.py
We need to use the lvmpv format to check if PV is active, not the
status of the underlying partition.
(This was originally part #721, we've decided to fix the original problem in Anaconda, but this is a different problem found during debugging.)
> Use format.status when checking for PV status

- blivet/iscsi.py
Correct mutual authentication options in UDisks are
"reverse-username" and "reverse-password".
> Fix options for ISCSI functions (#1632656)

- blivet/devicefactory.py
Reuse the message of the original exception when you call raise_from.
Otherwise, the string representation of the new exception is an empty
string.
Related: rhbz#1490174
> Don't raise errors without messages

- blivet/blivet.py
- blivet/flags.py
- blivet/populator/populator.py
- tests/imagebackedtestcase.py
The flags `automated_install`, `live_install` and `image_install` can be
removed, because they are not used or not useful anymore.
Depends on: https://github.com/rhinstaller/anaconda/pull/1613
> Remove Anaconda flags

- blivet/devices/file.py
- blivet/devices/nfs.py
- blivet/devices/nodev.py
- blivet/formats/fs.py
- tests/formats_test/selinux_test.py
This removes a bunch of unnecessary error messages from the logs by avoiding operations that are expected to fail.
> minor cleanups to reduce log noise

- blivet/devicelibs/btrfs.py
- blivet/devices/btrfs.py
This allows name validation without constructing the BtrfsDevice
object. There is a similar function in devicelibs.lvm.
> Move btrfs name validation to devicelibs

- blivet/udev.py
- tests/populator_test.py
There is no easier way how to check if disk is an nvdimm
namespace so without nvdimm plugin udev.device_is_nvdimm_namespace
will return False and the device will be added as a normal disk.
> Fix crash on reset on systems without nvdimm plugin

- blivet/populator/helpers/partition.py
- blivet/udev.py
- tests/populator_test.py
This fixes DeviceTreeError when adding LUKS device on a partition
on a raid -- the partition is added as "name1" so we can't use
the name from udev ("md127p1") here.
> Use raid names when looking for slave devices

- blivet/devices/lvm.py
This was not adjusted to libblockdev API when cherry-picking fixes
from rhel7-branch in 3c8f8dbf78b0a093e120f69241b44a48ff07be30
> Fix reading LV attributes in LVMVolumeGroupDevice.status

- blivet/iscsi.py
The initiatorname.iscsi file is used (sometimes) during boot so
we need to write the configuration to the installed system.
Resolves: rhbz#1664587
----
We do this on rhel7-branch, the code that saves the `initiatorname.iscsi` file was probably accidentally removed in https://github.com/storaged-project/blivet/commit/9280eff7016da0e58b8a58c1c844470e8fddeb55.
This was not  discovered because dracut should prefer the `rd.iscsi` boot option but this currently also broken -- https://github.com/dracutdevs/dracut/pull/518 -- and it tries to use the config file that has wrong (some random default) initiator name.
> Copy the iSCSI initiator name file to the installed system

- blivet/populator/helpers/dmraid.py
We don't want to crash during reset on systems with incomplete or
unsupported firmware RAIDs.
> Do not crash if DM RAID activation fails (#1661712)

- blivet/devicefactory.py
For encrypted thin LVs 'device' is the LUKSDevice which doesn't
have the thinpool instance reference, so we need to use the
'raw_device' for it. For non-encrypted factories 'raw_device'
points directly to the 'device'.
> Use raw_device to get thinpool device in LVMThinPFactory (#1490174)

- blivet/static_data/lvm_info.py
Currently the internal cache variables are defined in the
drop_cache which means the cache won't work without calling
drop_cache first, because the variable is not defined.
Discovered when working on #753
> Fix undefined attribute in LVM info cache

- blivet/blivet.py
- blivet/flags.py
Remove the unused `gpt` flag. It is not used by Blivet
or Anaconda.
Remove the unused `sysroot` property. The property is
not used in Blivet or Anaconda.
Remove unused attributes from the `Blivet` class. The
attributes are moved to Anaconda, where they are used.
**Depends on:** https://github.com/rhinstaller/anaconda/pull/1758
> Remove unused code

- blivet/static_data/mpath_info.py
Other options include:
1. use udev info to detect mpath membership
2. try/except
> Don't crash if blockdev mpath plugin isn't available. (#1672971)

- blivet/devices/lvm.py
- blivet/populator/helpers/lvm.py
- blivet/populator/populator.py
- blivet/static_data/__init__.py
- blivet/static_data/lvm_info.py
- tests/populator_test.py
This needs some libblockdev changes -- https://github.com/storaged-project/libblockdev/pull/420 -- and it make take some time before this is merged and available, because it as a backwards incompatible ABI change, so we might need to wait to libblockdev 3.0. But this issue is not so common, so it shouldn't be a problem.
> Mark exported VGs as protected

- blivet/formats/lvmpv.py
Also use the cached PV info instead of running pvinfo again.
Related: rhbz#1676718
-----
The main reason for this change is to fix anaconda crash on systems with a cluster VG. `pvs` on these systems won't show information about the  "cluster" PV, but we still know it is a PV from udev (because it has lvmpv signature) and we are trying to get additional information about. I think it should be safe to just set `free` to 0 (the PV is not really usable) and log error.
> Do not raise exception if can't get PV free space

- blivet/blivet.py
Resolves: rhbz#1676480
`lvmpv.free` raises exception for non-existing PVs. I'm not sure why, it is possible that simply returning "0" would be better way to solve this bug, but it is possible there is some reason behind this behaviour.
Also `fs_free` in `get_free_space` is defined as *space available by shrinking filesystems* so it probably doesn't make sense to include non-existing filesystems.
> Do not try to get format free space for non-existing formats

- blivet/iscsi.py
We don't need the 'storage' argument since the rewrite to udisks.
It would be best to just remove it, but that would be an API
change, so at least set default value to None so blivet users can
easily ignore it.
> iscsi: Add default value to unused 'storage' argument in 'write'

- blivet/formats/disklabel.py
- tests/formats_test/disklabel_test.py
The UEFI spec supports legacy MBR (msdos) in section 5.2 of the UEFI 2.7 spec [1].
There's a number of use cases where we might boot on a UEFI device but want to
support, but not by default, the creation of images using legacy MBR partitions.
One of these use cases is cloud images where we can produce a single image
tha will run on UEFI supported, including secure-boot, clouds but also
support AWS which only supports MBR partitioning schemes [2] and in the current
config anaconda fails the install where this is a perfectly valid and widely
supported deployment mechanism.
So enable the ability to use legacy msdos partitioning schemes, but don't use
it for default installs, so people may consume this mechanism using kickstarts
rather than having the install fail for a valid use case.
[1] …
> Support legacy MBR (msdos) as part of UEFI to enable hybrid builds

- blivet/devices/storage.py
Without this kickstart 'part /home --size=1 --grow --encrypted'
will fail because min size for LUKS is 2 MiB.
Resolves: rhbz#1680013
> Automatically adjust size of growable devices for new format

- blivet/static_data/mpath_info.py
This is a followup for #760. I had fixed this in some copy of the code already, but apparently not the one that matters.
> Ensure correct type of mpath cache member list.

- blivet/__init__.py
- tests/clearpart_test.py
The exceptions caused by using anaconda kickstart with `zerombr` and `--only-use` read-only disk
or `zerombr` and `autopart` now produce a warning instead of crashing.
Added tests for this behavior
Resolves: rhbz#1544425
> Fixed KS forcing zerombr onto RO disk (#1544425)

- blivet/devicelibs/lvm.py
Resolves: rhbz#1643531
Submitted-by: Renaud Métrich <rmetrich@redhat.com>
------
We already do this in libblockdev so newer versions don't need this change.
> Tell LVM to wipe cachepool metadata when attaching the cachepool

- python-blivet.spec
six is needed since 3af623c2a5e57e8397468b4825362275cb0f1ccb but
we forgot to add the dependency to the spec file.
Resolves: rhbz#1647173
> Add dependency on python-six

- blivet/formats/fs.py
It is not possible to mount the filesystem iso9660, if the kernel
module isofs (with alias iso9660) is not already loaded. Blivet will
fail with a message "mounting filesystem iso9660 is not supported",
because the mount type is not in kernel_filesystems, there is no file
/sbin/mount.iso9660 and there is no module iso9660.ko*. Therefore,
let's make sure that the kernel module is loaded.
> Fix mounting of the filesystem iso9660

- Makefile
- blivet/blivet.py
- python-blivet.spec
This provides a make target to create an archive of the tests/ subdirectory and spec file logic to add it to the unpacked sources during rpm build. The remaining piece (that I know of) is to change all of the test dependencies to from `Requires` to `BuildRequires`, which I'm not super excited about.
Thoughts?
> Tests archive

- blivet/platform.py
It is possible to have a virtio disk backed by a DASD disk and
in this case we use disk type to determine best label type
because disk type is not DASD.
Resolves: rhbz#1677383
Submitted-by: Masahiro Matsuya <mmatsuya@redhat.com>
> Recommend DASD disk label for disks with an existing DASD label

- blivet/udev.py
The function `fnmatch` will fail with a traceback if the given filename
is `None`, so let's make sure that `fnmatch` is never called with `None`
or an empty string.
Resolves: rhbz#1698937
> Don't call fnmatch with None (#1698937)

- blivet/iscsi.py
- blivet/udev.py
This needs new version of UDisks with the `GetInitiatorNameRaw` function. #774 should be merged first to avoid conflicts.
> Correctly handle non-unicode iSCSI initiator names

- blivet/populator/populator.py
It is not possible to protect devices from teardown when the
`auto_dev_updates` flag is set. So let's remove` teardown_all`
from the `populate` method and let users to do that.
> Remove teardown_all from the populate method

- blivet/devices/luks.py
We need to propagate the teardown call down to the underlying
device to call teardown on its LUKS format. Teardown for the
Integrity device is a no-op (same as for the LUKS device itself).
> Fix removing LUKS devices with integrity

- blivet/blivet.py
We shouldn't change the format at all if creating format fails for
some reason (for example device being to big/small for the new
format).
----
The original bug was about reusing an existing swap that was larger than our max size for swap (128 GiB). In this situation anaconda will not allow to reuse the swap but it will remove the swap format from it. Anaconda could remove the action too but it doesn't have the action instance so it would be complicated.
> format_device: Revert destroy action if create fails (#1727589)

- blivet/formats/disklabel.py
- blivet/populator/helpers/boot.py
- tests/populator_test.py
pyparted now raises an exception when trying to access partition
name on a disklabel that doesn't support partition names, see
https://github.com/dcantrell/pyparted/issues/59
> Check if disklabel supports partition names (#1723228)

- blivet/devicetree.py
- blivet/errors.py
- tests/devicetree_test.py
When trying to add a non-unique UUID device blivet now
produce more user friendly exception
Changed and added tests accordingly
> Improved non-unique UUID handling

- blivet/devices/lvm.py
- blivet/formats/fs.py
- tests/action_test.py
- tests/devices_test/device_properties_test.py
- tests/devices_test/lvm_test.py
- tests/devicetree_test.py
- tests/formats_test/fstesting.py
- added default minimal file system size into FS class (2 MiB)
- overriden in certain subclasses (e.g. NoDevFS)
- updated tests behavior to reflect the changes
Resolves: #1554519
> Added min size for file systems

- blivet/devicefactory.py
- blivet/devicetree.py
- blivet/populator/helpers/lvm.py
- tests/devicetree_test.py
- removed devicetree.names list
- introduced property with the same name and function
- devicetree.names are now obtained directly from devices
- added a test to check the proper behavior
> devicetree.names is now a property

- blivet/devices/lvm.py
Inherited setters do not work after being wrapped using the
SynchronizedMeta meta class.
-----
I've tried to find a way how to fix this in SynchronizedMeta, but it looks like it is not possible, the setter is just not visible in the child class. There is no problem for properties where both getter and setter are inherited.
> Add 'protected' property setter to LVMVolumeGroupDevice (#1729363)

- blivet/formats/luks.py
Anaconda documentation says that default for XTS should be 512 bits,
our current implementation only works if the cipher is not specified,
if you specify "aes-xts-plain64" (default cipher and mode) without
specifying key size, we will fallback to LUKS default which is only
256 bits.
Resolves: rhbz#1716674
> Always set default key size to 512 bits for ciphers with XTS mode

- blivet/devices/device.py
- blivet/devices/storage.py
This fixes a new pylint warning about Device not having the
'type_external_dependencies' method. The 'external_dependencies'
checks dependencies of all ancestors and theoretically it is
possible that a StorageDevice has Device in its ancestors.
----
We could simply ignore this pylint warning, but I think this time pylint is right, technically we can have a `StorageDevice` with `Device` within its ancestors. And all the `ancestors` and `parents` methods/properties are defined in the `Device` class so it makes sense to have the dependencies functions there too.
> Move dependencies code from StorageDevice to Device

- blivet/deviceaction.py
- blivet/devicefactory.py
- blivet/formats/luks.py
Use `luks_data.min_entropy` if the minimum entropy is not set.
> Always use luks_data.min_entropy as a default minimum entropy

- blivet/devicefactory.py
Factories with zero size are special cases for adjusting container
size after removing a device for it. We don't want to change size
of the factory in this case.
The recent change of filesystem minimal size to 2 MiB resulted
in changing of size of these factories from 0 to 2 MiB which
caused the "adjusting factory" to create a new LV after removing
one from the container.
Resolves: rhbz#1743753
> Do not try to normalize size for zero size device factories

- blivet/util.py
- tests/formats_test/disklabel_test.py
- tests/util_test.py
Fixed the systemd Manager object path, also get_property_sync
returns a tuple so we need to check its first element.
> Fix util.detect_virt function

- blivet/devicelibs/crypto.py
Switch cryptsetup default metadata format to LUKS2.
Related: rhbz#1668013
> Use LUKS2 by default

- blivet/errors.py
- doc/api/blivet.rst
You have as part of your API `UnknownSourceDeviceError` exception but this error is not used anywhere in your code and Anaconda removed the import.
I know you can't just remove this now because it is your API but you should do that on the next opportunity to remove unused code and make your API more lightweight.
Anaconda removing this in PR: https://github.com/rhinstaller/anaconda/pull/1834/
> Remove unused API code

- blivet/devices/disk.py
- blivet/devices/lvm.py
- blivet/devices/md.py
- blivet/devices/partition.py
- blivet/devices/storage.py
- tests/devices_test/lvm_test.py
LVM no longer allows creating VGs on top of disks with different logical sector sizes so we need to check this before running vgcreate (which fails).
There is a pull request for anaconda -- https://github.com/rhinstaller/anaconda/pull/2142 -- which adds a new StorageChecker check but we need to check this also for other users and we also need to provide API for getting sector size for disks without a disklabel.
> Check for PV sector size when creating new VG

- blivet/devices/lvm.py
- blivet/events/manager.py
- tests/events_test.py
- tests/pylint/runpylint.py
Newest release of pylint now correctly recognizes abstract properties -- it found a new problem in `events_test` and we can also remove some disable comments introduced in #804
> More (abstract) property related fixes for new pylint

- tests/pylint/runpylint.py
- tests/run_tests.py
We have a similar script in libblockdev and udisks. I plan to add more features later (e.g. running against installed version, some logging etc.) but for now the biggest feature is it allows running a simple test case using something like `sudo python3 tests/run_tests.py devices_test.device_properties_test.LVMLogicalVolumeDeviceTestCase`
> Add a simple script for running tests manually

- blivet/formats/fs.py
The module is needed only for mounting the filesystem and mount
will autoload the modules so we don't need to load it when
creating the instance. Instead we can use modprobe with the
`--dry-run` option to check if the module is available to mark
the filesystem as (un)supported.
----
This was discovered by anaconda team -- they are not running their unit tests as root so `modprobe` will always. `modrpobe --dry-run` works even when running as a "normal" user because it actually doesn't try to load the module and we don't really need to load the module just to check if the filesystem is mountable/supported.
> Do not load module when creating an FS instance

- blivet/devices/lvm.py
Anaconda needs these to be able to set reserved size or percent
specified in kickstart.
Resolves: rhbz#1737490
> Add setters for requested_size/percent form LVMVolumeGroupDevice

- blivet/devices/disk.py
- blivet/populator/helpers/disk.py
- tests/devices_test/tags_test.py
- tests/populator_test.py
Anaconda needs the "ID_PATH" udev attribute so it's better to
add it to our API so they don't need to get it from "device_links".
> Add a new "id_path" attribute for iSCSI and FCoE disks

- Makefile
'python -m coverage' should always find the executable, even if
installed using pip.
> Do not hardcode coverage executable name

- blivet/formats/fs.py
Fot existing TmpFS formats the _chrooted_mountpoint attribute can
be accessed when running update_size_info() during init so we
need to define it sooner.
Resolves: rhbz#1784690
> Make sure _chrooted_mountpoint attribute is defined before using it

- dbus/blivet.conf
- dbus/blivet.service
- dbus/com.redhat.Blivet0.service
- setup.py
We have changed the version in 98efb38 but never adjusted the
'allow own' policy in the config file so the service actually
can't start now.
Resolves: rhbz#1786919
> Fix Blivet DBus service version in service and config files

- blivet/formats/disklabel.py
- blivet/partitioning.py
- doc/api/formats.rst
- tests/formats_test/disklabel_test.py
- tests/partitioning_test.py
Take the alignment of candidate disks into account when creating the partition request to ensure that the initial/base size is never too small to be allocatable on the specified disks. A simpler approach, like choosing a larger base size than `1 MiB`, is appealing but could be problematic for certain formatting (eg: biosboot).
> Align base partition sizes in PartitionFactory.

- blivet/mounts.py
- blivet/util.py
MD5 is not available in the FIPS mode.
Resolves: rhbz#1792340
> Use SHA256 instead of MD5 for /proc/mounts hash calculation

- scripts/makebumpver
- scripts/makeupdates
Just a quick fix to make these two work on Fedora 31 (where `/usr/bin/python` is Python 3).
> Make 'makeupdates' and 'makebumpver' scripts Python 3 compatible

- blivet/deviceaction.py
- blivet/devicelibs/lvm.py
- blivet/devices/lvm.py
- tests/action_test.py
- tests/devices_test/lvm_test.py
The problem is that we try to activate an lv in order to remove the formatting before destroying the lv, but the activation fails because the user set the lv to ignore activation commands.
It is possible that we should be more cautious and possibly only pass `ignore_skip=True` when we're about to wipe the formatting. That would require setting up a generic mechanism for passing additional arguments, which seems quite disruptive given the problem.
Opinions?
> Tell lvm to ignore skip-activation flag on lvs we are removing or otherwise modifying. (#1766498)

- blivet/formats/fs.py
We should be able to schedule action to change the label on
a non-existing device so we can't check for the device/format
existence in the dry run mode (it's run when applying the action).
> Allow running 'write_label' in dry run mode on non-existing devices

- blivet/udev.py
Taken from #785
This is a good workaround for rhbz#1798792 which is currently a Fedora 32 blocker. Root of the problem is an mdadm udev rule which adds the `MD_DEVNAME` property (and other `MD_` properties) to the RAID member partitions which makes us think the partition is actually on the mdraid.
> Fix name resolution for md member partitions. (#1798792)

- blivet/udev.py
In some cases some NVDIMM namespaces don't have the ID_PATH set
and this makes the populate helper crash.
> Fix crash for devices without ID_PATH udev property (#1814920)

- blivet/devices/lvm.py
Reserving space in the VG and reserving space for thin pool metadata should not be mutually exclusive.
> Allow for reserved vg space and a growable thin pool. (#1783946)

- blivet/devicefactory.py
For names that are made entirely of prohibited characters we
remove all of these and set name to empty string which is also
invalid a causes problems in Anaconda.
> Do not set empty name instead of invalid one in devicefactory (#1813710)

- blivet/devices/md.py
- blivet/populator/helpers/boot.py
It's possible to have /boot/efi on an MD RAID device -- with the
older version of metadata and RAID1 it looks like a normal
partition and EFI can boot from it.
> Correctly recognize EFI format on an MD RAID device (#1695913)

- blivet/devicefactory.py
We need to rename the underlying device (LV in this case), not
the LUKSDevice which doesn't have name. This is a problem only
when encrypting LVs directly, this doesn't happen with the default
configuration where PVs are encrypted (because PVs are usually
partitions that can't be encrypted).
Resolves: rhbz#1759972
> Fix renaming encrypted devices in the DeviceFactory

- blivet/devices/storage.py
- blivet/formats/fs.py
- tests/devices_test/network_test.py
This option is used also for non-network devices like Clevis-Tang
protected LUKS devices so we can't remove it.
Resolves: rhbz#1722262
> Do not remove _netdev mount option specified manually by users

- blivet/blivet.py
We have all the information in the storage.log from reset but it's sometimes hard to decrypt the real storage layout from our populate/reset messages. Anaconda saves lsblk output but only for crashes so we don't always have it and if the crash happens during do_it, storage configuration is already changed. I'm logging lsblk in blivet-gui and it's really useful to have it for a quick debugging.
> Log current storage state before reset using lsblk

- blivet/devicefactory.py
The device factory should create encrypted containers with the requested
LUKS version.
Related: rhbz#1714120
> Use the specified LUKS version for container encryption

- tests/pylint/runpylint.py
We are disabling this warning locally using the "pylint: disable"
comment but this is currently broken with pylint 2.5.0, see
https://github.com/PyCQA/pylint/issues/3526
> Mark warning "'GError' has no 'message' member" as false positive

- blivet/devices/lvm.py
- blivet/devices/storage.py
- tests/devices_test/lvm_test.py
- tests/devices_test/partition_test.py
A simple check if the device is empty -- there is no filesystem
and partitioned devices don't have partitions (or only "magic"
partitions).
This is basically just a copy of the `_is_device_empty` function from Anaconda used for clearpart -- https://github.com/rhinstaller/anaconda/blob/master/pyanaconda/modules/storage/disk_initialization/configuration.py#L119 -- I don't think installer should deal with such "low level" stuff as magic partitions so this makes more sense in Blivet.
> Add "is_empty" property to StorageDevice

- blivet/devicetree.py
- tests/devicetree_test.py
Without this it's not possible to create a device with same name
after destroying and existing one.
-------
The issue is result of switching to names being a property in #688 The code which checked names of all existing LVs was originally in the LVM populator helper. I'm not sure why exactly we were adding names of all LVs to the list but I assume it was to include names of unsupported and internal LVs.
I think with this change the `names` property should behave the way it did before the change -- it will always contain all LVs except the ones we scheduled for removal (these were originally removed from the list in `devicetree._remove_device`) so this change should be safe.
> Do no include destroyed devices in list of names (#1830515)

- blivet/devices/luks.py
- tests/devices_test/size_test.py
The LUKS device "inherits" its size from the parent so we are
just setting the parent's size here. This allows automatic size
adjustments for format minimum size for growable devices with
sizes smaller than format minimum size (e.g. using --grow in
kickstart for PVs).
Resolves: rhbz#1836269
-----
I'm not sure about this one. There are two issues here. First, the size setter currently doesn't work for `LUKSDevice` at all. I think it's python problem with mixing the new style properties (using the `@property` decorator) and the old style properties and the setter from `StorageDevice` is currently not being inherited which causes the installation crash with the `can't set attribute` error. Second issue is about setting size for the `LUKSDevice` during `_set_format` -- the device factory …
> Allow setting size for non-existing LUKS devices

- blivet/devicefactory.py
- tests/devicefactory_test.py
We need to remove the member (LUKSDevice) from the container's
parents before trying to remove the member itself. Removing it
from the container parents will also remove the container from
the member children allowing us to remove the member because
devices with children (non-leaf devices) can't be removed.
> Fix toggling container encryption in devicefactory (#1827254)

- tests/formats_test/fstesting.py
We can have tools to create the filesystem without having kernel
module for mounting it.
> Skip test_mounting for filesystems that are not mountable

- blivet/devices/partition.py
- tests/devices_test/partition_test.py
Existing extended partitions should be always resizable. We can't
default to StorageDevice.resizable because it also checks format
for being resizable.
------
I found this when fixing resize option in blivet-gui in https://github.com/storaged-project/blivet-gui/pull/182.
> Make extended partitions resizable

- Makefile
pycodestyle doesn't like variables named "l" and its latest
version got better in discovering them in our code.
> Ignore pycodestyle warning E741

- blivet/devices/partition.py
This fixes isses in anaconda unit tests where some non-existing
partitions can have disk set to None. We don't allow resizing of
non-existing devices so it is safe to return False here.
> Fix resizable property for partitions

- blivet/deviceaction.py
Original format should be always set to the "real" format for
existing devices. This normally happens in the StorageDevice
constructor but newly created devices have original_format always
set to DeviceFormat and require running reset to correct this which
can cause various issues when doing multiple do_it operations
without running reset between them.
Resolves: rhbz#1820888
----
This bug was really "fun" to debug. Removing an existing LUKS device that was created without running `reset` after `do_it` crashes because the LUKS is not closed. It is open because there is no LUKS format to run `teardown` on. Both `format` and `original_format` are set to the default `DeviceFormat` -- `format` is removed when scheduling the destroy action and `original_format` is not set.
This was originally …
> Set device.original_format to the new format in ActionCreateFormat

- blivet/udev.py
Some Innovation IT NVMe devices have an (invalid) unicode in their
model name.
Resolves: rhbz#1849326
> Fix possible UnicodeDecodeError when reading model from sysfs

- blivet/formats/swap.py
- tests/formats_test/swap_test.py
The limit was part of change to limit suggested swap size in
kickstart which doesn't use the SwapSpace._max_size so there is no
reason to limit this for manual installations.
Resolves: rhbz#1656485
----
I'm not sure why the limit was enforced here in the first place. The `iutil.swapSuggestion` never used it (its original version used the same `SWAP_SIZE_LIMIT` constant but never `SwapSpace._max_size` directly) and the referenced bug is only about the `swap --recommended` kickstart command.
Few very old anaconda commits related to this:
- https://github.com/rhinstaller/anaconda/commit/d665afe10a38e5eae2e0605513fdce554d3b2cf4
- https://github.com/rhinstaller/anaconda/commit/62c250e71e6040f71d9ad09d50908342f2d1b394
- https://github.com/rhinstaller/anaconda/commit/98a347672c4a7c6972fa7e4af3d22 …
> Do not limit swap to 128 GiB

- blivet/devices/cache.py
- blivet/devices/lvm.py
Only "read" support for now, we need libblockdev support to able
to create a writecache device. With this we at least won't crash
on systems with existing writecache.
> Add basic support for LVM writecache devices

- blivet/blivet.py
These options were added in util-linux 2.33 which is not available
on older systems so we should not use these.
Fixes: #864
> Do not use FSAVAIL and FSUSE% options when running lsblk

- blivet/formats/fs.py
The function unfortunately uses only the name when searching for
the module and we need to use aliases for modules like ext2 and
ext3. So we need to use "modprobe --dry-run" instead.
> Do not use BlockDev.utils_have_kernel_module to check for modules

- blivet/formats/fs.py
exFAT support is slowly coming to Fedora so we should be able to
recognize it instead of marking is as an unknown "DeviceFormat".
> Add exFAT to filesystems we recognize

- blivet/partitioning.py
- tests/partitioning_test.py
Our users shouldn't need to catch parted exception, we should use
our PartitioningError where possible.
Related: rhbz#1855386
> Do not propagate ped exception from add_partition

- tests/devicefactory_test.py
- tests/devices_test/device_methods_test.py
- tests/devicetree_test.py
- tests/unsupported_disklabel_test.py
Fixes: #870 
The biggest issue here is LVM, we need root just to query LVM DBus API. We could also simply skip these tests when running as a non-root user, but I think these patches shouldn't affect the tests.
> Fix running tests as non-root

- blivet/populator/populator.py
- blivet/udev.py
NVMe multipath devices have a special internal hidden devices that
are visible in /sys/block but not directly usable so we should
ignore these as well as all devices with the hidden attribute.
> Ignore devices marked as hidden in sysfs (#1856974)

- blivet/blivet.py
- blivet/devicefactory.py
- blivet/devicelibs/btrfs.py
- blivet/devicelibs/lvm.py
- blivet/devicelibs/mdraid.py
This allows us to have a different safe device names for different
device types and for example allow characters like "@" and "/" for
btrfs only.
> Make safe_device_name device type specific

- tests/vmtests/vmbackedtestcase.py
zRAM is now enabled by default on latest Fedora and because it
looks like a disk we try to use it during the tests.
> Ignore zRAM devices in VMBackedTestCase

- blivet/devices/lvm.py
- tests/devices_test/lvm_test.py
- changed exception types in devices/lvm.py to
be more consistent (as per https://github.com/storaged-project/blivet/issues/528)
- these modifications change API
Fixes #528
> More consistent lvm errors (API break)

- blivet/udev.py
util.get_sysfs_attr returns a string so bool(hidden) is always
True and we hide all devices.
> Fix reading hidden sysfs attribute

- blivet/populator/helpers/dm.py
- tests/populator_test.py
For these devices we should add a "plain" DMDevice to the tree.
> Do not ignore unknown/unsupported device mapper devices

- blivet/devicefactory.py
- blivet/devices/dm.py
- blivet/devices/loop.py
- blivet/devices/luks.py
- blivet/errors.py
- blivet/partitioning.py
- blivet/populator/helpers/dm.py
- blivet/populator/helpers/luks.py
- blivet/populator/helpers/lvm.py
- blivet/populator/helpers/mdraid.py
- blivet/populator/helpers/multipath.py
- blivet/populator/populator.py
- blivet/threads.py
- blivet/udev.py
- tests/devicefactory_test.py
- tests/devices_test/size_test.py
- tests/populator_test.py
- tests/udev_test.py
- tests/vmtests/vmbackedtestcase.py
New version of #863 rebased to 3.3-devel with some more overlooked and recently added problematic words. I've also removed the deprecation warning notices: none of the properties and functions are part of the [stable API](https://github.com/storaged-project/blivet/blob/3.3-devel/doc/api.rst), we'll just make a note in 3.3 release notes.
> Terminology cleanups

- blivet/devicetree.py
- tests/devicetree_test.py
For disk-like devices like multipath we should allow to ignore
these by simply ignoring the mpath device or by ignoring all or one
of its drives.
- when ignoring the "mpatha" device we should also ignore "sda" and
"sdb"
- when ignoring both "sda" and "sdb" we should also ignore "mpatha"
- when ignoring only "sda" we should also ignore "mpatha" (we don't
want to deal with an "incomplete" multipath device in the tree)
This is consistent with the existing behaviour when using exclusive
disks (or "ignoredisks --only-use" in kickstart).
Resolves: rhbz#1866243
> Fix ignoring disk devices with parents or children

- blivet/devices/lvm.py
When making space for the bigger metadata we also need to make
extra space for pmspare because its size depends on the metadata
size.
Resolves: rhbz#1868623
> Account for pmspare grow when adjusting thinpool metadata size

- tests/pylint/runpylint.py
This warns about not using the "raise ... from" syntax which is
not available in Python 2 so we can't use it.
> Ignore new pylint warning W0707 "raise-missing-from"

- blivet/devicelibs/edd.py
If the device is unmapped from the storage side, the os.read will fail with i/o error. However, here it's not closing the fd and hence any process using the blivet module will hold the device indefinitely. This prevents administrator from removing the device from multipath layer.
```
10078 10:38:25.869889 open("/dev/mapper/36001405097fdbe4d6e04e3b9bdc97014", O_RDONLY <unfinished ...>
10078 10:38:25.870015 <... open resumed>) = 25
10078 10:38:25.870415 lseek(25, 440, SEEK_SET <unfinished ...>
10078 10:38:25.870600 read(25,  <unfinished ...>
10078 10:38:25.870759 <... read resumed>0x7f865c0ec984, 4) = -1 EIO (Input/output error)
< --  jumped to next device without closing the fd 25 -->
10078 10:38:25.871192 open("/dev/sda", O_RDONLY <unfinished ...>
< -- device is in hold by the supervdsm …
```
> Close fd if it fails to read the device

- blivet/devices/storage.py
- blivet/formats/fs.py
- blivet/formats/luks.py
- blivet/formats/swap.py
- blivet/mounts.py
- tests/devices_test/device_methods_test.py
Apparently it is completely normal to have hundreds of btrfs snapshots and blivet is currently not very good in handling this situation. `reset` is relatively fast, but `teardown_all` (which anaconda runs multiple times during installation) can take more than 10 minutes on systems with 500 snapshots ([rhbz#1876162](https://bugzilla.redhat.com/show_bug.cgi?id=1876162)).
I was able to find two issues in our code:
- `MountsCache` uses `udev.resolve_device` for every mountpoint query. `resolve_device` itself uses `udev.settle` and also iterates over all devices in the UDev database.
- `StorageDevice._pre_teardown` always runs `udev.settle` even when the `teardown` is no-op. This means we run `udev.settle` 3 times for every snapshot during `teardown_all`.
> Avoid using unnecessary udev.settle calls

- blivet/devicetree.py
- blivet/errors.py
- tests/devicetree_test.py
Follow-up for https://github.com/storaged-project/blivet/pull/883
to make Anaconda show a error message instead of crashing.
> Use UnusableConfigurationError for patially hidden multipath devices

- blivet/devicelibs/edd.py
The "fd" variable is not defined when the "os.open" fails (e.g.
when the device we try to open doesn't exist).
Follow up for #899
> edd: Fix UnboundLocalError when trying to close fd in collect_mbrs

- blivet/populator/populator.py
This will automatically fix issues like GPT partition table not
covering whole device after disk size change.
Resolves: rhbz#1846869
-----
I'd like to know your opinion about this change. I'm not sure if this is the best way to fix the problem (blivet crashing when trying to add partition to such disk). There is no way to tell what issue is being fixed (other than exception message) and this also means we'll do partition table changes during populate without asking. On the other hand, there is no way to detect this problem, so we can't mark the disk as "broken" and avoid using it in autopart.
> Let parted fix fixable issues with partition table

- blivet/iscsi.py
The startup method of the iSCSI class should start the iscsi-init service that
generates the /etc/iscsi/initiatorname.iscsi file. Otherwise, the file might
not exist and the getter of the initiator property might raise an exception.
Resolves: rhbz#1880673
> Start the iscsi-init service (#1880673)

- blivet/blivet.py
Resolves: rhbz#1888287
Because sometimes anaconda tells us the product name is `'hel`.
> Make sure the product name is safe when using it for device name

- blivet/blivet.py
The attribute `__luks_devs` in the `Blivet` class is never used.
> Remove an unused attribute from the Blivet class

- .packit.yaml
Testing Farm Team cluster does not work reliably. It should be fine during
January but until then let's avoid these constant tests failures.
> TFT is still broken so let's avoid failures by just doing a build

- blivet/devices/lib.py
It makes development and debugging easier and makes output of
device.parents and device.children (which is a simple list) same.
Before:
```
In [3]: sde1.parents
Out[3]: <blivet.devices.lib.ParentList at 0x7efe56aa7430>
```
After:
```
In [3]: sde1.parents
Out[3]: 
[DiskDevice instance (0x7f32cbd4f940) --
name = sde  status = True  id = 17
children = []
parents = []
uuid = None  size = 1024 MiB
format = existing msdos disklabel
major = 8  minor = 64  exists = True  protected = False
sysfs path = /sys/devices/pci0000:00/0000:00:07.0/host9/target9:0:1/9:0:1:0/block/sde
target size = 1024 MiB  path = /dev/sde
format args = []  original_format = disklabel  removable = False  wwn = None]
```
> Add __repr__ and __str__ methods to ParentList

- blivet/blivet.py
- blivet/devicefactory.py
- tests/devicefactory_test.py
- tests/misc_test.py
This fixes issue that happens when trying to add a new LV to an existing VG. This is not possible to do directly, new VG is always created for the new LV so user needs to move it to the existing VG after that. The problem here is we recommend a name that is unique in the new VG (for example `root` for `/`) but it might not be unique in the existing VG so user would need to rename the LV before moving it. Technically this is correct behaviour -- Anaconda tells us to use name that is not unique (that we recommended for a different VG) but it's not really user friendly to recommend a name and tell user it isn't unique in the next step.
I also tried to clean the suggest name functions a little and reuse the code that adds `00` to the name to make it unique.
> Make sure LV names are unique in device factory

- tests/pylint/censorship.py
- tests/pylint/pylintrc
- tests/pylint/runpylint.py
- translation-canary/translation_canary/translated/test_markup.py
This is based on similar change Anaconda did recently, see
rhinstaller/anaconda#2289
Using pylint directly is much faster than pocketlint. And pocketlint
doesn't really add that much functionality, we currently only use
the option to skip false positive reports based on a regex and this
can be done with pylint too.
pocketlint:
real    1m55,183s
user    9m4,957s
sys     0m23,387s
pylint:
real    0m39,922s
user    4m38,094s
sys     0m4,393s
> Replace pocketlint by a custom script

- blivet/blivet.py
We removed the "_get_container_name_template" method in
https://github.com/storaged-project/blivet/pull/911 but Anaconda
has its own version of it so we need to keep it in our code so
Anaconda can override it with their specific version in
InstallerStorage.
> Fix "suggest_container_name" for Anaconda

- blivet/devices/luks.py
- blivet/devices/partition.py
When adding two partitions we can end up with two LUKS devices
with the same name because the name of the underlying partition
changed after adding the second one but the LUKS device name
didn't change.
Resolves: rhbz#188355
> Update LUKS device name after parent partition name change

- tests/devicefactory_test.py
The test was added to 3.3-devel before merging the LVM VDO code so we need to adjust it to work with LVM VDO.
> Make sure we use size >= LVM VDO min size in test_lv_unique_name

- scripts/makeupdates
Anaconda is not going to support Python site packages in `/run/install/updates`.
**Related to:** https://github.com/rhinstaller/anaconda/pull/3127 (but it doesn't depend on it)
> Use real paths to Python site packages

- blivet/formats/fs.py
- blivet/util.py
When installing a system with non-standard mount points such as `/apps`, the mount point is created with `etc_runtime_t` label instead of `default_t`.
This is due to using the **0** parameter as mode in `matchpatchcon()` instead of explicitly specifying it's a directory.
Indeed, in the SELinux database, there are 2 rules for `/apps` and related:
~~~
/.*                                                all files          system_u:object_r:default_t:s0 
/[^/]+                                             regular file       system_u:object_r:etc_runtime_t:s0 
~~~
> apply directory's SELinux context to freshly created mount points

- blivet/deviceaction.py
- tests/devices_test/lvm_test.py
We don't need VDO to be able to remove these.
Resolves: rhbz#1933611
> Allow removing LVM VDO devices without VDO support

- blivet/udev.py
We swiched to util.get_sysfs_attr when reading device model in
e8afad15aee5a85aaaa59abcff8b1b58539c748e which logs warning for
non-existing sysfs attributes which leads to excessive logging
because we are checking all devices including those that don't
have model attribute. This adds additional check to prevent this.
Related: rhbz#1849326
> Fix excessive logging in udev.__is_ignored_blockdev

- tests/devices_test/lvm_test.py
Found when working on tests for #940. mock.called_with is always
true, because it's just another custom mocked function, correct
function is assert_called_with.
> Fix usage of assert_called_with in lvm_test

- python-blivet.spec
make is no longer present in the Fedora build environment by
default.
----
We already have this in dist-git and on 3.4-release (see https://github.com/storaged-project/blivet/commit/bb0dc95a59b8e69f83dbf07d0267b015154c68f6) but we also need make in spec here on the devel branch for packit builds.
> spec: Add 'make' to BuildRequires

- blivet/iscsi.py
We do this every time and in most cases the call will fail
because there is no ISCSI firmware. Having the entire exception
logged is not useful for us (it will always be the same backtrace
for a failed DBus call) and it confuses users when reporting bugs
because it's the first error message in the log.
> Do not log entire exception when trying to get ISCSI initiator name

- blivet/devices/md.py
- blivet/zfcp.py
IOError is only an alias of OSError since Python 3.3.
Related: #944
> Replace IOError for file operations

- blivet/formats/disklabel.py
Simple instance of DiskLabel without label_type specified in the
constructor results in a AttributeError when trying to print the
format name. This makes sure the name is always valid.
Resolves: rhbz#1945914
------
Anaconda hits this when it's gathering format types for some DBus shenanigans. Simple reproducer is to get disklabel without specifying type `blivet.formats.get_format("disklabel")` and it will fail when printing the disklabel info (because `__repr__` prints `name`). Alternatively we could make sure the `_default_label_type` is never `None` but that might break more things. It might be also better to have a special `name` for this "disklabel without type" but I wasn't able to come up with something that makes sense, so feel free to suggest something better.
> Avoid AttributeError for DiskLabel formats without disklabel type

- blivet/devices/partition.py
For 512 B partitions, pyparted throws ArithmeticError when trying
to align their size down which crashes the installer when trying
to get max size of such partitions.
Resolves: rhbz#1947985
> Ignore ArithmeticError when trying to align partition size down

- blivet/devices/btrfs.py
Resolves: rhbz#1860602
-----
This isn't really a fix, just a workaround. @dwlehman mentioned similar issue happening in the [store role](https://github.com/linux-system-roles/storage) too, we should consider reading the UUID and similar properties we gather in `_post_create` from other sources than UDev. We run `udev.settle()` but it doesn't help.
> Try to get Btrfs volume UUID using libblockdev if UDev lookup fails

- blivet/devices/lvm.py
- blivet/errors.py
- tests/devices_test/lvm_test.py
List of pvs with sector sizes is now part of the error message. I've also added a new exception for Anaconda to catch so they can add more information in the UI (workarounds in kickstart etc.).
> Provide better error message for LVM with inconsistent sector sizes

- blivet/blivet.py
We switched "encryption_passphrase" to property in 2.0 but the
removing of the attribute didn't make it to 3.0-devel probably
because of some merge conflict issue between 2.2-devel and
3.0-devel.
Related: https://github.com/storaged-project/blivet/pull/404
> Remove the "encryption_passphrase" attribute from Blivet class

- doc/api/blivet.rst
- doc/api/devices.rst
Forgot to add this in the LVM VDO PR. Surprisingly simple API, but based on the other LVM "public API", this is all that's needed.
> Add LVM VDO to public API

- blivet/formats/fs.py
- python-blivet.spec
Parted automatically sets the ESP flag together with the boot flag
on GPT but not on MBR which means a wrong partition ID will be set
on MBR (FAT specific ID 0x6 instead of 0xef for EFI system
partition) because partition IDs are based on flags with parted.
To make sure the correct ID is set we need to set both flags
manually on both GPT and MBR.
> Set both boot and ESP flag for EFIFS partitions (#1930486)

- blivet/tasks/availability.py
- blivet/tasks/fslabeling.py
- blivet/tasks/fswritelabel.py
The default "NO NAME" label is now not printed by the "dosfslabel"
tool and a new option "--reset" must be used to set empty label.
> Adapt to dosfstools 4.2 FAT label changes

- blivet/devicetree.py
- tests/devicetree_test.py
A RAID array named "10" will not be resolved because we try to
resolve it using EDD data and after this lookup fails, we don't
try the name.
Resolves: rhbz#1960798
> Fix resolving devices with names that look like BIOS drive number

- blivet/actionlist.py
- blivet/devicelibs/lvm.py
- tests/devicetree_test.py
Because the filter is a list internally we can add a device multiple times to it and remove it only once when we decide to use the device.
> Fix adding/removing devices to the LVM reject filter

- blivet/util.py
Xen is apparently still alive so we should return True for it too.
-----
Discover by the new Fedora/RHEL tests that run in EC2. I guess we could also adjust the `MiscTest.test_detect_virt` test but I think it makes more sense to return `True` for Xen too.
> Fix util.virt_detect on Xen

- blivet/deviceaction.py
- blivet/devices/lvm.py
- blivet/devices/storage.py
- tests/action_test.py
- tests/devices_test/lvm_test.py
Currently only volume groups and logical volumes can be renamed.
----
The internal implementation for LVs is a little messier because of the difference between `name` and `lvname`, but I think it makes more sense making the API for users simpler (changing `name` for all devices) even thought the implementation is a little bit uglier.
> Add support for renaming devices using ActionConfigureDevice

- blivet/blivet.py
- blivet/devices/device.py
- blivet/util.py
- tests/misc_test.py
We need a special sorting key for partitions to make sure they are
sorted like "sda1, sda2, ..., sda10" and not like "sda1, sda10,
sda2, ...".
Resolves: rhbz#1915333
----
When removing a logical partition, the "higher number" partitions are automatically renumbered (e.g. with sda5 and sda6, sda6 becomes sda5 after removing sda5). We have a code to adjust to this behaviour (sorting destroy actions etc.) but it still causes issues for Anaconda when allowing to remove partitions in the UI where Anaconda uses the displayed name to remove the partition which no longer exists in the model. By correctly sorting the partitions we can make sure Anaconda removes them in correct order (see also https://github.com/rhinstaller/anaconda/pull/2755).
> When sorting devices make sure partitions are sorted correctly

- blivet/devices/lvm.py
The old style snapshots are activated together with the origin LV
so we need to make sure it is activated to be able to remove the
snapshot or its format.
Resolves: rhbz#1961739
> Fix activating old style LVM snapshots

- blivet/formats/fs.py
- python-blivet.spec
This reverts commit aeffc4d50d5059e6a782ee41ccd49061d28996ab.
Using the correct 0xef partition type for EFI System Partition
unfortunately doesn't work with RaspberryPi so we need to keep
using 0x06 with "normal" boot flag to make it boot.
Resolves: rhbz#1975375
> Revert "Use PARTITION_ESP flag for EFIFS partitions (#1930486)"

- blivet/devicelibs/raid.py
- blivet/devices/md.py
- tests/devices_test/md_test.py
Setting chunk size for RAID 1 doesn't make sense and latest
mdadm started returning error instead of ignoring the --chunk
option when creating an array.
Resolves: rhbz#1987170
> Do not set chunk size for RAID 1

- blivet/threads.py
We use it only with Python 2, Python 3 branch uses current_thread.
> pylint: Ignore deprecation warning about threading.currentThread

- blivet/deviceaction.py
- blivet/tasks/availability.py
The existing error message can be confusing for people that don't
know internals of blivet and libblockdev and the information what
is actually broken or not installed on the system is missing
completely. Example for LVM VDO with missing kvdo module:
Before:
device type lvmvdopool requires unavailable_dependencies:
libblockdev lvm plugin (vdo technology)
After:
device type lvmvdopool requires unavailable_dependencies:
libblockdev lvm plugin (vdo technology):
libblockdev plugin lvm is loaded but some required technologies
are not available (BD_LVM_TECH_VDO: Kernel module 'kvdo' not
available)
> Improve error message printed for missing dependecies

- blivet/formats/lvmpv.py
"self.device" is string for formats so accessing "self.device.path"
results in an AttributeError.
> Fix getting PV info in LVMPhysicalVolume from the cache

- blivet/deviceaction.py
The check fails for actions with devices that don't have
a container, e.g. when removing a partition and also removing
a member from a container.
> Fix ActionRemoveMember requires check (#1993655)

- blivet/devices/btrfs.py
The FS.mount/setup does additional things, notably setting SELinux
context when running in the installer mode, which we don't want to
do when mounting the btrfs volume just to get list of subvolumes.
> Do not use FS.mount for btrfs temporary mounts

- blivet/iscsi.py
- blivet/tasks/availability.py
- setup.py
We have some hacks in `setup.py` so it's possible this breaks *something* but everything I was able to manually test seems to be working. I guess we won't be sure until next upstream release.
> Distutils deprecation

- blivet/devices/container.py
- blivet/devices/disk.py
- blivet/devices/dm.py
- blivet/devices/lvm.py
- blivet/devices/md.py
- blivet/devices/optical.py
- blivet/devices/partition.py
- blivet/devices/storage.py
DeviceError doesn't expect additional arguments which leads to the
exception message being tuple of (msg, name) instead of a simple
string.
------
I've tried to find out why the name is added for some `DeviceError`s, but as far as I can tell it never expected device name as a second parameter. We have some exceptions like that (notably `UnusableConfigurationError`, but not `DeviceError`). I added the name to the exception string where it makes sense and for most calls it's also logged by `log_method_call` so we shouldn't lose any information. Feel free to suggest better messages for the exceptions.
> Do not add device name as a parameter for errors.DeviceError

- blivet/flags.py
We are not using the flag internally and Anaconda is not setting it, see also https://github.com/rhinstaller/anaconda/pull/3586#issuecomment-910462263
> Remove unused flag multipath

- blivet/errors.py
- blivet/fcoe.py
- blivet/iscsi.py
IOError is now deprecated and only an alias to OSError. Raising
IOError doesn't really makes sense for our use cases so we are
replacing it with custom FCoE/ISCSIError exceptions that are also
subclasses of OSError to keep backward compatibility.
Fixes: #944
> Do not raise deprecated IOError from iscsi and fcoe modules

- Makefile
This will make specifying an alternative branch for RHEL releases
easier.
> Makefile: Specify weblate repository branch for the potfile target

- blivet/populator/helpers/luks.py
- tests/formats_test/luks_test.py
We assume that all LUKS device are named luks-<UUID>. This is true
for devices activated by us or UDisks, but manually opened devices
can have a different name. This change uses sysfs holders to check
the "real" name for opened LUKS devices and makes sure we always
set correct state for the LUKS format based on the name (we check
whether /dev/mapper/<map_name> exists when checking whether the
LUKS format is active or not).
> Set correct map name for existing LUKS devices

- blivet/zfcp.py
Values parsed from `/proc/scsi/scsi` were not correctly used to assemble
paths to SCSI devices.
For example:
`/sys/bus/scsi/devices/0:0:00:00/`
was incorrectly accessed instead of:
`/sys/bus/scsi/devices/0:0:0:0/`
Switch to a more reliable way of listing the available SCSI devices.
> Fix removing zFCP SCSI devices

- blivet/actionlist.py
- blivet/devicelibs/lvm.py
- blivet/devices/lvm.py
- blivet/devicetree.py
- blivet/formats/lvmpv.py
- blivet/populator/helpers/lvm.py
- blivet/populator/helpers/partition.py
- blivet/populator/populator.py
- tests/devicetree_test.py
- tests/populator_test.py
Work in progress version of the LVM devices file and "filtering" support (check [lvmdevices manpage](https://man7.org/linux/man-pages/man8/lvmdevices.8.html) for more information about this new LVM feature).
Because we need to support the "old" lvm.conf based filtering too (the new LVM devices feature is currently available only on CentOS/RHEL 9) the first commit switches from the existing *reject* based filtering to *accept* based. This is the biggest change in this PR, the LVM devices support itself is just about switching from calling LVM with `--config devices` to `--devices`. Libblockdev support needs to merged first, see https://github.com/storaged-project/libblockdev/pull/646
> LVM devices support

- blivet/blivet.py
- blivet/devicefactory.py
- blivet/devicelibs/stratis.py
- blivet/devices/__init__.py
- blivet/devices/stratis.py
- blivet/errors.py
- blivet/formats/__init__.py
- blivet/formats/fs.py
- blivet/formats/stratis.py
- blivet/populator/helpers/__init__.py
- blivet/populator/helpers/dm.py
- blivet/populator/helpers/formatpopulator.py
- blivet/populator/helpers/luks.py
- blivet/populator/helpers/stratis.py
- blivet/populator/populator.py
- blivet/safe_dbus.py
- blivet/static_data/__init__.py
- blivet/static_data/stratis_info.py
- blivet/tasks/fsmount.py
- blivet/udev.py
- doc/api/blivet.rst
- doc/api/devices.rst
- doc/api/formats.rst
- examples/stratis.py
- tests/devicefactory_test.py
- tests/devices_test/stratis_test.py
- tests/populator_test.py
New version of #915 I made some smaller changes in the code, the biggest difference are names of the Stratis devices, I've removed the underscore in `stratis pool` and `stratis filesystem` to make it more consistent with our other names. This now includes support for both "normal" and encrypted pools.
I've also moved this to 3.5-devel to make 3.4.0 release a little bit smaller and to have more time for testing and review here.
You can use blivet-gui for testing (everything except devicefactory support), I have a PR with experimental Stratis support here https://github.com/storaged-project/blivet-gui/pull/277
> Stratis support v2

- blivet/devicelibs/lvm.py
- blivet/devices/lvm.py
- tests/devices_test/lvm_test.py
With our default chunk size of 64 KiB we cannot create bigger
thin pools than 15.88 TiB. Unfortunately we need to specify chunk
size to be able to calculate thin metadata properly so we can't
simply leave this to LVM to determine the correct chunk size.
> Use bigger chunk size for thinpools bigger than ~15.88 TiB

- blivet/devicelibs/crypto.py
- blivet/devices/luks.py
- blivet/errors.py
- blivet/formats/luks.py
- blivet/populator/helpers/luks.py
- blivet/tasks/availability.py
- tests/formats_test/luks_test.py
Advanced options for the integrity format are not support, users
can choose only the integrity algorithm (HMAC is not supported)
and sector size.
Depends on https://github.com/storaged-project/libblockdev/pull/663 (but if the `availability` code works we don't need the new version of libblockdev to merge this).
> Add support for creating standalone integrity devices

- blivet/iscsi.py
We don't get any useful information from the exception, it's
always the same traceback from a failed DBus call and we only use
these when a called failed because firmware ISCSI is not supported.
The resulting log message also looks like a failure with the
traceback logged and not just as a debug information.
Resolves: rhbz#2028134
----
Similar to #943, we had the `log_exception_info` function on two other places that are not triggered so often and as visible as the previous one, but it's still confusing when we log the entire traceback for something that isn't critical.
> iscsi: Replace all log_exception_info calls with log.info

- README.md
storaged.org/blivet/docs contains old documentation, latest version
is available at storaged.org/blivet
> README: Fix API documentation link

- blivet/devices/btrfs.py
We are currently using the btrfs volume mountpoint when trying to
get list of subvolumes and if the volume isn't mounted, we don't
show the subvolumes. But if one of the subvolumes is mounted
(like with the default Fedora installation where / and /home are
mounted) we can also use the subvolume mountpoint to run the
"btrfs subvol list <mnt>" command. This change makes sure we check
all the possible mountpoints to show the subvolumes.
Resolves: rhbz#1856048
> Use subvolume mountpoints when listing btrfs subvolumes

- blivet/devicelibs/lvm.py
- blivet/formats/lvmpv.py
Running pvcreate with --devices doesn't work with LVM DBus API,
because with --devices the newly created PV is not added to the
system.devices config file which means lvmdbusd isn't able to find
the newly created PV when it runs 'pvs' internally and the PvCreate
call fails.
> Do not run pvcreate with --devices and list of PVs

- blivet/devices/lvm.py
We read cache stats from the DM table so it's not available for
inactive logical volumes. We can use the metadata size we get from
the internal LV in this case.
Resolves: rhbz#1893553
> Do no try to read cache MD size for inactive LVs from cache stats

- blivet/devicefactory.py
- blivet/partitioning.py
For multipath devices anaconda creates the `PartitionFactory` with both the multipath device and the disks (so for example with `disks=["sda", "sdb", "mpatha"]`). Technically speaking this isn't correct but we allow this in other factories and when `LVMFactory` is used we exclude the disks in the `PartitionSetFactory` when creating the physical volumes so we should do the same with the `PartitionFactory`.
> Exclude unusable disks from PartitionFactory 

- blivet/devices/btrfs.py
If we don't specify the subvolid=5 we end up mounting the default
subvolume and if it isn't the top volume one, we can't remove
other subvolumes "higher" in the hierarchy.
This makes the installer crash when reinstalling over a preexisting
btrfs installation, for example the default openSUSE installation
where the default subvolume is a post installation snapshot.
Resolves: rhbz#2026205
> Make sure we mount the top level subvolume when mounting btrfs

- blivet/blivet.py
- blivet/devicelibs/lvm.py
- blivet/devices/lvm.py
- examples/lvm_cachepool.py
- tests/devices_test/lvm_test.py
This adds support for creating LVM cache pools, the goal is to be able to add cache to an existing LV, we can currently only attach an existing cache pool to an LV or create cached LV (create the LV and the cache pool together).
This doesn't contain support for attaching (or detaching) the cache pool using an action, this is currentl being discussed in #1003
> LVM cache pool support

- blivet/deviceaction.py
With latest parted setting the parted filesystem property changes
the GPT type set by the flags to the default type for the fs, e.g.
to "Microsoft basic data" for FAT instead of "EFI System" which
is set with the boot flag on GPT.
> Set partition flags after setting parted filesystem (#2033875)

- tests/formats_test/loopbackedtestcase.py
On latest rawhide newly created partitions are not added when the
loop device is created without the partscan option.
Related: rhbz#2055708
> Create loop devices for tests with --partscan

- blivet/deviceaction.py
- tests/action_test.py
By default an action obsoletes all actions with the same type on
the same device. For configure actions this makes sense only if
the actions changes the same attribute.
> Make sure configure actions obsolete only actions with same attribute

- blivet/deviceaction.py
- tests/action_test.py
The action also must be marked as not applied which is what the
DeviceAction.cancel() call does for all actions.
> Correctly cancel configure actions in cancel()

- .packit.yaml
Fedora ELN builds are broken all the time because of repository
or GPG signatures issues, it doesn't make sense to have a test
that is broken all the time and outside of our control.
> Disable Fedora ELN builds in packit

- blivet/populator/helpers/disk.py
This happens when trying to use Blivet on a system with a BIOS
RAID without dmraid installed. Because we don't fully support
BIOS RAIDs using MD the MDBiosRaidDevicePopulator helper fails
to get kwargs for the BIOS RAID "disk" and populate fails.
----
This is just a workaround. We should aim to fully support DDF RAIDs with MD (some changes will be needed in libblockdev too see https://github.com/storaged-project/libblockdev/issues/722). Populator is also one the things we should focus when making Blivet more stable, returning `None` from `_get_kwargs` means we try to pass `**None` for the device constructor which crashes without even telling the user what's wrong.
> Do not crash when a disk populator doesn't return kwargs

- blivet/tasks/fslabeling.py
- blivet/tasks/fsuuid.py
These are class methods in the subclasses and pylint is now
complaining about this.
> Change label_format_ok and uuid_format_ok to class methods

- blivet/devices/lvm.py
- tests/devices_test/lvm_test.py
Without setting the LVMPhysicalVolume.vg_name argument to None
after removing the PV from its VG, the PV is still considered
active and cannot be removed.
Yet another issue discovered when working on https://github.com/linux-system-roles/storage/pull/264
> Correctly set vg_name after adding/removing a PV from a VG

- blivet/actionlist.py
The _find_active_devices_on_action_disks function originally
prevented from making any changes on disks with active devices
(active LVs, mounted partitions etc.)  This was changed in
b72e957d2b23444824316331ae21d1c594371e9c and the check currently
prevents only reformatting the disklabel on such disks which
should be already impossible on disks with an existing partition.
This change for the 3.4 stable branch keeps the current behaviour
where the active devices are teared down when running in installer
mode to avoid potential issues with the installer.
> Do not crash when changing disklabel on disks with active devices

- blivet/deviceaction.py
- tests/action_test.py
If we want to remove a PV from a VG and then remove the PV device,
the ActionDestroyDevice must not obsolete the ActionRemoveMember
action. Eventhough we are going to remove the device, we still
need to call "vgreduce" first.
> ActionDestroyDevice should not obsolete ActionRemoveMember

- blivet/devices/lvm.py
- examples/lvm_cache.py
- tests/devices_test/lvm_test.py
This adds support to attach an existing LV as a writecache to
another LV and to create a writecached LV.
Fixes: #1027 
This is a good candidate for more tests, especially something that will actually try to attach and detach the writecache LV so I'll wait for #1028 to be merged and add more tests later.
> Add support for attaching and creating LVM writecached LVs

- blivet/actionlist.py
The _find_active_devices_on_action_disks function originally
prevented from making any changes on disks with active devices
(active LVs, mounted partitions etc.) This was changed in
b72e957 and the check currently prevents only reformatting
the disklabel on such disks which should be already impossible
on disks with an existing partition.
The check currently also makes it impossible to add a new disk to
an existing VG -- the new disk has an active device (the VG) in
our storage model so creating a new partition table (even if it
didn't have one before) marks it as "problematic".
----
This is a less conservative version of #1037 removing the check completely. I mean, what could go wrong, right?
> Do not check for "problematic" disks in ActionList._pre_process

- blivet/devices/lvm.py
The member format size is 0 when target size is not set.
> Use LVM PV format current_size in LVMVolumeGroupDevice._remove

- blivet/errors.py
- blivet/nvme.py
This covers only the basic functionallity needed by Anaconda right
now: populating the config files in /etc/nvme and copying them to
the installed system. The API for the NVMe singleton is based on
the similar modules for iSCSI and FCoE.
Resolves: rhbz#2073008
> Add a very simple NVMe module

- blivet/devices/disk.py
- blivet/util.py
- blivet/zfcp.py
- tests/util_test.py
This change adds a support for [zFCP NPIV (N_Port ID virtualization)](https://www.ibm.com/docs/en/linux-on-systems?topic=later-n-port-id-virtualization) devices.
NPIV-enabled devices are activated just by using the device ID. The kernel module will detect the WWPNs and LUNs and bring all the devices up automatically. This means the user doesn't have to provide the WWPN and LUN IDs.
Related: rhbz#[1937030](https://bugzilla.redhat.com/show_bug.cgi?id=1937030)
TODO:
> Add support for NPIV-enabled zFCP devices

- blivet/util.py
- tests/formats_test/selinux_test.py
- tests/pylint/pylintrc
Latest pylint removed some deprecated warnings/messages and now
complains about disabling unknown messages.
> pylint: Remove deprecated pylint warnings from pylintrc and code

- .github/workflows/check.yml
We don't really need to run the checks (pylint, pycodestyle and translation-canary) in our CI, everything can run in the GH actions on Ubuntu without a problem. This uses our ansible playbook to install dependencies including pocketlint and latest pylint from pip so the action itself is actually really simple.
> ci: Run static analysis checks in GitHub actions

- blivet/events/manager.py
- tests/populator_test.py
- tests/pylint/runpylint.py
Pylint finally works with Python 3.11 on rawhide and shows some new warnings.
> Misc pylint fixes for rawhide

- blivet/devices/file.py
- blivet/devices/nfs.py
- blivet/devices/storage.py
- blivet/formats/fs.py
Latest pycodestyle is complaining about missing whitespace around
"not" which we were (at some places) using as a function instead
of keyword like "not(...)".
> Fix missing whitespaces around not keyword

- blivet/blivet.py
- blivet/devicefactory.py
Remove some leftover code that manipulates with collected installation roots.
These objects are part of Anaconda.
**Depends on:** https://github.com/rhinstaller/anaconda/pull/4271
> Remove the Blivet.roots attribute

- blivet/formats/fs.py
- tests/storage_tests/formats_test/fs_test.py
- tests/storage_tests/formats_test/fslabeling.py
- tests/storage_tests/formats_test/fsuuid.py
- tests/storage_tests/formats_test/labeling_test.py
- tests/storage_tests/formats_test/uuid_test.py
Starting with xfsprogs 5.19 minimal size for XFS is 300 MiB.
> Adjust to new XFS min size

- blivet/tasks/availability.py
The version sometimes can have an -rcX suffix we need to ignore.
> Fix regex for checking e2fsprogs version

- tests/storage_tests/devices_test/partition_test.py
These variables appear to have been copied over from the tests/unit_tests/devices_test/partition_test.py but are not used.
> tests: remove unused global variables

- tests/vmtests/README.rst
- tests/vmtests/runvmtests.py
I've struggled to figure out how to actually run the VM tests in blivet since there's no docs.
This series attempts to help in that respect by adding a tests/vmtests/README.rst file, whose content I inferred / reverse engineered from terse description in
```
commit aa9160875482debdf6eacc0cbfa6ca1906cf5cb1
Author: Vojtech Trefny <vtrefny@redhat.com>
Date:   Thu Aug 25 11:08:42 2016 +0200
Add a script to run tests in a virtual machine
This script will start the machine, make a snapshot of its initial
state and run the tests on it (reverting to the snashot after each
test). The VM must automatically boot to an live image with ssh
enabled.
```
With the steps I document, I was able to successfully run the VM tests. If there is a better way to achieve this, that the maintainers typically …
> Improve and document VM tests

- python-blivet.spec
We are not using the part, fs and kbd plugins in blivet. The s390 plugin is available only on s390x.
> spec: Fix recommended libblockdev plugins

- blivet/devices/btrfs.py
This is a workaround for RHEL where the btrfs plugin is not available and where we might still try to call some libblockdev functions to gather information about preexisting btrfs devices.
We should create a better and more generic solution for this problem (we might have similar issue with other potentially missing plugins or tools) but this should be good enough for now.
> Catch BlockDevNotImplementedError for btrfs plugin calls

- blivet/arch.py
T2 apple macs behave much more like normal `EFI` computers than the current use of `Mactel`. This PR will make T2 Apple Macs report as x86-64 EFI computers, which is probably the right behavior. This PR also adds the `is_t2mac()` function to arch.py for detecting T2 macs.
> Do not report as `Mactel` for Apple Macs with the T2 chip

- blivet/blivet.py
- blivet/deviceaction.py
- blivet/devicelibs/gpt.py
- blivet/devices/partition.py
- blivet/errors.py
- blivet/flags.py
- blivet/formats/disklabel.py
- examples/partitioning.py
- tests/storage_tests/devices_test/partition_test.py
- tests/unit_tests/devices_test/device_methods_test.py
- tests/unit_tests/gpt_test.py
- tests/vmtests/gpt_test.py
- tests/vmtests/runvmtests.py
The discoverable partitions specification defines a way to identify partitions used for various well known mount points:
https://uapi-group.org/specifications/specs/discoverable_partitions_specification/
This relies on setting well known GPT partition GUIDs, instead of parted's generic "Linux Data"  GUID which more or less everything gets set to today (swap being a notable exception).
My goal is to make it possible for applications like Anaconda to "do the right thing(tm)" with little to no effort when doing disk partitioning. This series aims to make that possible, while still retaining the current behaviour by default for the sake of backwards compatibility.
With this series, a simple app usage might not need anything more than to opt-in to discoverable partitions with:
```
from …
```
> Support configuring partition type UUIDs for GPT partition auto-discovery

- blivet/arch.py
- blivet/devices/md.py
- blivet/udev.py
- blivet/util.py
Python's garbage collector should close these automatically, but we shouldn't depend on that and close the file descriptor when no longer needed.
> Make sure we close the streams when reading a file

- tests/README.rst
- tests/unit_tests/__init__.py
- tests/unit_tests/action_test.py
- tests/unit_tests/blivettestcase.py
Having two storagetestcase classes and module could be confusing
and these are unit tests that don't really touch any storage.
> Rename unit_tests.storagetestcase to unit_tests.blivettestcase 

- blivet/arch.py
`/sys/class/dmi/id/product_name` works on more model/firmware combinations than DMI `product_id`. Apple's firmware always sets `product_name`, but only sometimes sets `product_id`, so the t2 detection will work on more macs with this change.
> Use DMI product_name for t2 mac detection.

- tests/unit_tests/devices_test/stratis_test.py
In unit tests we don't want to actually use the stratis tools to check for metadata size, we just need to be sure our internal calculation works.
> tests: Patch checking stratis pool metadata size

- blivet/tasks/availability.py
Should've been removed together with the dmraid support.
> Remove unused BLOCKDEV_DM_RAID technology from tasks

- doc/index.rst
Without a link the documentation is not accessible.
> doc: Link to the LVM VDO documentation from the index page

- blivet/actionlist.py
If we don't have a parted disk instance here, we should just ignore it some of the devices we are trying to update here are not even used.
> Ignore missing parted disk in ActionList._post_process (#2102960)

- Makefile
- python-blivet.spec
- setup.py
Python 2 EOL was 3 years ago so we can stop supporting it now.
I'd like to do a bigger cleanup in the future (like removing the `six` module), but for now we can just remove Python 2 from the build and release process.
> Remove support for Python 2 from spec and Makefile

- tests/pylint/pylintrc
Latest pylint changed the required format of this section and we want the default configuration for this anyway.
> pylint: Remove the "EXCEPTIONS" section from pylintrc

- blivet/devices/btrfs.py
- blivet/devices/lvm.py
- blivet/devices/partition.py
This is intended to replace #1110, we have a lot more pykickstart attributes that are wrong that just the `on_part`/`onPart` one.
> Kickstart data fixes

- blivet/util.py
Iterate over lines of the `/proc/mounts` file instead of characters of the first line.
This bug was introduced in the commit 12ba6cb.
> Fix the get_mount_device function

- blivet/devices/dm.py
We now have multiple use cases that require using UUID in fstab for all devices so we should remove the exception for LVM and other DM devices.
> Prefer UUID for fstab spec for DM devices too

- blivet/devices/btrfs.py
- blivet/devices/dm.py
- blivet/devices/loop.py
- blivet/devices/lvm.py
- blivet/devices/md.py
- blivet/errors.py
- blivet/formats/luks.py
- blivet/formats/lvmpv.py
- blivet/formats/mdraid.py
- blivet/formats/swap.py
We shouldn't force our users to import libblockdev just to be able to catch storage exceptions. This commit makes sure all libblockdev calls are protected with try-except and we raise our own exceptions like StorageError.
Fixes: #1014
> Avoid raising libblockdev exceptions from our code

- .packit.yaml
We need to set the sources manually (Packit doesn't support multiple sources) and we also need to merge the release branch to get the correct version.
> ci: Fix Packit configuration

- blivet/dbus/blivet.py
The device_added/device_removed/format_added/format_removed callbacks are for changes to blivet's model -- not when changes are written to disk.
> DBus: remove extra callback invocations

- tests/skip.yml
This reverts commit 16b90071145d2d0f19a38f3003561a0cc9d6e281.
The kernel issue was resolved, we no longer need to skip the test.
> Revert "tests: Skip test_lvcreate_type on CentOS/RHEL 9"

- blivet/devicelibs/crypto.py
- blivet/formats/luks.py
- tests/unit_tests/formats_tests/luks_test.py
- tests/unit_tests/formats_tests/methods_test.py
With FIPS enabled LUKS uses pbkdf and not argon so the memory limit is not a valid parameter.
> Do not set memory limit for LUKS2 when running in FIPS mode

- blivet/devicelibs/crypto.py
- blivet/formats/luks.py
- tests/unit_tests/formats_tests/luks_test.py
For disks with mixed sector size (4096 physical and 512 logical) we were wrongly adding the sector_size extra option which is not supported on LUKS1 only LUKS2.
> Fix creating LUKS1 on disks with mixed sector size (#2188785)

- blivet/iscsi.py
The downstream libiscsi uses MD5 as the only default CHAP auth algorithm. With MD5 not available in FIPS mode, this leaves an empty set of algorithms available.
---
This is completely untested, just a thought. Needs https://github.com/storaged-project/udisks/pull/1098 otherwise it's likely a no-op.
From `/etc/iscsi/iscsid.conf`:
```
```
For some reason these defaults are not honoured by the downstream `libiscsi` (subject to rewrite in the future).
> iscsi: Extend allowed CHAP auth algorithms

- blivet/formats/disklabel.py
- tests/storage_tests/devices_test/partition_test.py
- tests/unit_tests/formats_tests/disklabel_test.py
See: https://bugzilla.redhat.com/show_bug.cgi?id=2092091#c6 There was a Fedora 37 Change to prefer GPT disk labels on x86_64 BIOS installs, but for some reason, this was implemented in anaconda by having it ignore blivet's ordering of the disk label types and just universally prefer GPT if it's in the list at all, which resulted in a preference for GPT in more cases than just x86_64 BIOS. This is one step towards fixing that, by putting the 'always prefer GPT on x86_64' logic here in the blivet ordering code where it belongs. Step 2 will be to drop the anaconda code that overrides blivet's preference order.
This also simplifies the logic a bit; it had gotten rather a lot of conditions piled on top of each other and was rather hard to read. This should achieve the same effect as before in …
> Always prefer GPT disk labels on x86_64 (and clean up the logic)

- blivet/tasks/fsmkfs.py
* With the default I was running out of inodes, disk reported no additional space after only using about 20%.
> blivet: Enable the extended node bitmap for F2FS

- blivet/devices/stratis.py
- blivet/formats/luks.py
- blivet/formats/stratis.py
We don't want to return 'None' here.
Related: https://github.com/rhinstaller/anaconda/pull/4873
> Make sure that LUKS.has_key always returns a boolean value

- blivet/iscsi.py
- misc/install-test-dependencies.yml
- tests/storage_tests/__init__.py
- tests/storage_tests/iscsi_test.py
- tests/storage_tests/storagetestcase.py
Backport of https://github.com/storaged-project/blivet/pull/1112 https://github.com/storaged-project/blivet/pull/1144 and https://github.com/storaged-project/blivet/pull/1145
> Backport iSCSI initiator name related fixes to RHEL 8

- blivet/__init__.py
- blivet/devices/lvm.py
- blivet/formats/lvmpv.py
- blivet/tasks/availability.py
- tests/unit_tests/devices_test/lvm_test.py
This feature is requested by GFS2 for the storage role. This adds support for creating shared VGs and activating LVs in shared mode.
> Add support for creating shared LVM setups

- blivet/devices/disk.py
The '95nvmf' dracut module needs a couple more packages for the NBFT (NVMe over TCP) to work - such as networking. Local PCIe NVMe devices have no special needs.
> nvme: Require additional rpms for dracut

- blivet/devicelibs/lvm.py
This was changed to always enabled by accident in #972.
Fixes: #1155
> Enable LVM logging only in debug mode

- tests/pylint/censorship.py
- tests/run_tests.py
The 'do_exit' keyword argument has been deprecated for a while and finally removed in pylinr 3.0.
> pylint: Use 'exit' instead of 'do_exit' for pylint.lint.Run

- blivet/devicetree.py
Btrfs Volumes use label of the filesystem as name in blivet, which isn't really a name, so it doesn't have to be unique, but not having it unique causes problems in both Blivet and Anaconda where we assume device name is a unique identifier. Not having the name in the list of names means newly created devices can get the same name as an already existing (or scheduled to be created) device.
-----------
@dwlehman btrfs volumes were explicitly excluded even before https://github.com/storaged-project/blivet/pull/688 Do you know about any issues adding btrfs volumes names to the list could cause? We are currently having two bugs reported related to this and the new Anaconda WebUI: https://bugzilla.redhat.com/show_bug.cgi?id=2237375 and https://bugzilla.redhat.com/show_bug.cgi?id=2237375
> Include btrfs volumes names/labels in DeviceTreeBase.names

- blivet/devices/disk.py
- blivet/devices/dm.py
- tests/unit_tests/devices_test/lvm_test.py
`DMDevice` now depends on `kpartx` which means all DM devices (LUKS, LVM etc.) depend on `kpartx` which is really needed only for multipath. This PR moves the dependency to multipath and also allows avoids unnecessary exceptions when `kpartx` is not available.
> Fix DMDevice hard dependency on kpartx

- .github/workflows/anaconda_tests.yml
- blivet/actionlist.py
- blivet/blivet.py
- blivet/formats/fs.py
- blivet/fstab.py
- misc/files/libmount_deb.py
- misc/install-test-dependencies.yml
- python-blivet.spec
- tests/pylint/runpylint.py
- tests/storage_tests/fstab_test.py
- tests/unit_tests/fstab_test.py
- added support for blivet to directly modify fstab based on blivet actions
- added tests
> Fstab support (rebased to 3.9)

- blivet/actionlist.py
- blivet/formats/swap.py
- blivet/fstab.py
- tests/storage_tests/fstab_test.py
Anaconda tests revealed missing `FSTabOptions` object in `SwapSpace` class.
This issue is related to the recent merge of fstab rework #1119 which
added this object to `FS` class. `SwapSpace` does not inherit from `FS` and
was overlooked. This change adds the missing object.
It also adds logic that skips all fstab related operations if fstab file
is not to be written (i.e. `fstab.dest_file is None`). The reason for this is to
eliminate the risk of potential issues caused by unused component.
The test for above has been added as well.
>  Added missing fstab object to SwapSpace

- blivet/tasks/fsmkfs.py
- tests/storage_tests/formats_test/fs_test.py
Resolves: https://github.com/rhinstaller/kickstart-tests/issues/1028
> Fix passing extra mkfs arguments to libblockdev

- .packit.yaml
- python-blivet.spec
We want a high release number (99) for the daily builds done by Packit to make sure the Copr daily builds are always newer than the version in Fedora. We can do this in Packit config instead of bumping the release in the spec everytime.
> ci: Set custom release number for Packit

- blivet/devices/partition.py
- tests/unit_tests/devices_test/partition_test.py
Anaconda needs to be able to create hybrid boot disks. For example:
```
clearpart --all --initlabel --disklabel=gpt
part prepboot  --size=4    --fstype=prepboot
part biosboot  --size=1    --fstype=biosboot
part /boot/efi --size=100  --fstype=efi
part /boot     --size=1000 --fstype=ext4 --label=boot
part /         --grow      --fstype xfs
```
However, this kickstart snippet is not working with two or more disks. The bootloader-related partitions should be all created on the disk the computer will boot from, but Blivet does that only for platform -specific partitions. The rest of them are created on any disk with enough space.
It looks like this can be easily fixed by setting the same weight to all of these partitions regardless of the current platform.
See: …
> Support partitioning of hybrid boot disks

- blivet/devices/btrfs.py
- tests/storage_tests/devices_test/btrfs_test.py
- tests/unit_tests/devices_test/__init__.py
- tests/unit_tests/devices_test/btrfs_test.py
- tests/unit_tests/devices_test/device_properties_test.py
We want to have a predictable UUID when creating btrfs volumes so
we can have a unique identifier that is same for the volume before
and after it is created.
> Generate UUID for newly created btrfs volumes

- tests/unit_tests/__init__.py
- tests/unit_tests/nvme_test.py
Just a simple heavily mocked test case, but it should prevent issues like the one currently blocking https://github.com/rhinstaller/anaconda/pull/5357
> tests: Add a simple unit test for the NVMe module

- blivet/devices/disk.py
- blivet/populator/helpers/disk.py
- tests/unit_tests/tags_test.py
so anaconda can use it to display path_id information for multipath members
**Note**:
It would be nice to get this into RHEL9.x as well, but I'm not sure which branch I should base my PR according to CONTRIBUTING ("oldest ``x.y`` release that should include
your work"). So for starters I tried to use the latest branch for upstreaming.
@jstodola @poncovka @sharkcz
> add udev-builtin-path_id property to zfcp-attached SCSI disks

- tests/storage_tests/devices_test/md_test.py
Attempt to fix the randomly failing MD tests on CentOS 9.
> tests: Wait for array resync in MD tests

- blivet/blivet.py
- blivet/devices/btrfs.py
- blivet/devices/device.py
- blivet/devices/dm.py
- blivet/devices/luks.py
- blivet/devices/lvm.py
- blivet/devices/md.py
- blivet/devices/stratis.py
- blivet/devicetree.py
- blivet/populator/helpers/luks.py
- blivet/populator/helpers/lvm.py
- blivet/populator/helpers/mdraid.py
- blivet/populator/helpers/partition.py
- blivet/populator/populator.py
- tests/storage_tests/devices_test/misc_test.py
- tests/unit_tests/devices_test/btrfs_test.py
- tests/unit_tests/devices_test/lvm_test.py
- tests/unit_tests/devices_test/md_test.py
- tests/unit_tests/devices_test/partition_test.py
- tests/unit_tests/devices_test/stratis_test.py
- tests/unit_tests/devicetree_test.py
- tests/unit_tests/populator_test.py
The new `device_id` identifier is meant to be unique even for devices with the same name. The primary user for this will be Anaconda which needs an ID that will be a unique string stable between `reset()` calls.
The device ID looks as follows:
- `name` for disks, partitions and loop devices
- `LVM-<name>` for LVM VGs and LVs
- `BTRFS-<uuid>-<name>` for btrfs volumes and subvolumes
- `STRATIS-<name>` for Stratis devices
- `LUKS-<name>` for LUKS mapped devices
- `MDRAID-<name>` for MD arrays
- `DM-<name>` for generic DM devices
Btrfs is currently the only device type that allows duplicate names for volumes so UUID is used for btrfs volumes. For other devices (LVM, MD...) the device name must be unique so we can use the name with technology prefix.
> Add a unique device identifier

- blivet/devicelibs/btrfs.py
- blivet/formats/fs.py
- tests/storage_tests/devices_test/btrfs_test.py
- tests/storage_tests/formats_test/fs_test.py
This will be used by Anaconda to determine whether a given filesystem can be used for / without reformating.
> Add a new function to check if a filesystem is empty

- blivet/devices/lvm.py
The segtype is "cache-pool", not "cache_pool".
> Fix checking for segment type for cache pools

- blivet/populator/helpers/mdraid.py
When we don't have the array name we cannot construct device ID for the devicetree lookup, we need to let the code fallback to other means like UUID.
> Fix crash when scanning degraded/not fully assembled MD arrays

- blivet/populator/helpers/mdraid.py
We want to be able to gather information about the array including size and filesystem type on it which is possible only when the array is active. By default this is disabled, auto_dev_updates flag needs to be set to enable this behaviour.
> Try to assemble MD arrays during populate (#2236356)

- blivet/devices/btrfs.py
When looking for a mountpoint we're trying to compare device name with the device node base name which doesn't work for DM devices like LUKS (we're trying to compare "dm-0" to "luks-..."), we need to make sure to resolve the name first.
> Fix getting subvolumes for mounted btrfs volumes

- blivet/actionlist.py
- blivet/blivet.py
- blivet/fstab.py
- tests/storage_tests/fstab_test.py
Formats with multiple layers (e.g. LUKS) were not handled properly in fstab. This resulted in fstab entries not being properly cleaned from fstab when destroy actions were executed. This fixes the issue by using different variables with correct values based on action type.
> Fstab cleanup fix

- blivet/tasks/availability.py
- tests/run_tests.py
If we can't get the information from DBus, we should try the
/etc/os-release file.
> tests: Try to get distro and version from /etc/os-release

- blivet/formats/fs.py
There are some changes planned in libblockdev that will affect how subvolumes are listed so we need to adjust our check to work with both the old and new version of libblockdev.
> Adjust check for btrfs filesystem being empty

- blivet/devices/stratis.py
- tests/unit_tests/devices_test/stratis_test.py
We do allow creating Stratis FS without specifying its size which simply means creating the default 1 TiB filesystem.
> Fix creating Stratis filesystem without size specified

- blivet/devices/partition.py
We want to print the human-readable string if possible, not the binary data.
> Fix printing the partition type UUID

- blivet/nvme.py
This is similar to other modules like iSCSI where these methods are silently skipped if the technology isn't supported or available.
> nvme: Skip startup/write when NVMe plugin isn't available

- blivet/devicelibs/btrfs.py
If we don't have libblockdev btrfs plugin we cannot check if the btrfs filesystem is empty.
> Do not raise not implemented exception when checking if btrfs is empty

- blivet/fstab.py
- tests/unit_tests/fstab_test.py
FOr some formats the 'type' value is not valid for mounting/fstab, for example for Stratis devices we internally use 'stratis xfs' but we need to use 'xfs' for mounting and fstab.
> fstab: Use 'mount_type' when writing filesystem type to fstab

- blivet/devices/lvm.py
- blivet/devices/stratis.py
- blivet/errors.py
- tests/unit_tests/devices_test/lvm_test.py
- tests/unit_tests/devices_test/stratis_test.py
Just failing with an early exception, same as for LVM VGs.
> Do not allow creating stratis pools with different sector sizes

- blivet/populator/helpers/disk.py
> Ignore invalid/empty UUIDs for NVMe namespaces

- blivet/devicelibs/stratis.py
Without this we won't get any error message when the call fails.
> Make sure to include stderr when gathering output of stratis tools

- blivet/devices/stratis.py
- tests/unit_tests/devices_test/stratis_test.py
Stratis requires sizes to be rounded for the filesystems.
> Round Stratis Filesystem size down to the nearest sector

- blivet/formats/__init__.py
- blivet/formats/lvmpv.py
- blivet/tasks/pvtask.py
- tests/storage_tests/formats_test/lvmpv_test.py
Storage role requires support for a case when PV has to be resized to fill all available space when its device's size changes (usually on VM).
A new flag `grow_to_fill` was added, which marks the device for size expansion (all available space it taken).
Proper size is determined by LVM, avoiding inaccurate size calculations in blivet.
> Added support for PV grow

- misc/install-test-dependencies.yml
- tests/storage_tests/devices_test/stratis_test.py
To avoid re-running all the test cases from StratisTestCase in StratisTestCaseClevis.
> tests: Add a base class for stratis tests

- blivet/devicelibs/stratis.py
- blivet/devicetree.py
- blivet/formats/luks.py
- blivet/tasks/availability.py
- blivet/udev.py
- tests/pylint/runpylint.py
- tests/run_tests.py
The latest pylint introduced a new warning for values possibly used before assignment.
> Fix pylint 'possibly-used-before-assignment' warnings

- blivet/devicelibs/mdraid.py
The md-linear kernel module is deprecated and will be removed in the future.
> Remove support for the MD linear RAID level

- blivet/__init__.py
Default log level is WARNING and we want to log even INFO messages for libblockdev. INFO level contains for example also all commands and their output that we want to log to program.log.
> Set log level to INFO for libblockdev

- blivet/tasks/fsmkfs.py
We stopped adding the force option when switching to libblockdev in fa3add214ba8edf1965bc851b85f2f2a6a3ea107. This was not intentional and the missing force option is already causing issues when running mkfs.xfs on misaligned devices.
Related: RHEL-39384
> Run mkfs.xfs with the force (-f) option by default

- tests/storage_tests/formats_test/fs_test.py
The test randomly fails to find the newly created partition so lets try waiting a bit with udev settle.
> tests: Try waiting after partition creation for XFS resize test

- tests/skip.yml
We added new test cases that also need to be skipped.
> Fix skipping MD tests on CentOS 9

- tests/unit_tests/formats_tests/selinux_test.py
This is a unit test so it shouldn't try to create directories anywhere.
> tests: Make sure selinux_test doesn't try to create mountpoints

- blivet/tasks/availability.py
- blivet/tasks/fsminsize.py
- python-blivet.spec
This was not part of #1163 because libblockdev originally didn't support getting filesystem min size using the resize tools. We now have the required version of libblockdev available everywhere so we can switch the fsminsize task to the FS plugin too.
> Use libblockdev FS plugin for fsminsize

- blivet/devicetree.py
- tests/unit_tests/devicetree_test.py
This will allow easier filtering for Anaconda when using the device IDs as unique device identifiers.
> Make sure ignored and exclusive disks work with device IDs too

- blivet/devicetree.py
- tests/unit_tests/devicetree_test.py
This identifier should be handled as well. It's met in debian fstab.
> devicetree: resolve devices also with the PARTUUID=.. naming

- blivet/devices/partition.py
It's possible for the pyparted partition's `type_uuid` to be None in several ways: see all the NULL returns in
https://github.com/dcantrell/pyparted/blob/d5870bb7a5d512c17c92a4e4fe7e9a8e7c8c3528/src/pydisk.c#L1481 In the specific case we hit, anaconda since 41.26 will try to get the `part_type_uuid` of a partition on an msdos-labeled disk when looking for Windows installations; as msdos-labeled disks do not support partition type UUIDs, pyparted's call to
ped_partition_get_type_uuid gets a "msdos disk labels do not support partition type-uuids" error from parted and returns NULL, so pyparted tries to forward that error somehow then return NULL itself (though the error gets swallowed somewhere along the line, I had to patch pyparted to find out what was going on).
That means we try to do …
> part_type_uuid: guard against pyparted type_uuid being None

- blivet/blivet.py
- blivet/devicefactory.py
- blivet/devicelibs/crypto.py
- blivet/devices/luks.py
- blivet/devices/storage.py
- blivet/formats/luks.py
- tests/unit_tests/devices_test/device_size_test.py
- tests/unit_tests/formats_tests/luks_test.py
When creating or resizing LUKS 2 devices we need to take the bigger metadata into account (16 MiB for LUKS2 but just 2 MiB for LUKS1).
> Use correct LUKS metadata size for LUKS 2

- blivet/fstab.py
- tests/unit_tests/fstab_test.py
Blivet fstab methods `get_device()` and `find_device()` took `Blivet` object as a first parameter. However, for anaconda (primary customer for the blivet change) usecase the `Blivet` object does not always exist, only the `Devicetree`. Mentioned methods do not need anything else besides `Devicetree` from blivet object.
This changes those methods interfaces to accept `Devicetree` instead of `Blivet` as the first parameter.
Unit tests modified accordingly.
Storage role should not be affected by this change.
> blivet fstab method change

- blivet/devicelibs/crypto.py
- blivet/devices/storage.py
- blivet/formats/__init__.py
- blivet/formats/luks.py
- blivet/populator/helpers/luks.py
- plans/blivet-gui.fmf
- plans/tests.fmf
- tests/unit_tests/formats_tests/luks_test.py
Work in progress support for creating and managing OPAL self encrypting drives with LUKS. This for now contains only support for recognizing pre-existing LUKS HW-OPAL devices, because this doesn't require any additional support from libblockdev (which creating and removing these devices will require).
> LUKS HW-OPAL support

- blivet/populator/helpers/luks.py
Accidentally removed in 319e6a6ede8f9468f56458ed8d14110536cf88d8
> Fix getting LUKS subsystem for existing LUKS formats

- blivet/udev.py
crashed with DiskDevice get members property
trace: 'DiskDevice' object has no attribute 'members'
changed: when ID_FS_TYPE is isw_raid_member use SYS_NAME to device name
issue: https://github.com/storaged-project/blivet/issues/1270
> Fix intel biosraid can't get device name causing crashed

- .github/workflows/check.yml
'main' is the only development branch now, see #1274
> ci: Update branches in GitHub actions

- blivet/__init__.py
- blivet/devices/partition.py
- python-blivet.spec
- tests/storage_tests/devices_test/lvm_test.py
Unfortunately parted doesn't have the human readable strings so if we don't want to simply copy the table from libfdisk, we need to start using libblockdev part plugin to get it.
Fixes: #1258
> Add partition type human-readable string to PartitionDevice

- blivet/util.py
This was originally designed to gather data for the EDD tests but we are not using this and with Anaconda now merging all storage logs to one file this makes the storage.log harder to read and doesn't bring any useful human readable information.
> Disable the "testdata" logging

- misc/install-test-dependencies.yml
Everything except coverage and pycodestyle is available in the repositories and we can install these two from pypi.
> misc: Add support for installing dependencies on CentOS 1O Stream

- tests/unit_tests/devicefactory_test.py
Stratis changes its metadata and the way "stratis-predict-usage" predicts its size so we need to change our expectations too.
> tests: Change expected Stratis metadata size for stratisd 3.7.0

- .github/workflows/anaconda_tests.yml
- .github/workflows/check-rhel.yml
- .packit.yaml
- plans/tests-rhel.fmf
- plans/tests.fmf
The idea is to have the same configuration both here and on the rhel10-branch (with only the appropriate tests for the branch running) so we can do rebases on the rhel10-branch without losing the RHEL-specific configuration.
See #1283 for more details.
> RHEL 10 branch CI -- sync with the main branch

- python-blivet.spec
Marking as draft for now because 3.2.0 is not released yet.
> spec: Bump required version of libblockdev to 3.2.0

- blivet/tasks/fsminsize.py
Follow up for #1255. We need to raise FSError in case of errors because libblockdev errors are not caught in FS.update_size_info.
> Do not raise libblockdev errors in FSMinSize tasks (#2314637)

- blivet/populator/helpers/partition.py
If we don't have the parted disk object we cannot really construct a working PartitionDevice so adding partitions on these disks usually end with an exception. This change should make blivet a little bit more resilient in those situations.
> Ignore partitions on disks without parted disk

- blivet/formats/fs.py
We have a problem with Fedora aarch64 KDE disk images ATM. We want to make them 16 power-of-ten gigabytes big, so they will fit on "16GB" SD cards / USB sticks. When we set them to this size, compose fails because the anaconda free space check fails, saying "An additional 436 MiB is needed". That check is ultimately backed by this estimate.
In these images, the main system partition is a btrfs volume, with compression enabled. If you examine the last successful image (which was built at size 18 power-of-two GB), thanks to compression, only ~5GB of space is actually occupied on that volume. The contents would easily fit if it were slightly smaller.
With this change we adjust the free space estimate by a compression factor, as well as a metadata factor, if the class defines one. For the …
> free_space_estimate: adjust for compression on btrfs

- python-blivet.spec
We are a noarch package so we cannot have architecture-specific dependencies. "Recommends" ignores missing packages so we can ignore that libblockdev-s390 is available only on s390x.
> spec: Fix dependency on libblockdev-s390

- tests/vmtests/gpt_test.py
We don't want to set logging when skipping the test case so it cannot be defined on the module level.
> tests: Do not set logging when loading gpt_test

- blivet/devices/disk.py
- blivet/populator/helpers/disk.py
- blivet/zfcp.py
- python-blivet.spec
#1162 rebased to the latest 3.10-devel
> consolidated s390 device configuration

- tests/storage_tests/devices_test/stratis_test.py
FIPS requires at least 8 chars long passphrase. Dummy passphrase used in stratis test was too short causing encryption
tests with FIPS enabled to fail.
Changed passphrase.
fixes RHEL-45173, RHEL-8029
> Modified passphrase in stratis test

- scripts/makeupdates
We no longer create tags with the -1 release so the script needs to be adjusted, see c1d2eee02f390c014a121a5e86481b9ed31c070b
> Fix looking for the latests tag in makeupdates script

- blivet/devices/luks.py
- blivet/devices/lvm.py
- blivet/devices/storage.py
Growable LVs usually start at minimum size so adjusting it down
can change the size below allowed minimum.
> Align sizes up for growable LVs

- blivet/devices/disk.py
The vendor information used to come from parted which reports virtio blk devices as 'Virtio Block Device'. The sysfs vendor entry has always been 0x1af4 which isn't very descriptive. So in disk.description check for the exception and return "Virtio Block Device". disk.vendor is left as-is, only the user friendly description is modified.
Resolves: rhbz#1242117
> Translate vendor id 0x1af4 to Virtio Block Device (#1242117)

- blivet/devicelibs/lvm.py
The check for LVM devices support is executed on import so we need to catch the BlockDevNotImplementedError exception as well, otherwise blivet will crash even without calling any LVM related code.
> Do not crash when libblockdev LVM plugin is not available

- blivet/formats/disklabel.py
- tests/unit_tests/formats_tests/disklabel_test.py
Exceptions are DASD drives on s390 and 32bit ARM. Everywhere else GPT will be default.
> Make GPT default label type on all architectures

- blivet/populator/populator.py
There is no reason to crash if we fail to set this. It might cause some issues when working when multipath devices, but we should be able to continue in general.
> Ignore errors when setting multipath friendly names

- blivet/devices/disk.py
Anaconda relies on disks using name as device ID because it needs to be able to process the disks from kickstart without using blivet. For this use case multipath devices are basically disks so we should just use name here as well.
> Use just name as device ID for multipath devices (#2327619)

- .github/workflows/anaconda_tests.yml
Anaconda renamed their default branch.
> ci: Change branch for Anaconda tests from 'master' to 'main'

- blivet/devices/md.py
These are treated as disks so we should use just the name, the same way we do for disks. The names of the BIOS arrays are unique enought to hopefuly not cause any issues.
> Use name as device ID for BIOS RAID arrays (#2335009)

- blivet/udev.py
We've seen online UnicodeDecodeErrors from pyudev, but let's just catch all exceptions here and try to process the device anyway.
Fixes: #1330
> Protect against exceptions when getting properties from udev

- blivet/formats/lvmpv.py
- tests/unit_tests/formats_tests/lvmpv_test.py
When the file doesn't exists the 'lvmdevices --deldev' call will fail but it will still create the devices file. This means we now have an empty devices file and all subsequent LVM calls will fail.
Resolves: rhbz#2283014
> Do not remove PVs from devices file if disabled or doesn't exists

- blivet/devices/lvm.py
- blivet/formats/lvmpv.py
- blivet/populator/helpers/lvm.py
- blivet/tasks/pvtask.py
- tests/storage_tests/devices_test/lvm_test.py
- tests/unit_tests/populator_test.py
This makes the LVM code to check the actual LVM PV format size instead of assuming it's always the same size as the underlying block device.
Fixes: #1320
> LVMPV format size

- blivet/errors.py
- blivet/formats/luks.py
- blivet/populator/helpers/__init__.py
- blivet/populator/helpers/luks.py
- blivet/tasks/availability.py
> Fix BitLocker format status and allow closing active BITLK devices

- blivet/partitioning.py
The generic 'Unable to allocate requested partition scheme' is not very helpful, we should try to include additional information if possible.
> Include additional information in PartitioningError

- blivet/devicelibs/mdraid.py
This reverts commit a21c4fa61f75f6c900f152651308ac9b457a62da.
The removal of the kernel module was reverted and apparently a lot of people use it.
> Revert "Remove support for the MD linear RAID level"

- blivet/devicelibs/lvm.py
- blivet/devices/lvm.py
- tests/unit_tests/devices_test/device_methods_test.py
lvmetad is no longer used so we need to check LVM config for the auto-activation support.
> lvm: Check lvm.conf for auto-activation support

- blivet/formats/fs.py
- blivet/tasks/fssync.py
Originally we had to run the sync operation in chroot so we needed to remove the chroot prefix from the mountpoint, but we switched to using the ioctl calls directly which don't run in chroot so we need to use the "full" mountpoint (including the chroot prefix) now.
> Fix running filesystem sync in installation environment

- blivet/formats/luks.py
- tests/unit_tests/formats_tests/luks_test.py
We are currently using the "allow-discards" in /etc/crypttab to set the discards/fstrim feature for LUKS, but that doesn't work for Fedora Silverblue so we need to set the persistent flag in the LUKS header instead.
Resolves: RHEL-82884
> Set persitent allow-discards flag for newly created LUKS devices

- blivet/util.py
Make sure we are not adding "-o ''" to the mount call
> Fix calling mount without options

- blivet/formats/fs.py
These temporary mount operations are to gather information about the filesystem, we don't need read-write mount for these so lets be a bit safer and do a read-only mount.
> Make FS temporary mounts read-only

- blivet/udev.py
Another attempt to make blivet.reset() more stable and not crash when encountering broken devices. This is triggered by lingering MD device after removing it's parent devices. The MD device itself will be "broken" and unusable in blivet, but at least the reset/ populate call won't end with an error.
> Fix handling devices with "no" parents in udev

- blivet/devices/storage.py
- blivet/devicetree.py
- blivet/formats/__init__.py
- blivet/formats/disklabel.py
- tests/storage_tests/devices_test/md_test.py
Parted caches information about about devices internally. The cache is based on device name so when recreating a device using the same name but different size (e.g. when removing RAID0 array and creating RAID1 array with the same name) the cached information, including device size, is used by parted. This means that during next reset() call parted will think the device is bigger and tries to fix the partition table on the array breaking it instead.
Resolves: rhbz#2357214
> Drop parted device cache during reset v2

- blivet/populator/helpers/luks.py
- blivet/populator/helpers/lvm.py
We are no longer raising libblockdev exceptions in our public API calls (see #1014) so when calling setup() ourselves we need to catch our exceptions instead of libblockdev ones as well.
Resolves: rhbz#2362743
> Fix expected exception type when activating devices in populor

- blivet/tasks/fssize.py
- blivet/udev.py
We cannot use ID_FS_SIZE, for some filesystems (like XFS) this doesn't include the filesystem metadata.
See also https://github.com/storaged-project/udisks/pull/1115
> Fix getting filesystem size from udev

- blivet/blivet.py
- blivet/deviceaction.py
- blivet/devicetree.py
- tests/storage_tests/devices_test/lvm_test.py
- tests/unit_tests/devices_test/lvm_test.py
We are always trying to wipe format from devices we are going to remove, this causes issues when we for example cannot activate or assemble the device (broken thinpools, missing kernel modules...). In these cases we can ignore the failed format destroy action -- the device is going to be removed anyway so failing to remove the format is not a critical error.
> Make ActionDestroyFormat optional when the device is also scheduled to be removed

- blivet/devicetree.py
This just runs wipefs on empty devices needlessly. destroy_device already has the same check to skip adding the format destroy action on devices without formats.
> Do not try to destroy "None" formats in recursive_remove

- blivet/tasks/availability.py
Hotfix for rhbz#2371256. Technologies in libblockdev are defined as enums and we are using 'value_name' to get the technology name/ description in blivet. For some unknown reason the 'value_name' attribute from GLib.GEnumValue is not available with Python 3.14. This needs to be investigated more thoroughly, but for now we can just not include this information.
Resolves: rhbz#2371256
> Fix getting missing libblockdev technologies with Python 3.14
