storaged-project/blivet

blivet/devicetree.py

F22 1208536

---

tests/formats_test/selinux_test.py
tests/partitioning_test.py
tests/pylint/pointless-override.py

Trivial Test Fixes

---

blivet/formats/__init__.py
blivet/formats/disklabel.py
blivet/formats/fs.py
blivet/formats/luks.py
blivet/formats/lvmpv.py
blivet/formats/mdraid.py
blivet/formats/prepboot.py
blivet/formats/swap.py

This is the same model used within the device classes, which has worked pretty well.

Consolidate common code in DeviceFormat class methods.

---

blivet/formats/fs.py

Should have gone in with commit 10bc41e6f73796298a3a78faaf69dd363429ea53.

In FS._postSetup() check the mountpoint options that were actually used.

---

blivet/__init__.py

Resolves: rhbz#1139222
Previously, if a device had a child that was a LUKS device that child was
ignored when generating ksdata. What this meant was that that device's
format, which was luks, was used in generating the kickstart data.
Now, the LUKSDevice, which contains the format that should appear in the ks
output is used. This means that the LUKS format is used to set some ks data,
but the mountpoint and so forth are overwritten with the correct values
when the format on the LUKSDevice is used to populate those values.
The --passphrase option with passphrase continues to not appear in the
output anaconda-ks.cfg file.

Include LUKSDevice information in kickstart data (#1139222)

---

blivet/callbacks.py
blivet/deviceaction.py

Add a simple callback for all actions to report progress when running blivet.doIt() in blivet-gui

Add progress report callback for action processing

---

tests/action_test.py
tests/formats_test/labeling_test.py
tests/loopbackedtestcase.py

Some Test Fixes

---

blivet/devicelibs/btrfs.py
blivet/devicelibs/mdraid.py
blivet/devices/btrfs.py
blivet/devicetree.py
blivet/errors.py
blivet/flags.py
blivet/udev.py

Original bz's are:  1019685, 1090009.
bz#1151649 is already in as bz#1150147
bz#1155151 is already in as bz#1156202.
bz#1090009 required some extra follow up patches

rhel7 cherry picks

---

blivet/formats/fs.py

Increase ext4 maximum size from 16 TiB to 1 EiB (#1231049)

---

blivet/devices/storage.py

StorageDevice.format should never be anything other than an instance
of DeviceFormat or one of its subclasses. All block devices contain data
that is arranged according to some format. The case of empty or
uninitialized or unrecognized formatting is represented by the base class
DeviceFormat.

Enforce and document the fact that StorageDevice.format is always a DeviceFormat.

---

blivet/devices/lvm.py
blivet/osinstall.py

Related to rhinstaller/pykickstart/pull/29

autopart root snapshot support

---

blivet/devices/container.py
blivet/populator.py

These are just some random things I had laying around.

Misc 20150728

---

blivet/devicefactory.py
blivet/devices/lib.py

These were turned up in the course of writing unit tests for `DeviceFactory` (PR forthcoming).

device factory bug fixes

---

blivet/udev.py

Resolves: rhbz#1248476
Fixup of
commit 0f986f932f7a9bcbd48b0b711e5b270a76b72083

Fix ixgbe/bnx2fc fcoe disk detection (#1248476)

---

blivet/devices/md.py
blivet/devices/storage.py
blivet/formats/fs.py
blivet/populator.py
blivet/udev.py
tests/devices_test/device_properties_test.py

This resolves various problems encountered trying to install f23 alpha on md fwraid, beginning with [this bug](https://bugzilla.redhat.com/show_bug.cgi?id=1245191). "Minor cleanup..." doesn't need to go on f23-branch since it doesn't really fix anything.

md fwraid detection

---

blivet/devices/partition.py

Check for it and return, assuming the new size will be assigned to a
disk with enough space.
Resolves: rhbz#1248973

Partition requests may not have partedPartition (#1248973)

---

blivet/mounts.py

Sometimes we may know about a device udev has no (longer) idea about. For
example if an LV is deactivated and thus it's device node gets destroyed. We
shouldn't replace a valid device spec with None in such cases.

Use device name from udev only if it's available (#1252052)

---

scripts/harvest-edd

Signed-off-by: Peter Jones <pjones@redhat.com>

Add an edd test data harvester.

---

python-blivet.spec

See also https://github.com/rhinstaller/libblockdev/pull/49

Require the python libblockdev packages

---

blivet/util.py

This way we can use it not only for the deprecation decorator, but for similar
things as well.
(this is a usable thing I implemented on a dead-end way to implement a ``@singleton`` decorator)

Make the function adding the deprecation doc text more generic

---

blivet/actionlist.py
blivet/blivet.py
blivet/devicetree.py
blivet/partitioning.py
tests/action_test.py
tests/storagetestcase.py

This is built on #263, so ignore commits up to and including "Fix remaining PEP8 violations."
This PR has only two commits as of now.

DeviceTree cleanup

---

blivet/blivet.py
blivet/devicefactory.py
blivet/formats/__init__.py
blivet/formats/fs.py
blivet/osinstall.py
blivet/partitioning.py
blivet/populator.py

These are not so easy to find by pep8 or pylint because they are just strings.

Fix few more camelCase leftovers

---

MANIFEST.in
release_notes.rst

These are more high-level notes about changes done in the releases (at least
major). Useful for people outside of the team, but also for us to easily find
out when and in to what extent something was added.
I believe everybody know what the difference between changelog and release notes is.
Also, obviously, this should be merged after the LVM RAID PR #286 gets merged and then amended with more content related to other big changes.

RFC: Add a file with release notes

---

blivet/threads.py

Thanks for pointing out the problem, @vojtechtrefny.

Blacklisted attrs should be unwrapped, not omitted.

---

blivet/formats/fs.py
tests/formats_test/misc_test.py

Cherry picked from 1.x-branch to master.

FS overhead methods from 1.x-branch

---

blivet/arch.py
blivet/blivet.py
blivet/devicelibs/edd.py
blivet/devices/disk.py
blivet/devices/file.py
blivet/devices/lib.py
blivet/devices/md.py
blivet/devices/optical.py
blivet/devices/storage.py
blivet/fcoe.py
blivet/flags.py
blivet/formats/fs.py
blivet/formats/fslib.py
blivet/formats/prepboot.py
blivet/iscsi.py
blivet/mounts.py
blivet/osinstall.py
blivet/populator/populator.py
blivet/udev.py
blivet/util.py
blivet/zfcp.py
scripts/makebumpver
scripts/makeupdates
scripts/merge-pr
setup.py

PEP 0475 finally fixes this ridiculous problem, so remove all
references to it and pretend that the whole thing never happened.
Depends on https://github.com/rhinstaller/pocketlint/pull/12

Do not retry interruptible system calls.

---

blivet/errors.py
blivet/iscsi.py
blivet/safe_dbus.py
blivet/util.py

This is a totally untested PR just ready for comments. It replaces all the calls to *libiscsi* with DBus calls to *storaged* and its iSCSI functionality. Is it worth testing and getting into a shape that could be merged?

storaged iscsi

---

Makefile
blivet/devicelibs/edd.py
blivet/errors.py
blivet/fcoe.py
blivet/platform.py
blivet/size.py
blivet/util.py
blivet/zfcp.py
tests/formats_test/misc_test.py

Few pep8 fixes for recent commits.

PEP8 fixes

---

blivet/actionlist.py
blivet/autopart.py
blivet/blivet.py
blivet/devicelibs/edd.py
blivet/devicetree.py
blivet/events/changes.py
blivet/events/handler.py
blivet/events/manager.py
blivet/platform.py
blivet/populator/helpers/formatpopulator.py
blivet/populator/helpers/lvm.py

This is the stuff I had to fix to make anaconda able to run using blivet-2.0.

Anaconda to 2.0

---

blivet/autopart.py
blivet/blivet.py
blivet/devicetree.py
blivet/osinstall.py
blivet/populator/populator.py
doc/api/blivet.rst
examples/factory.py
examples/lvm.py
examples/lvm_cache.py
examples/lvm_non_linear.py
examples/partitioning.py
tests/clearpart_test.py
tests/imagebackedtestcase.py
tests/populator_test.py

How many iterations can there be. Let's find out.

Installer isolation: part one

---

blivet/devicefactory.py

When raising an exception like with 'raise SomeException(str(e))', the traceback
from the original exception is lost (just 'raise' to re-raise an exception is
okay). Python 3 has an extended raise statement 'raise SomeException from e'
which preserves the traceback. That's what we should use to make our lives
easier when debugging issues.

Preserve traceback when re-raising exceptions

---

blivet/blivet.py

HyperPAV aliases enable improved I/O efficiency by allowing parallel
access to a real DASD through a base subchannel (device) and multiple
aliases.
Unfortunately, while the kernel recognizes such devices, they don't
seem to generate any actual udev events so that blivet picks them up;
nor do these aliases have a device node. Thus, if they are used at all
during installation, they are not brought online after rebooting, since
they are on the device ignore list. They are not removed from the device
ignore list since there is no entry in dasd.conf, so this patch loops
through all DASD devices in sysfs and adds all detected aliases to dasd.conf.
(HyperPAV support was added in rhel7-branch quite a while ago, but
I forgot to push it to any other branch as well.)

Make sure to add hyperPAV aliases to dasd.conf.

---

blivet/errors.py
blivet/populator.py

Do not add mdarray with no slave (#1321393)

---

blivet/osinstall.py

Well, this is what I get for not testing thoroughly. And what I at
first attributed to rawhide problems actually turned out to be....well,
my problems. Fortunately, not many though.
* osinstall.InstallerStorage.mountpoints needed the @property heading.
Oops.
* Apparently I forgot, in one of the manual rebases I had to do, to actually
move get_free_space (with all the clearpart type stuff, which anaconda needs) into osinstall.InstallerStorage. Mega-oops.
* And some smaller issue with protected devices, where I was just
passing the wrong variable into a function.

Some small, stupid bugfixes to first installer isolation patch set.

---

blivet/devices/btrfs.py

Do not add btrfs volume subvolid to subvolumes mountopts (#1306808)

---

scripts/git-multi-merge

Merging PRs into multiple branches is a tedious and error prone work. In order
to make our lives easier, here comes a simple script doing the multi-merge in a
way we want it to happen.

A simple script for multi-merges we now do

---

blivet/dbus/__init__.py
blivet/dbus/blivet.py
blivet/dbus/object.py
dbus/blivet.conf
dbus/blivet.service
dbus/blivetd
dbus/com.redhat.Blivet1.service
python-blivet.spec
scripts/makebumpver
setup.py
tests/dbus_test.py

This is #371 rebased onto `2.2-devel`. While it may be useful to change the `DeviceFactory` API at some point, I think it is possible to have a fully-functioning dbus interface with the current API.

dbus proof of concept / initial interface (2.2-devel)

---

blivet/actionlist.py
blivet/callbacks.py
blivet/dbus/blivet.py
blivet/devices/storage.py
blivet/devicetree.py
blivet/events/changes.py
blivet/events/handler.py
blivet/events/manager.py
blivet/populator/helpers/formatpopulator.py
blivet/populator/helpers/lvm.py
tests/dbus_test.py

This is implemented via `DeviceTree.recursive_remove`, so I'm open to different names, including `RecursiveRemove`. Since #392 isn't merged yet its commits are appearing here, too. This one starts with 7b2ebfc and currently has six commits.

Add a RemoveDevice method to DBusBlivet

---

blivet/udev.py

Otherwise people may be confused what it actually does.

Improve documentation of the udev.resolve_glob() function

---

blivet/devices/btrfs.py
blivet/flags.py
blivet/osinstall.py

#393 for 2.0-devel and 2.1-devel

Fix root detection on btrfs in rescue mode

---

blivet/autopart.py
blivet/blivet.py
blivet/deviceaction.py
blivet/devicefactory.py
blivet/devicetree.py
blivet/formats/luks.py
blivet/populator/helpers/luks.py
blivet/populator/populator.py
blivet/static_data/__init__.py
blivet/static_data/luks_data.py

- added "static_data" directory
- the following was moved to luks_data singleton:
- luks_devs
- encryption_passphrase
- luks_min_entropy
- save_passphrase
- min_luks_entropy attribute

LUKS data moved to singleton

---

blivet/devicelibs/dasd.py

Fix a typo when checking whether we're using an FBA DASD. (#1233438)

---

blivet/devices/storage.py
blivet/devicetree.py

This is the rhel7-branch version of #429 plus a little cleanup of recursive teardown so that we don't try to tear down inactive lvs (it looks especially ugly when the pv is md since then lvm denies any knowledge of the vg).

Fix a few minor bugs

---

blivet/blivet.py
blivet/devicetree.py
blivet/osinstall.py
tests/blivet_test.py

- fixed bugs from manual merging

Quickfix of merge bugs

---

blivet/devices/partition.py

(Followup for #435)
Related: rhbz#1257997
Resolves: rhbz#1346154

Fix unit arg name in Size.roundToNearest call.

---

tests/devicetree_test.py

This doesn't improve the `make coverage` numbers much, but it does add focused testing of very high-traffic code in `DeviceTree`.

more unit tests for DeviceTree

---

blivet/devicetree.py
blivet/udev.py

Related: rhbz#1200833
-------
Much simpler version of #441

Fix udev.resolve_glob to match device path too

---

blivet/events/handler.py
blivet/populator/helpers/disk.py
blivet/populator/populator.py
blivet/udev.py

Fix udev.resolve_glob and udev.device_is_disk

---

scripts/git-multi-merge

This provides a nice visual check and can prevent some unwanted changes to be
pushed.

Show changes for each branch in git-multi-merge before pushing

---

blivet/mounts.py
python-blivet.spec
tests/storagetestcase.py

Use libmount.Table for parsing /proc/self/mountinfo instead
'manual' parsing from python.

Use libmount for MountsCache

---

blivet/udev.py

Remove deprecated method udev.device_is_realdisk

---

blivet/devices/lvm.py

Fix removing PVs after removing VG (#1358067)

---

blivet/partitioning.py

That's what the LV would take from the VG if not grown at all.

Allign the LV's size up to set the base size for growing

---

blivet/util.py

Eliminate mountpoint symlinks when looking for mounted device

---

blivet/blivet.py
blivet/devicetree.py
blivet/populator/populator.py
blivet/static_data/luks_data.py

Removed backwards API compatibility
API optimized for LUKS data singleton

Broke backwards API compatibility of LUKS handling

---

blivet/devicetree.py

Fix lookup of md partition's disk.

---

scripts/git-multi-merge

Added check if origin and branch exists.
I don't know how to test this, so it's untested.

Add checks to git-multi-merge script

---

blivet/deviceaction.py

When reformatting UUID is now reset

UUID is now cleaned when destroying format

---

blivet/partitioning.py

Fixed merge error

---

python-blivet.spec
setup.py

Port of #491 to 2.0-devel.
Does anyone know how I could get patches onto both 1.20-devel and 2.0-devel by merging?

2.0 packaging tweaks

---

blivet/devices/lvm.py
blivet/partitioning.py

Both of these changes are need to fix the issues reported in rhbz#1374499

Fixes for thpool padding and metadata on rhel7-branch (rhbz#1374499)

---

tests/vmtests/runvmtests.py

This allows using libvirt without ssh authentication.

Functional testing: Add support for libvirt authentication

---

blivet/formats/disklabel.py

Add translators comment for unsupported disklabel names

---

python-blivet.spec

systemd-udev provides 'udevadm' command.

Add 'systemd-udev' to dependencies (#1392591)

---

blivet/mounts.py
tests/devices_test/dependencies_test.py
tests/formats_test/fstesting.py

This should fix problems from #531

Few test-related fixes

---

blivet/formats/fs.py

Thanks to this parted will set the partition type (GUID) to "EFI
System Partition".

Set parted boot flag when creating EFI filesystem

---

blivet/devicelibs/raid.py

Fix detection of linear MD RAID

---

blivet/devicelibs/mdraid.py
blivet/devices/md.py
tests/devices_test.py

Resolves: rhbz#1405141
-------
Cherry picked from `2.1-devel`. Original PR: https://github.com/rhinstaller/blivet/pull/344

Allow custom chunk size specification for MDRaidArrayDevice

---

blivet/devicelibs/disk.py
blivet/devicelibs/raid.py
blivet/devices/disk.py
blivet/populator/populator.py
tests/devicelibs_test/disk_test.py
tests/devices_test/disk_test.py
tests/util_test.py

This is the same as (reiviewed) #547 except it's against `2.2-devel`.

Use libstoragemgmt to present HBA RAID info for disks

---

blivet/devices/lvm.py
blivet/formats/fs.py
tests/devices_test.py

These changes allow the installer to create LVM snapshots as part of the installation process.

Fixes for thin snapshot creation

---

blivet/autopart.py
blivet/devicefactory.py
blivet/devices/lvm.py
blivet/partitioning.py
tests/devicefactory_test.py

As described in the first commit (788d7d0) and in the [bug report](https://bugzilla.redhat.com/show_bug.cgi?id=1131247)

Reserve space for thin pool in the VG not the thin pool itself

---

blivet/util.py

Related: rhbz#1411407
Python is trying to execve the program (specified without the path) in the
fork, iterating over the path list and calling strerror when failing on paths
before it finds the right one. The strerror call can then hang waiting forever
for a lock held by parent process (__libc_setlocale_lock).
NOTE: in the future we want to replace this workaround by using subprocess32
module.

Call subprocess.Popen with absolute path to a binary (#1411407)

---

blivet/devicefactory.py
blivet/devicelibs/lvm.py
blivet/devices/lvm.py
blivet/devices/storage.py
blivet/partitioning.py
blivet/size.py

This is a *rhel7-branch* version of the PR #566 addressing [rhbz#1131247](https://bugzilla.redhat.com/show_bug.cgi?id=1131247)

Reserve space for thin pool(s) to grow in a VG

---

scripts/docs-update

This will automatically generate new documentation from given
branch and push it to the github pages branch.

Add a script for generating and pushing updated documentation

---

blivet/deviceaction.py

Resolves: rhbz#1368986
This is a cherry-pick of an old fix.

Setup device before format create

---

blivet/deviceaction.py
blivet/devices/storage.py
blivet/static_data/lvm_info.py

This is stuff I encountered while testing the API demo on a freshly-installed F26 Alpha Server installation.

Fixes related to missing external deps

---

blivet/devices/luks.py
blivet/devices/storage.py
tests/devices_test/dependencies_test.py

Am I being lazy by just leaving the existing tests there? I was tempted to rewrite them using mock and combine with the new ones I'm adding here.

external dependency tests

---

tests/formats_test/selinux_test.py

Added new test for checking correct function parameters
when setting selinux context while mounting

New test for selinux context setting when mounting

---

tests/vmtests/blivet_reset_vmtest.py
tests/vmtests/vmbackedtestcase.py

Same as #621 just for 3.0-devel (VM tests are only in 3.0).

Use addCleanup for VM tests too

---

blivet/fcoe.py

Rebasing https://github.com/storaged-project/blivet/pull/447
on 2.1-devel

2.1 devel port fcoemon patches from rhel

---

blivet/blivet.py
blivet/devicetree.py
tests/clearpart_test.py
tests/devicetree_test.py

added tags support for ks parameter 'ignoredisk'
added tests for 'ignoredisk' tags
added tags support for ks parameter 'clearpart'
added tests for 'clearpart' tags

Added support for device tags

---

tests/formats_test/selinux_test.py

selinux flag is set to True for the duration of the test

Fixed behavior when selinux is disabled

---

tests/clearpart_test.py
tests/formats_test/selinux_test.py

fixed selinux test
fixed clearpart test

Clearpart test tag fixes

---

blivet/formats/__init__.py
blivet/formats/fs.py
blivet/tasks/fsck.py

Otherwise the resize usually fails.

Do file system check before resize (#1484575)

---

blivet/autopart.py

Do not try to use protected disks for autopart

---

blivet/partitioning.py
tests/partitioning_test.py

(cherry picked from commit d81ed9e8eb4eb861927276b1632ff1a49263fc20)
Resolves: rhbz#1460668

Stop enforcing obsolete limits on partition count. (#1460668)

---

blivet/udev.py

Changed way of obtaining DM device subsystem value
Now libblockdev function is called instead of UUID parsing

DM device subsystem is now obtained by libblockdev

---

blivet/dbus/constants.py
doc/dbus.rst
doc/index.rst

It's important to do this before 2.2 is released.

Mark the DBus interface as unstable.

---

blivet/deviceaction.py
blivet/devices/lvm.py
blivet/devices/md.py
blivet/devicetree.py

Thanks in advance for merging this PR.

Fix minor typos

---

blivet/blivet.py

This is basically
https://github.com/rhinstaller/anaconda/commit/7e1c09e14b25d9c0b99fe5b9b485173e7b85c9ed
for blivet 2

Do not copy ksdata.

---

python-blivet.spec

Our old website is no longer working.

Fix upstream URL in spec

---

python-blivet.spec

This pulls in recent dist-git changes that should improve python2/3 packaging handling and pull in recent Fedora build history.

Spec file updates for python 2/3 and Fedora dist-git.

---

blivet/__init__.py
blivet/devices/__init__.py
blivet/devices/disk.py
blivet/devicetree.py
blivet/errors.py
blivet/nvdimm.py
blivet/udev.py
blivet/util.py
python-blivet.spec
tests/pylint/pylint-false-positives

NVDIMM support

---

blivet/__init__.py
blivet/udev.py

Depends on https://github.com/storaged-project/blivet/pull/694

Rhel7 branch nvdimm devices handling in installer mode

---

blivet/formats/__init__.py
blivet/formats/lvmpv.py

This fixes a pair of udev-related race conditions that have recently popped up in testing.

Work around udev timing issues.

---

blivet/devices/lvm.py

Deactivate incomplete lvm in DeviceTree.teardownAll

---

blivet/devicetree.py
blivet/formats/luks.py
blivet/udev.py

Add version to the LUKS format

---

blivet/arch.py
blivet/devices/partition.py
blivet/flags.py
blivet/formats/disklabel.py
tests/devices_test/partition_test.py
tests/formats_test/disklabel_test.py

This PR drops a few old legacy code paths that haven't been needed for some time as well  as adding support for UEFI on ARMv7

Some ARMv7 cleanups and add UEFI support for ARMv7

---

blivet/udev.py

Port of
commit 55a5feca56e7be9474ed09d98a9fb4f1ec73c14c

Fix ixgbe/bnx2fc fcoe disk detection (#1651506)

---

tests/devicetree_test.py

Add a test for DeviceTree.get_related_disks

---

blivet/iscsi.py

Do not try to login to iBFTs with active session

---

tests/action_test.py
tests/devices_test/dependencies_test.py

Fixes for failing tests on systems with missing btrfs, hfsplus etc.

Various test related fixes

---

blivet/devicefactory.py
blivet/devices/cache.py
blivet/devices/lvm.py
blivet/devices/storage.py
blivet/errors.py
blivet/formats/__init__.py
blivet/formats/fs.py
blivet/populator/helpers/populatorhelper.py
blivet/safe_dbus.py
blivet/tasks/fstask.py
tests/action_test.py
tests/imagebackedtestcase.py
tests/populator_test.py
tests/vmtests/vmbackedtestcase.py

Remove unnecessary pass statements

---

blivet/devices/disk.py
blivet/populator/helpers/disk.py
blivet/udev.py
tests/devices_test/tags_test.py

The changes are required by https://github.com/rhinstaller/anaconda/pull/1960

Use only sysfs for iscsi device attributes

---

blivet/formats/disklabel.py
blivet/util.py

Use dasd disklabel for vm disks backed by dasds.

---

blivet/devicefactory.py
blivet/devices/lvm.py
blivet/size.py
tests/size_test.py

See the particular commit messages for details.

Fixes for factory thin pool calculations

---

blivet/populator/helpers/dmraid.py

https://bugzilla.redhat.com/show_bug.cgi?id=1723979

Check dmraid status before trying to activate array during populate

---

blivet/formats/fs.py
tests/devices_test/device_properties_test.py
tests/devices_test/lvm_test.py

Resolves: rhbz#1372622
Fixes #807

Set min size for XFS to 16 MiB

---

blivet/udev.py
tests/udev_test.py

Add recognition of Dell FW RAID to udev.device_is_disk.

---

blivet/devicelibs/edd.py

Resolves: rhbz#1824195
Submitted-by: Renaud Métrich <rmetrich@redhat.com>

Fix typo in string formatter in EddEntry

---

blivet/devices/partition.py

On s390x in particular, some partition alignment issue is causing fractional
sizes to be reported. Pykickstart doesn't take anything except int values for
partition info, hence the call to roundToNearest.
This change only affects the data that is written to ks.cfg.
Resolves: rhbz#1850670
--------
This is just a cherry-pick from rhel7-branch, see #435 and #439 for more details.

Round down to nearest MiB value when writing ks parittion info.

---

blivet/formats/luks.py
blivet/populator/helpers/luks.py
blivet/udev.py

Just few small change so we are able to remove these devices.

Standalone DM Integrity devices support improvement

---

MANIFEST.in
README
README.md
python-blivet.spec
setup.py

Some small changes in our `setup.py` to make it work with PyPI infrastructure.
I've also added new README to make Blivet's PyPI page look nicer. It is mostly a copy of the blivet-gui README, feel free to suggest improvements.
You can test the result on the Test PyPI: https://test.pypi.org/project/blivet/ (ignore the version change, PyPI doesn't allow uploading same version twice so I had to run bumpver few times when making the changes).
Fixes: #858

Changes for PyPI support

---

blivet/formats/fs.py
blivet/tasks/availability.py
blivet/tasks/fsck.py
blivet/tasks/fslabeling.py
blivet/tasks/fsmkfs.py
tests/formats_test/fs_test.py

Add basic F2FS support

---

blivet/__init__.py
blivet/formats/fs.py
blivet/tasks/availability.py
blivet/tasks/fsck.py
blivet/tasks/fsinfo.py
blivet/tasks/fsresize.py
tests/formats_test/fs_test.py
tests/formats_test/fstesting.py

XFS grow support

---

blivet/devicefactory.py
blivet/formats/luks.py
tests/devicefactory_test.py
tests/formats_test/luks_test.py

Add support for specifying sector size for LUKS 2 devices

---

blivet/formats/luks.py

Allow specifying custom hash function for LUKS 2 format

---

Makefile

Two small issues discovered during the 3.3.0 release.

Two makefile fixes

---

zanata.xml

I forgot to remove the config file #826

Remove Zanata config file

---

blivet/blivet.py
blivet/devicefactory.py
blivet/devices/lvm.py
blivet/formats/fs.py
blivet/populator/helpers/lvm.py
blivet/tasks/availability.py
blivet/tasks/fsmkfs.py
doc/lvmvdo.rst
examples/lvm_vdo.py
python-blivet.spec
tests/action_test.py
tests/devicefactory_test.py
tests/devices_test/lvm_test.py
tests/formats_test/methods_test.py
tests/vmtests/blivet_reset_vmtest.py
tests/vmtests/runvmtests.py

LVM VDO create support

---

blivet/formats/fs.py
blivet/util.py

Signed-off-by: Renaud Métrich <rmetrich@redhat.com>
Resolves: rhbz#1934076
----
Backport of #938 to RHEL 8

apply directory's SELinux context to freshly created mount points

---

blivet/deviceaction.py

Make sure the device is setup before configuring its format

---

.github/workflows/anaconda_tests.yml

Use anaconda-ci container which has all dependencies to run the tests. In this container build and install the blivet from the current PR and then run the Anaconda tests.

Run Anaconda tests on blivet pull requests

---

blivet/devicefactory.py
blivet/devices/cache.py
blivet/events/manager.py
blivet/size.py
blivet/static_data/luks_data.py
blivet/tasks/fsck.py
blivet/tasks/fsinfo.py
blivet/tasks/fsminsize.py
blivet/tasks/fsreadlabel.py
blivet/tasks/fsresize.py
blivet/tasks/fssize.py
blivet/tasks/fssync.py
blivet/tasks/fswritelabel.py
blivet/tasks/fswriteuuid.py
blivet/tasks/lukstasks.py
blivet/tasks/pvtask.py
blivet/util.py
tests/pylint/runpylint.py
tests/tasks_test/basic_tests.py

Misc pylint fixes

---

blivet/flags.py

flags: Fix leaking file descriptor

---

blivet/devices/btrfs.py
blivet/formats/fs.py
blivet/i18n.py
blivet/partitioning.py
blivet/util.py
doc/conf.py
tests/devices_test/device_properties_test.py
tests/pylint/pylintrc
tests/pylint/runpylint.py

Pylint warning fixes

---

blivet/deviceaction.py

It should be ACTION_OBJECT_DEVICE not ACTION_OBJECT_FORMAT.

Fix object type for ActionConfigureDevice

---

blivet/devicelibs/stratis.py
blivet/formats/fs.py
blivet/formats/stratis.py
blivet/static_data/stratis_info.py

We plan to support only the new 3.0 API so we don't need to be
backward compatible.

Adjust to Stratis 3.0 API

---

tests/storage_tests/devices_test/lvm_test.py

The first commit is shared from #1047

Add storage tests for more LVM RAID levels

---

tests/storage_tests/devices_test/lvm_test.py

tests: Add test for creating and attaching cache pools

---

blivet/devicefactory.py
blivet/devicelibs/stratis.py
blivet/devices/stratis.py
blivet/tasks/availability.py
tests/devicefactory_test.py
tests/devices_test/stratis_test.py
tests/vmtests/blivet_reset_vmtest.py
tests/vmtests/runvmtests.py

This uses the updated tool for predicting pool and filesystem metadata sizes and adds support for specifying size when creating a file system.

Stratis support update for stratis 3.1.0

---

blivet/devices/disk.py
blivet/zfcp.py

Fixes suggested in https://github.com/storaged-project/blivet/pull/1035#pullrequestreview-1023659533

Improve zFCP related code

---

tests/conftest.py
tests/unit_tests/populator_test.py

Fix infinite loop when running tests with pytests

---

blivet/util.py
tests/unit_tests/util_test.py

The version used is a merger of the original blivet code and anaconda's counterpart from commit f22386ef. Note that the referenced commit has not been merged, and so isn't reachable in the repository itself. See below for relevant GitHub links. Note also that the function in anaconda has been retired in favor of using the blivet's one.
New:
- checks for bad input
- check for no data
- tests
See also:
- https://github.com/rhinstaller/anaconda/pull/4338
- https://github.com/rhinstaller/anaconda/commit/f22386efafe33df7f8182e65aaf99279904344c6

Backport total_memory improvements from anaconda

---

python-blivet.spec

https://fedoraproject.org/wiki/Changes/SPDX_Licenses_Phase_1

spec: Change license string to the SPDX format required by Fedora

---

blivet/arch.py

add loongarch support
Signed-off-by: mahailiang <mahailiang@uniontech.com>

add loongarch support

---

blivet/udev.py

When running in a chroot environment (e.g.mock) there is a race between
udev actually settling the discovered loopback/dm device names and a
program running 'udevadm settle', as latter becomes a no-op in chroot:
<mock-chroot> sh-5.1# udevadm settle
Running in chroot, ignoring request.
This patch grabs stdout of 'udevadm settle' command, tries to
determine whether the command was ignored, and adds an 1s delay if it was.
1s delay was chosen arbitrary, to succeed in used environment.
However, it should be sufficient for most chrooted environments, as
significant device changes are not expected there.

Add a forced delay to udev settle in chroot environments

---

doc/api/blivet.rst
doc/api/devices.rst
doc/api/formats.rst

Adding some of the new public API classes we forgot to add when
adding the new features: new filesystems, integrity and errors.

Update public API documentation

---

tests/storage_tests/devices_test/lvm_test.py

The directory is sometimes not removed. This is a known bug that causes subsequent test cases to fail.

tests: Force remove LVM VG /dev/ entry not removed by vgremove

---

.github/workflows/unit_tests.yml
blivet/util.py
tests/unit_tests/action_test.py
tests/unit_tests/blivettestcase.py
tests/unit_tests/dbus_test.py
tests/unit_tests/devicefactory_test.py
tests/unit_tests/devices_test/device_dependencies_test.py
tests/unit_tests/devices_test/device_methods_test.py
tests/unit_tests/devices_test/lvm_test.py
tests/unit_tests/formats_tests/methods_test.py
tests/unit_tests/misc_test.py

This should be a final fix for #870 In addition to the changes to the unit tests, I have added a GH action to run the unit tests on Ubuntu so we can be sure we won't break this in the future.

Unit test fixes -- run as normal user and GH action

---

blivet/iscsi.py
misc/install-test-dependencies.yml
tests/storage_tests/__init__.py
tests/storage_tests/iscsi_test.py
tests/storage_tests/storagetestcase.py

Allow changing iSCSI initiator name after setting it

---

blivet/actionlist.py
blivet/dbus/blivet.py
blivet/dbus/object.py
tests/unit_tests/dbus_test.py

Two more fixes arising from the CSI PoC...

DBus: reset fix and accounting for pruned actions

---

blivet/devices/md.py
tests/unit_tests/devices_test/md_test.py

Related to libblockdev change https://github.com/storaged-project/libblockdev/pull/901

md: Adapt libblockdev 3.0 mdraid bitmap arg changes

---

Makefile

This reverts commit 642a69814e4b80c80c5110760adc1a0a347d2b9e.
----
I need to redo this, some of the removed targets are used by the makebumpver script (which also needs cleanup).

Revert "Makefile cleanup"

---

blivet/devicetree.py
tests/unit_tests/devicetree_test.py

Related: https://github.com/rhinstaller/anaconda/pull/4835

Add btrfs subvolume specification to devicetree.resolve_device

---

blivet/iscsi.py

iscsi: Save firmware initiator name to /etc/iscsi/initiatorname.iscsi

---

blivet/iscsi.py
misc/install-test-dependencies.yml
tests/storage_tests/__init__.py
tests/storage_tests/iscsi_test.py
tests/storage_tests/storagetestcase.py

Backport iSCSI initiator name related fixes to RHEL 9

---

tests/storage_tests/iscsi_test.py

Changed how we create the initiator name ACLs based on RTT test case for rhbz#2084043 and also improved the test case itself.

tests: Improve iscsi_test.ISCSITestCase

---

blivet/iscsi.py

Related to https://bugzilla.redhat.com/show_bug.cgi?id=2220657

iscsi ibft and auth algs fixes

---

blivet/iscsi.py

No functional change, avoiding deprecated stuff.

iscsi: the 'UDisks' terminology + cleanup

---

blivet/nvme.py

Also don't overwrite existing files during startup() since they might have been supplied by early boot stages.

nvme: Align HostNQN and HostID format to TP4126

---

blivet/fcoe.py
blivet/iscsi.py

fcoe/iscsi: Use libblockdev to laod modules instead of modprobe

---

.github/workflows/blivetgui_tests.yml
misc/ci.Dockerfile
misc/install-test-dependencies.yml

A GH action to run blivet-gui test suite so we can avoid issues like https://github.com/storaged-project/blivet-gui/pull/418 in the future.

Blivet-GUI reverse dependency testing in GH actions

---

blivet/devices/md.py
tests/storage_tests/devices_test/__init__.py
tests/storage_tests/devices_test/md_test.py
tests/storage_tests/storagetestcase.py

MD RAID tests with some small fixes.

tests: Add storage test case for MD RAID

---

misc/install-test-dependencies.yml
tests/storage_tests/formats_test/fs_test.py
tests/storage_tests/formats_test/labeling_test.py
tests/unit_tests/formats_tests/init_test.py

Label tests moved to unit tests section and GFS2 tests enabled.

Two small formats tests changes

---

blivet/populator/helpers/mdraid.py

Follow-up for a73bb08255a97cf4f16c764ef09341a2421318d6
Fixes: #1199

Fix UnboundLocalError in MD populator

---

blivet/blivet.py
blivet/formats/fs.py
blivet/fstab.py
blivet/tasks/availability.py
misc/Vagrantfile
misc/install-test-dependencies.yml
tests/storage_tests/fstab_test.py
tests/unit_tests/fstab_test.py

The biggest change is libmount requirement which is not available on Debian/Ubuntu, so we should be able to work without it if possible. The other changes are mostly small fixes in the dependencies installation.

Fixes for latest Ubuntu/Debian support

---

blivet/tasks/availability.py

stratisd is neither autostarted after installing the package nor DBus activated so we need to try to start it first.

Try to start stratisd before checking its availability

---

blivet/devices/__init__.py
blivet/devices/luks.py
blivet/formats/luks.py
blivet/populator/helpers/__init__.py
blivet/populator/helpers/dm.py
blivet/populator/helpers/luks.py
blivet/udev.py
tests/unit_tests/populator_test.py

Just a basic support so we are able to recognize BitLocker format and devices unlocked with cryptsetup.

Add basic support for BitLocker devices

---

blivet/tasks/availability.py

We don't want to try to start services that are already running.

availability: Fix starting DBus services

---

blivet/populator/helpers/disk.py

replenish：https://github.com/storaged-project/blivet/pull/1223
as issuse https://github.com/storaged-project/blivet/issues/1221 verify，need to convert as same output

fix compare uuid fail

---

blivet/arch.py

reopen #1240 against 3.10-devel

fix issue #1239

---

blivet/formats/fs.py
blivet/tasks/fslabeling.py
blivet/tasks/fsmkfs.py
tests/storage_tests/formats_test/fs_test.py
tests/storage_tests/formats_test/fstesting.py
tests/storage_tests/formats_test/labeling_test.py
tests/unit_tests/formats_tests/init_test.py

Related: https://github.com/linux-system-roles/storage/pull/418

Add support for setting label when creating GFS2 format

---

tests/storage_tests/devices_test/md_test.py

tests: Add a test case with MD array on LUKS

---

tests/storage_tests/devices_test/lvm_test.py

Forgotten logging initialization from debugging.

tests: Remove logging from LVMTestCase

---

blivet/devices/partition.py

[storage.log](https://github.com/user-attachments/files/16558156/storage.log)

devices: catch exceptions where invalid access happens first

---

blivet/devicefactory.py

Log reason for ignoring disks in devicefactory

---

.packit.yaml
Makefile

Preparing for a new release, just some small changes to Makefile and packit configuration to (hopefully) automate the next Fedora build.

Release process fixes in Makefile and packit

---

python-blivet.spec

These are the URLs of the tarballs uploaded by us to every release.

spec: Update sources URL

---

.packit.yaml
plans/blivet-gui.fmf
plans/tests.fmf

"fedora-latest" is the latest branched release (now Fedora 41).

packit: Switch to latest Fedora for tests

---

python-blivet.spec

We need to make sure our downstream changes are not overwriten by packit when doing a new release.

Sync spec with downstream

---

blivet/iscsi.py

iscsi: Use node.startup=onboot option for Login

---

blivet/formats/luks.py

We are currently using the "allow-discards" in /etc/crypttab to set the discards/fstrim feature for LUKS, but that doesn't work for Fedora Silverblue so we need to set the persistent flag in the LUKS header instead.
Resolves: RHEL-82430

Set persitent allow-discards flag for newly created LUKS devices

---

tests/storage_tests/devices_test/md_test.py

Some more tests to better cover various MD use cases.

New MD RAID storage test case

---

blivet/devices/lvm.py
blivet/formats/lvmpv.py
blivet/populator/helpers/lvm.py
blivet/tasks/pvtask.py
tests/storage_tests/devices_test/lvm_test.py
tests/unit_tests/populator_test.py

LVMPV format size

---

blivet/partitioning.py

The generic 'Unable to allocate requested partition scheme' is not very helpful, we should try to include additional information if possible.
Resolves: RHEL-8005

Include additional information in PartitioningError

---

blivet/tasks/fssize.py
blivet/udev.py
tests/storage_tests/formats_test/fstesting.py

More fixes for getting FS size from udev

---

blivet/devicelibs/stratis.py
blivet/devices/stratis.py
blivet/formats/stratis.py
blivet/populator/helpers/stratis.py
blivet/static_data/stratis_info.py
tests/storage_tests/devices_test/stratis_test.py

Latest stratis introduced changes to encryption implementation (the LUKS devices are not longer "publicly visible"). Support for stopping and starting stratis pools was also added recently.

Stratis 3.8.0 changes adjustment

---

blivet/blivet.py
blivet/deviceaction.py
blivet/devicetree.py
blivet/populator/helpers/luks.py
blivet/populator/helpers/lvm.py
tests/storage_tests/devices_test/lvm_test.py
tests/unit_tests/devices_test/lvm_test.py

RHEL 10 backport of #1383
Resolves: RHEL-84685
Resolves: RHEL-84663

Make ActionDestroyFormat optional when the device is also scheduled to be removed

---

tests/storage_tests/devices_test/partition_test.py

This supplements the existing tests which use sparse files. These new test cases actually run do_it() and check the result after reset. More test cases will follow.

Add some basic partitioning storage tests

---

blivet/devices/partition.py
tests/storage_tests/devices_test/partition_test.py

Wipe end partition before creating it as well as the start
